-- Фото з офіційної сторінки Papa Carlo: https://papa-carlo.com.ua/ua/dverne-polotno-st-04/
-- Завантажте вміст папки tmp\papa-carlo-variants\catalog-113 у bucket catalog-images, зберігши шлях variants/papa-carlo/catalog-113.

insert into public.product_variants (product_slug, selections, image_path, sort_order)
values
('catalog-113', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-113/1227.jpg', 1227),
('catalog-113', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-113/1228.jpg', 1228),
('catalog-113', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-113/1229.jpg', 1229),
('catalog-113', '{"color":"ясен білий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-113/1230.jpg', 1230),
('catalog-113', '{"color":"ясен білий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-113/1231.jpg', 1231),
('catalog-113', '{"color":"дуб ciрий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-113/1232.jpg', 1232),
('catalog-113', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-113/1233.jpg', 1233),
('catalog-113', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-113/1234.jpg', 1234),
('catalog-113', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-113/1235.jpg', 1235),
('catalog-113', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-113/1236.jpg', 1236),
('catalog-113', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-113/1237.jpg', 1237),
('catalog-113', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-113/1238.jpg', 1238),
('catalog-113', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-113/1239.jpg', 1239),
('catalog-113', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-113/1240.jpg', 1240),
('catalog-113', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-113/1241.jpg', 1241),
('catalog-113', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-113/1242.jpg', 1242),
('catalog-113', '{"color":"бетон сiрий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-113/1243.jpg', 1243),
('catalog-113', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-113/1244.jpg', 1244),
('catalog-113', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-113/1245.jpg', 1245),
('catalog-113', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-113/2226.jpg', 2226),
('catalog-113', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-113/2227.jpg', 2227),
('catalog-113', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-113/3874.jpg', 3874),
('catalog-113', '{"color":"ясен білий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-113/3875.jpg', 3875),
('catalog-113', '{"color":"дуб ciрий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-113/3876.jpg', 3876),
('catalog-113', '{"color":"дуб кремовий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-113/3877.jpg', 3877),
('catalog-113', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-113/3878.jpg', 3878),
('catalog-113', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-113/3879.jpg', 3879),
('catalog-113', '{"color":"бетон сiрий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-113/3880.jpg', 3880),
('catalog-113', '{"color":"сірий матовий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-113/3881.jpg', 3881),
('catalog-113', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-113/4122.jpg', 4122),
('catalog-113', '{"color":"ясен білий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-113/4123.jpg', 4123),
('catalog-113', '{"color":"дуб ciрий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-113/4124.jpg', 4124),
('catalog-113', '{"color":"дуб кремовий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-113/4125.jpg', 4125),
('catalog-113', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-113/4126.jpg', 4126),
('catalog-113', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-113/4127.jpg', 4127),
('catalog-113', '{"color":"бетон сiрий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-113/4128.jpg', 4128),
('catalog-113', '{"color":"сірий матовий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-113/4129.jpg', 4129),
('catalog-113', '{"color":"сірий матовий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-113/4680.jpg', 4680),
('catalog-113', '{"color":"кремовий матовий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-113/4867.jpg', 4867),
('catalog-113', '{"color":"кремовий матовий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-113/4868.jpg', 4868),
('catalog-113', '{"color":"кремовий матовий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-113/4869.jpg', 4869),
('catalog-113', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-113/4870.jpg', 4870),
('catalog-113', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-113/4871.jpg', 4871)
on conflict (product_slug, selections) do update
set image_path = excluded.image_path, sort_order = excluded.sort_order, is_active = true;
