-- Фото з офіційної сторінки Papa Carlo: https://papa-carlo.com.ua/ua/dverne-polotno-st-25/
-- Завантажте вміст папки tmp\papa-carlo-variants\catalog-114 у bucket catalog-images, зберігши шлях variants/papa-carlo/catalog-114.

insert into public.product_variants (product_slug, selections, image_path, sort_order)
values
('catalog-114', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-114/2054.jpg', 2054),
('catalog-114', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-114/2055.jpg', 2055),
('catalog-114', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-114/2056.jpg', 2056),
('catalog-114', '{"color":"ясен білий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-114/2057.jpg', 2057),
('catalog-114', '{"color":"ясен білий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-114/2058.jpg', 2058),
('catalog-114', '{"color":"дуб ciрий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-114/2059.jpg', 2059),
('catalog-114', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-114/2060.jpg', 2060),
('catalog-114', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-114/2061.jpg', 2061),
('catalog-114', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-114/2062.jpg', 2062),
('catalog-114', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-114/2063.jpg', 2063),
('catalog-114', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-114/2064.jpg', 2064),
('catalog-114', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-114/2065.jpg', 2065),
('catalog-114', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-114/2066.jpg', 2066),
('catalog-114', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-114/2067.jpg', 2067),
('catalog-114', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-114/2068.jpg', 2068),
('catalog-114', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-114/2069.jpg', 2069),
('catalog-114', '{"color":"бетон сiрий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-114/2070.jpg', 2070),
('catalog-114', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-114/2071.jpg', 2071),
('catalog-114', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-114/2072.jpg', 2072),
('catalog-114', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-114/2268.jpg', 2268),
('catalog-114', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-114/2269.jpg', 2269),
('catalog-114', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-114/4026.jpg', 4026),
('catalog-114', '{"color":"ясен білий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-114/4027.jpg', 4027),
('catalog-114', '{"color":"дуб ciрий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-114/4028.jpg', 4028),
('catalog-114', '{"color":"дуб кремовий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-114/4029.jpg', 4029),
('catalog-114', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-114/4030.jpg', 4030),
('catalog-114', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-114/4031.jpg', 4031),
('catalog-114', '{"color":"бетон сiрий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-114/4032.jpg', 4032),
('catalog-114', '{"color":"сірий матовий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-114/4033.jpg', 4033),
('catalog-114', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-114/4274.jpg', 4274),
('catalog-114', '{"color":"ясен білий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-114/4275.jpg', 4275),
('catalog-114', '{"color":"дуб ciрий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-114/4276.jpg', 4276),
('catalog-114', '{"color":"дуб кремовий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-114/4277.jpg', 4277),
('catalog-114', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-114/4278.jpg', 4278),
('catalog-114', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-114/4279.jpg', 4279),
('catalog-114', '{"color":"бетон сiрий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-114/4280.jpg', 4280),
('catalog-114', '{"color":"сірий матовий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-114/4281.jpg', 4281),
('catalog-114', '{"color":"сірий матовий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-114/4699.jpg', 4699),
('catalog-114', '{"color":"кремовий матовий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-114/4966.jpg', 4966),
('catalog-114', '{"color":"кремовий матовий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-114/4967.jpg', 4967),
('catalog-114', '{"color":"кремовий матовий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-114/4968.jpg', 4968),
('catalog-114', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-114/4969.jpg', 4969),
('catalog-114', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-114/4970.jpg', 4970)
on conflict (product_slug, selections) do update
set image_path = excluded.image_path, sort_order = excluded.sort_order, is_active = true;
