-- Фото з офіційної сторінки Papa Carlo: https://papa-carlo.com.ua/ua/dverne-polotno-pl-04/
-- Завантажте вміст папки tmp\papa-carlo-variants\catalog-104 у корінь bucket catalog-images.

insert into public.product_variants (product_slug, selections, image_path, sort_order)
values
('catalog-104', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-103.jpg', 103),
('catalog-104', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-104.jpg', 104),
('catalog-104', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-105.jpg', 105),
('catalog-104', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-106.jpg', 106),
('catalog-104', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-107.jpg', 107),
('catalog-104', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-108.jpg', 108),
('catalog-104', '{"color":"ясен білий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-109.jpg', 109),
('catalog-104', '{"color":"ясен білий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-110.jpg', 110),
('catalog-104', '{"color":"ясен білий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-111.jpg', 111),
('catalog-104', '{"color":"ясен білий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-112.jpg', 112),
('catalog-104', '{"color":"дуб ciрий","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-113.jpg', 113),
('catalog-104', '{"color":"дуб ciрий","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-114.jpg', 114),
('catalog-104', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-115.jpg', 115),
('catalog-104', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-116.jpg', 116),
('catalog-104', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-117.jpg', 117),
('catalog-104', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-118.jpg', 118),
('catalog-104', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-119.jpg', 119),
('catalog-104', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-120.jpg', 120),
('catalog-104', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-121.jpg', 121),
('catalog-104', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-122.jpg', 122),
('catalog-104', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-123.jpg', 123),
('catalog-104', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-124.jpg', 124),
('catalog-104', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-125.jpg', 125),
('catalog-104', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-126.jpg', 126),
('catalog-104', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-127.jpg', 127),
('catalog-104', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-128.jpg', 128),
('catalog-104', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-129.jpg', 129),
('catalog-104', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-130.jpg', 130),
('catalog-104', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-131.jpg', 131),
('catalog-104', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-132.jpg', 132),
('catalog-104', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-133.jpg', 133),
('catalog-104', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-134.jpg', 134),
('catalog-104', '{"color":"бетон сiрий","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-135.jpg', 135),
('catalog-104', '{"color":"бетон сiрий","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-136.jpg', 136),
('catalog-104', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-137.jpg', 137),
('catalog-104', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-138.jpg', 138),
('catalog-104', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-139.jpg', 139),
('catalog-104', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-140.jpg', 140),
('catalog-104', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-643.jpg', 643),
('catalog-104', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-644.jpg', 644),
('catalog-104', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-645.jpg', 645),
('catalog-104', '{"color":"ясен білий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-646.jpg', 646),
('catalog-104', '{"color":"ясен білий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-647.jpg', 647),
('catalog-104', '{"color":"дуб ciрий","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-648.jpg', 648),
('catalog-104', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-649.jpg', 649),
('catalog-104', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-650.jpg', 650),
('catalog-104', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-651.jpg', 651),
('catalog-104', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-652.jpg', 652),
('catalog-104', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-653.jpg', 653),
('catalog-104', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-654.jpg', 654),
('catalog-104', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-655.jpg', 655),
('catalog-104', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-656.jpg', 656),
('catalog-104', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-657.jpg', 657),
('catalog-104', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-658.jpg', 658),
('catalog-104', '{"color":"бетон сiрий","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-659.jpg', 659),
('catalog-104', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-660.jpg', 660),
('catalog-104', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-661.jpg', 661),
('catalog-104', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-2294.jpg', 2294),
('catalog-104', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-2295.jpg', 2295),
('catalog-104', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-2296.jpg', 2296),
('catalog-104', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-2297.jpg', 2297),
('catalog-104', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-2298.jpg', 2298),
('catalog-104', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-2299.jpg', 2299),
('catalog-104', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-3129.jpg', 3129),
('catalog-104', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-3130.jpg', 3130),
('catalog-104', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-3131.jpg', 3131),
('catalog-104', '{"color":"ясен білий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-3132.jpg', 3132),
('catalog-104', '{"color":"ясен білий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-3133.jpg', 3133),
('catalog-104', '{"color":"ясен білий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-3134.jpg', 3134),
('catalog-104', '{"color":"дуб ciрий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-3135.jpg', 3135),
('catalog-104', '{"color":"дуб ciрий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-3136.jpg', 3136),
('catalog-104', '{"color":"дуб ciрий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-3137.jpg', 3137),
('catalog-104', '{"color":"дуб кремовий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-3138.jpg', 3138),
('catalog-104', '{"color":"дуб кремовий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-3139.jpg', 3139),
('catalog-104', '{"color":"дуб кремовий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-3140.jpg', 3140),
('catalog-104', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-3141.jpg', 3141),
('catalog-104', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-3142.jpg', 3142),
('catalog-104', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-3143.jpg', 3143),
('catalog-104', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-3144.jpg', 3144),
('catalog-104', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-3145.jpg', 3145),
('catalog-104', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-3146.jpg', 3146),
('catalog-104', '{"color":"бетон сiрий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-3147.jpg', 3147),
('catalog-104', '{"color":"бетон сiрий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-3148.jpg', 3148),
('catalog-104', '{"color":"бетон сiрий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-3149.jpg', 3149),
('catalog-104', '{"color":"сірий матовий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-3150.jpg', 3150),
('catalog-104', '{"color":"сірий матовий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-3151.jpg', 3151),
('catalog-104', '{"color":"сірий матовий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-3152.jpg', 3152),
('catalog-104', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-4354.jpg', 4354),
('catalog-104', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-4355.jpg', 4355),
('catalog-104', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-4356.jpg', 4356),
('catalog-104', '{"color":"ясен білий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-4357.jpg', 4357),
('catalog-104', '{"color":"ясен білий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-4358.jpg', 4358),
('catalog-104', '{"color":"ясен білий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-4359.jpg', 4359),
('catalog-104', '{"color":"дуб ciрий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-4360.jpg', 4360),
('catalog-104', '{"color":"дуб ciрий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-4361.jpg', 4361),
('catalog-104', '{"color":"дуб ciрий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-4362.jpg', 4362),
('catalog-104', '{"color":"дуб кремовий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-4363.jpg', 4363),
('catalog-104', '{"color":"дуб кремовий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-4364.jpg', 4364),
('catalog-104', '{"color":"дуб кремовий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-4365.jpg', 4365),
('catalog-104', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-4366.jpg', 4366),
('catalog-104', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-4367.jpg', 4367),
('catalog-104', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-4368.jpg', 4368),
('catalog-104', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-4369.jpg', 4369),
('catalog-104', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-4370.jpg', 4370),
('catalog-104', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-4371.jpg', 4371),
('catalog-104', '{"color":"бетон сiрий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-4372.jpg', 4372),
('catalog-104', '{"color":"бетон сiрий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-4373.jpg', 4373),
('catalog-104', '{"color":"бетон сiрий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-4374.jpg', 4374),
('catalog-104', '{"color":"сірий матовий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-4375.jpg', 4375),
('catalog-104', '{"color":"сірий матовий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-4376.jpg', 4376),
('catalog-104', '{"color":"сірий матовий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-4377.jpg', 4377),
('catalog-104', '{"color":"сірий матовий","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-4711.jpg', 4711),
('catalog-104', '{"color":"сірий матовий","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-4712.jpg', 4712),
('catalog-104', '{"color":"сірий матовий","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-4713.jpg', 4713),
('catalog-104', '{"color":"кремовий матовий","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-5032.jpg', 5032),
('catalog-104', '{"color":"кремовий матовий","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-5033.jpg', 5033),
('catalog-104', '{"color":"кремовий матовий","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-5034.jpg', 5034),
('catalog-104', '{"color":"кремовий матовий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-5035.jpg', 5035),
('catalog-104', '{"color":"кремовий матовий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-5036.jpg', 5036),
('catalog-104', '{"color":"кремовий матовий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-5037.jpg', 5037),
('catalog-104', '{"color":"кремовий матовий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-5038.jpg', 5038),
('catalog-104', '{"color":"кремовий матовий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-5039.jpg', 5039),
('catalog-104', '{"color":"кремовий матовий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-5040.jpg', 5040),
('catalog-104', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-5041.jpg', 5041),
('catalog-104', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-5042.jpg', 5042),
('catalog-104', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-5043.jpg', 5043),
('catalog-104', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-104-5044.jpg', 5044),
('catalog-104', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-104-5045.jpg', 5045),
('catalog-104', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-104-5046.jpg', 5046)
on conflict (product_slug, selections) do update
set image_path = excluded.image_path, sort_order = excluded.sort_order, is_active = true;
