-- Фото з офіційної сторінки Papa Carlo: https://papa-carlo.com.ua/ua/dverne-polotno-pl-14/
-- Завантажте вміст папки tmp\papa-carlo-variants\catalog-107 у корінь bucket catalog-images.

insert into public.product_variants (product_slug, selections, image_path, sort_order)
values
('catalog-107', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-495.jpg', 495),
('catalog-107', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-496.jpg', 496),
('catalog-107', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-497.jpg', 497),
('catalog-107', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-498.jpg', 498),
('catalog-107', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-499.jpg', 499),
('catalog-107', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-500.jpg', 500),
('catalog-107', '{"color":"ясен білий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-501.jpg', 501),
('catalog-107', '{"color":"ясен білий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-502.jpg', 502),
('catalog-107', '{"color":"ясен білий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-503.jpg', 503),
('catalog-107', '{"color":"ясен білий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-504.jpg', 504),
('catalog-107', '{"color":"дуб ciрий","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-505.jpg', 505),
('catalog-107', '{"color":"дуб ciрий","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-506.jpg', 506),
('catalog-107', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-507.jpg', 507),
('catalog-107', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-508.jpg', 508),
('catalog-107', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-509.jpg', 509),
('catalog-107', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-510.jpg', 510),
('catalog-107', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-511.jpg', 511),
('catalog-107', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-512.jpg', 512),
('catalog-107', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-513.jpg', 513),
('catalog-107', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-514.jpg', 514),
('catalog-107', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-515.jpg', 515),
('catalog-107', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-516.jpg', 516),
('catalog-107', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-517.jpg', 517),
('catalog-107', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-518.jpg', 518),
('catalog-107', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-519.jpg', 519),
('catalog-107', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-520.jpg', 520),
('catalog-107', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-521.jpg', 521),
('catalog-107', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-522.jpg', 522),
('catalog-107', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-523.jpg', 523),
('catalog-107', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-524.jpg', 524),
('catalog-107', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-525.jpg', 525),
('catalog-107', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-526.jpg', 526),
('catalog-107', '{"color":"бетон сiрий","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-527.jpg', 527),
('catalog-107', '{"color":"бетон сiрий","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-528.jpg', 528),
('catalog-107', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-529.jpg', 529),
('catalog-107', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-530.jpg', 530),
('catalog-107', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-531.jpg', 531),
('catalog-107', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-532.jpg', 532),
('catalog-107', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-815.jpg', 815),
('catalog-107', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-816.jpg', 816),
('catalog-107', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-817.jpg', 817),
('catalog-107', '{"color":"ясен білий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-818.jpg', 818),
('catalog-107', '{"color":"ясен білий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-819.jpg', 819),
('catalog-107', '{"color":"дуб ciрий","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-820.jpg', 820),
('catalog-107', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-821.jpg', 821),
('catalog-107', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-822.jpg', 822),
('catalog-107', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-823.jpg', 823),
('catalog-107', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-824.jpg', 824),
('catalog-107', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-825.jpg', 825),
('catalog-107', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-826.jpg', 826),
('catalog-107', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-827.jpg', 827),
('catalog-107', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-828.jpg', 828),
('catalog-107', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-829.jpg', 829),
('catalog-107', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-830.jpg', 830),
('catalog-107', '{"color":"бетон сiрий","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-831.jpg', 831),
('catalog-107', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-832.jpg', 832),
('catalog-107', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-833.jpg', 833),
('catalog-107', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-2346.jpg', 2346),
('catalog-107', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-2347.jpg', 2347),
('catalog-107', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-2348.jpg', 2348),
('catalog-107', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-2349.jpg', 2349),
('catalog-107', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-2350.jpg', 2350),
('catalog-107', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-2351.jpg', 2351),
('catalog-107', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-3345.jpg', 3345),
('catalog-107', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-3346.jpg', 3346),
('catalog-107', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-3347.jpg', 3347),
('catalog-107', '{"color":"ясен білий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-3348.jpg', 3348),
('catalog-107', '{"color":"ясен білий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-3349.jpg', 3349),
('catalog-107', '{"color":"ясен білий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-3350.jpg', 3350),
('catalog-107', '{"color":"дуб ciрий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-3351.jpg', 3351),
('catalog-107', '{"color":"дуб ciрий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-3352.jpg', 3352),
('catalog-107', '{"color":"дуб ciрий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-3353.jpg', 3353),
('catalog-107', '{"color":"дуб кремовий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-3354.jpg', 3354),
('catalog-107', '{"color":"дуб кремовий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-3355.jpg', 3355),
('catalog-107', '{"color":"дуб кремовий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-3356.jpg', 3356),
('catalog-107', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-3357.jpg', 3357),
('catalog-107', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-3358.jpg', 3358),
('catalog-107', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-3359.jpg', 3359),
('catalog-107', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-3360.jpg', 3360),
('catalog-107', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-3361.jpg', 3361),
('catalog-107', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-3362.jpg', 3362),
('catalog-107', '{"color":"бетон сiрий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-3363.jpg', 3363),
('catalog-107', '{"color":"бетон сiрий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-3364.jpg', 3364),
('catalog-107', '{"color":"бетон сiрий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-3365.jpg', 3365),
('catalog-107', '{"color":"сірий матовий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-3366.jpg', 3366),
('catalog-107', '{"color":"сірий матовий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-3367.jpg', 3367),
('catalog-107', '{"color":"сірий матовий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-3368.jpg', 3368),
('catalog-107', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-4564.jpg', 4564),
('catalog-107', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-4565.jpg', 4565),
('catalog-107', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-4566.jpg', 4566),
('catalog-107', '{"color":"ясен білий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-4567.jpg', 4567),
('catalog-107', '{"color":"ясен білий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-4568.jpg', 4568),
('catalog-107', '{"color":"ясен білий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-4569.jpg', 4569),
('catalog-107', '{"color":"дуб ciрий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-4570.jpg', 4570),
('catalog-107', '{"color":"дуб ciрий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-4571.jpg', 4571),
('catalog-107', '{"color":"дуб ciрий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-4572.jpg', 4572),
('catalog-107', '{"color":"дуб кремовий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-4573.jpg', 4573),
('catalog-107', '{"color":"дуб кремовий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-4574.jpg', 4574),
('catalog-107', '{"color":"дуб кремовий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-4575.jpg', 4575),
('catalog-107', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-4576.jpg', 4576),
('catalog-107', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-4577.jpg', 4577),
('catalog-107', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-4578.jpg', 4578),
('catalog-107', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-4579.jpg', 4579),
('catalog-107', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-4580.jpg', 4580),
('catalog-107', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-4581.jpg', 4581),
('catalog-107', '{"color":"бетон сiрий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-4582.jpg', 4582),
('catalog-107', '{"color":"бетон сiрий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-4583.jpg', 4583),
('catalog-107', '{"color":"бетон сiрий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-4584.jpg', 4584),
('catalog-107', '{"color":"сірий матовий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-4585.jpg', 4585),
('catalog-107', '{"color":"сірий матовий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-4586.jpg', 4586),
('catalog-107', '{"color":"сірий матовий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-4587.jpg', 4587),
('catalog-107', '{"color":"сірий матовий","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-4765.jpg', 4765),
('catalog-107', '{"color":"сірий матовий","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-4766.jpg', 4766),
('catalog-107', '{"color":"сірий матовий","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-4767.jpg', 4767),
('catalog-107', '{"color":"кремовий матовий","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-5164.jpg', 5164),
('catalog-107', '{"color":"кремовий матовий","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-5165.jpg', 5165),
('catalog-107', '{"color":"кремовий матовий","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-5166.jpg', 5166),
('catalog-107', '{"color":"кремовий матовий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-5167.jpg', 5167),
('catalog-107', '{"color":"кремовий матовий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-5168.jpg', 5168),
('catalog-107', '{"color":"кремовий матовий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-5169.jpg', 5169),
('catalog-107', '{"color":"кремовий матовий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-5170.jpg', 5170),
('catalog-107', '{"color":"кремовий матовий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-5171.jpg', 5171),
('catalog-107', '{"color":"кремовий матовий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-5172.jpg', 5172),
('catalog-107', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-5173.jpg', 5173),
('catalog-107', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-5174.jpg', 5174),
('catalog-107', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-5175.jpg', 5175),
('catalog-107', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-107-5176.jpg', 5176),
('catalog-107', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-107-5177.jpg', 5177),
('catalog-107', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-107-5178.jpg', 5178)
on conflict (product_slug, selections) do update
set image_path = excluded.image_path, sort_order = excluded.sort_order, is_active = true;
