-- Фото з офіційної сторінки Papa Carlo: https://papa-carlo.com.ua/ua/dverne-polotno-st-02/
-- Завантажте вміст папки tmp\papa-carlo-variants\catalog-112 у bucket catalog-images, зберігши шлях variants/papa-carlo/catalog-112.

insert into public.product_variants (product_slug, selections, image_path, sort_order)
values
('catalog-112', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-112/1189.jpg', 1189),
('catalog-112', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-112/1190.jpg', 1190),
('catalog-112', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-112/1191.jpg', 1191),
('catalog-112', '{"color":"ясен білий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-112/1192.jpg', 1192),
('catalog-112', '{"color":"ясен білий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-112/1193.jpg', 1193),
('catalog-112', '{"color":"дуб ciрий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-112/1194.jpg', 1194),
('catalog-112', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-112/1195.jpg', 1195),
('catalog-112', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-112/1196.jpg', 1196),
('catalog-112', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-112/1197.jpg', 1197),
('catalog-112', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-112/1198.jpg', 1198),
('catalog-112', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-112/1199.jpg', 1199),
('catalog-112', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-112/1200.jpg', 1200),
('catalog-112', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-112/1201.jpg', 1201),
('catalog-112', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-112/1202.jpg', 1202),
('catalog-112', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-112/1203.jpg', 1203),
('catalog-112', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-112/1204.jpg', 1204),
('catalog-112', '{"color":"бетон сiрий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-112/1205.jpg', 1205),
('catalog-112', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-112/1206.jpg', 1206),
('catalog-112', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-112/1207.jpg', 1207),
('catalog-112', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-112/2222.jpg', 2222),
('catalog-112', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-112/2223.jpg', 2223),
('catalog-112', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-112/3858.jpg', 3858),
('catalog-112', '{"color":"ясен білий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-112/3859.jpg', 3859),
('catalog-112', '{"color":"дуб ciрий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-112/3860.jpg', 3860),
('catalog-112', '{"color":"дуб кремовий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-112/3861.jpg', 3861),
('catalog-112', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-112/3862.jpg', 3862),
('catalog-112', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-112/3863.jpg', 3863),
('catalog-112', '{"color":"бетон сiрий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-112/3864.jpg', 3864),
('catalog-112', '{"color":"сірий матовий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-112/3865.jpg', 3865),
('catalog-112', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-112/4106.jpg', 4106),
('catalog-112', '{"color":"ясен білий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-112/4107.jpg', 4107),
('catalog-112', '{"color":"дуб ciрий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-112/4108.jpg', 4108),
('catalog-112', '{"color":"дуб кремовий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-112/4109.jpg', 4109),
('catalog-112', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-112/4110.jpg', 4110),
('catalog-112', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-112/4111.jpg', 4111),
('catalog-112', '{"color":"бетон сiрий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-112/4112.jpg', 4112),
('catalog-112', '{"color":"сірий матовий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-112/4113.jpg', 4113),
('catalog-112', '{"color":"сірий матовий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-112/4678.jpg', 4678),
('catalog-112', '{"color":"кремовий матовий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-112/4854.jpg', 4854),
('catalog-112', '{"color":"кремовий матовий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-112/4855.jpg', 4855),
('catalog-112', '{"color":"кремовий матовий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-112/4856.jpg', 4856),
('catalog-112', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-112/4857.jpg', 4857),
('catalog-112', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-112/4858.jpg', 4858)
on conflict (product_slug, selections) do update
set image_path = excluded.image_path, sort_order = excluded.sort_order, is_active = true;
