-- Фото з офіційної сторінки Papa Carlo: https://papa-carlo.com.ua/ua/dverne-polotno-pl-22/
-- Завантажте вміст папки tmp\papa-carlo-variants\catalog-108 у корінь bucket catalog-images.

insert into public.product_variants (product_slug, selections, image_path, sort_order)
values
('catalog-108', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-3052.jpg', 3052),
('catalog-108', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-3053.jpg', 3053),
('catalog-108', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-585.jpg', 585),
('catalog-108', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-586.jpg', 586),
('catalog-108', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-587.jpg', 587),
('catalog-108', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-588.jpg', 588),
('catalog-108', '{"color":"ясен білий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-589.jpg', 589),
('catalog-108', '{"color":"ясен білий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-590.jpg', 590),
('catalog-108', '{"color":"ясен білий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-591.jpg', 591),
('catalog-108', '{"color":"ясен білий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-592.jpg', 592),
('catalog-108', '{"color":"дуб ciрий","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-3055.jpg', 3055),
('catalog-108', '{"color":"дуб ciрий","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-3056.jpg', 3056),
('catalog-108', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-597.jpg', 597),
('catalog-108', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-598.jpg', 598),
('catalog-108', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-599.jpg', 599),
('catalog-108', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-600.jpg', 600),
('catalog-108', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-601.jpg', 601),
('catalog-108', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-602.jpg', 602),
('catalog-108', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-603.jpg', 603),
('catalog-108', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-604.jpg', 604),
('catalog-108', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-3058.jpg', 3058),
('catalog-108', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-3059.jpg', 3059),
('catalog-108', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-609.jpg', 609),
('catalog-108', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-610.jpg', 610),
('catalog-108', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-611.jpg', 611),
('catalog-108', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-612.jpg', 612),
('catalog-108', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-3061.jpg', 3061),
('catalog-108', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-3062.jpg', 3062),
('catalog-108', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-617.jpg', 617),
('catalog-108', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-618.jpg', 618),
('catalog-108', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-619.jpg', 619),
('catalog-108', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-620.jpg', 620),
('catalog-108', '{"color":"бетон сiрий","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-3064.jpg', 3064),
('catalog-108', '{"color":"бетон сiрий","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-3065.jpg', 3065),
('catalog-108', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-625.jpg', 625),
('catalog-108', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-626.jpg', 626),
('catalog-108', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-627.jpg', 627),
('catalog-108', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-628.jpg', 628),
('catalog-108', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-3054.jpg', 3054),
('catalog-108', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-836.jpg', 836),
('catalog-108', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-837.jpg', 837),
('catalog-108', '{"color":"ясен білий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-838.jpg', 838),
('catalog-108', '{"color":"ясен білий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-839.jpg', 839),
('catalog-108', '{"color":"дуб ciрий","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-3057.jpg', 3057),
('catalog-108', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-842.jpg', 842),
('catalog-108', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-843.jpg', 843),
('catalog-108', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-844.jpg', 844),
('catalog-108', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-845.jpg', 845),
('catalog-108', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-3060.jpg', 3060),
('catalog-108', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-848.jpg', 848),
('catalog-108', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-849.jpg', 849),
('catalog-108', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-3063.jpg', 3063),
('catalog-108', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-852.jpg', 852),
('catalog-108', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-853.jpg', 853),
('catalog-108', '{"color":"бетон сiрий","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-3066.jpg', 3066),
('catalog-108', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-856.jpg', 856),
('catalog-108', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-857.jpg', 857),
('catalog-108', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-2356.jpg', 2356),
('catalog-108', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-2357.jpg', 2357),
('catalog-108', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-2358.jpg', 2358),
('catalog-108', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-2359.jpg', 2359),
('catalog-108', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-2360.jpg', 2360),
('catalog-108', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-2361.jpg', 2361),
('catalog-108', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-3708.jpg', 3708),
('catalog-108', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-3711.jpg', 3711),
('catalog-108', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-3714.jpg', 3714),
('catalog-108', '{"color":"ясен білий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-3717.jpg', 3717),
('catalog-108', '{"color":"ясен білий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-3720.jpg', 3720),
('catalog-108', '{"color":"ясен білий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-3723.jpg', 3723),
('catalog-108', '{"color":"дуб ciрий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-3726.jpg', 3726),
('catalog-108', '{"color":"дуб ciрий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-3729.jpg', 3729),
('catalog-108', '{"color":"дуб ciрий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-3732.jpg', 3732),
('catalog-108', '{"color":"дуб кремовий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-3735.jpg', 3735),
('catalog-108', '{"color":"дуб кремовий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-3738.jpg', 3738),
('catalog-108', '{"color":"дуб кремовий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-3741.jpg', 3741),
('catalog-108', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-3744.jpg', 3744),
('catalog-108', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-3747.jpg', 3747),
('catalog-108', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-3750.jpg', 3750),
('catalog-108', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-3753.jpg', 3753),
('catalog-108', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-3756.jpg', 3756),
('catalog-108', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-3759.jpg', 3759),
('catalog-108', '{"color":"бетон сiрий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-3762.jpg', 3762),
('catalog-108', '{"color":"бетон сiрий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-3765.jpg', 3765),
('catalog-108', '{"color":"бетон сiрий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-3768.jpg', 3768),
('catalog-108', '{"color":"сірий матовий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-3771.jpg', 3771),
('catalog-108', '{"color":"сірий матовий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-3774.jpg', 3774),
('catalog-108', '{"color":"сірий матовий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-3777.jpg', 3777),
('catalog-108', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-4605.jpg', 4605),
('catalog-108', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-4606.jpg', 4606),
('catalog-108', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-4607.jpg', 4607),
('catalog-108', '{"color":"ясен білий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-4608.jpg', 4608),
('catalog-108', '{"color":"ясен білий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-4609.jpg', 4609),
('catalog-108', '{"color":"ясен білий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-4610.jpg', 4610),
('catalog-108', '{"color":"дуб ciрий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-4611.jpg', 4611),
('catalog-108', '{"color":"дуб ciрий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-4612.jpg', 4612),
('catalog-108', '{"color":"дуб ciрий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-4613.jpg', 4613),
('catalog-108', '{"color":"дуб кремовий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-4614.jpg', 4614),
('catalog-108', '{"color":"дуб кремовий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-4615.jpg', 4615),
('catalog-108', '{"color":"дуб кремовий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-4616.jpg', 4616),
('catalog-108', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-4617.jpg', 4617),
('catalog-108', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-4618.jpg', 4618),
('catalog-108', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-4619.jpg', 4619),
('catalog-108', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-4620.jpg', 4620),
('catalog-108', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-4621.jpg', 4621),
('catalog-108', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-4622.jpg', 4622),
('catalog-108', '{"color":"бетон сiрий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-4623.jpg', 4623),
('catalog-108', '{"color":"бетон сiрий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-4624.jpg', 4624),
('catalog-108', '{"color":"бетон сiрий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-4625.jpg', 4625),
('catalog-108', '{"color":"сірий матовий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-4626.jpg', 4626),
('catalog-108', '{"color":"сірий матовий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-4627.jpg', 4627),
('catalog-108', '{"color":"сірий матовий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-4628.jpg', 4628),
('catalog-108', '{"color":"сірий матовий","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-4780.jpg', 4780),
('catalog-108', '{"color":"сірий матовий","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-4781.jpg', 4781),
('catalog-108', '{"color":"сірий матовий","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-4782.jpg', 4782),
('catalog-108', '{"color":"кремовий матовий","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-5257.jpg', 5257),
('catalog-108', '{"color":"кремовий матовий","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-5258.jpg', 5258),
('catalog-108', '{"color":"кремовий матовий","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-5259.jpg', 5259),
('catalog-108', '{"color":"кремовий матовий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-5260.jpg', 5260),
('catalog-108', '{"color":"кремовий матовий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-5261.jpg', 5261),
('catalog-108', '{"color":"кремовий матовий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-5262.jpg', 5262),
('catalog-108', '{"color":"кремовий матовий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-5269.jpg', 5269),
('catalog-108', '{"color":"кремовий матовий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-5270.jpg', 5270),
('catalog-108', '{"color":"кремовий матовий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-5271.jpg', 5271),
('catalog-108', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-5272.jpg', 5272),
('catalog-108', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-5273.jpg', 5273),
('catalog-108', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-5274.jpg', 5274),
('catalog-108', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-108-5275.jpg', 5275),
('catalog-108', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-108-5276.jpg', 5276),
('catalog-108', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-108-5277.jpg', 5277)
on conflict (product_slug, selections) do update
set image_path = excluded.image_path, sort_order = excluded.sort_order, is_active = true;
