-- Фото з офіційної сторінки Papa Carlo: https://papa-carlo.com.ua/ua/dverne-polotno-pl-01/
-- Завантажте вміст папки tmp\papa-carlo-variants\catalog-102 у корінь bucket catalog-images.

insert into public.product_variants (product_slug, selections, image_path, sort_order)
values
('catalog-102', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'papa-carlo-catalog-102-26.jpg', 26),
('catalog-102', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'papa-carlo-catalog-102-27.jpg', 27),
('catalog-102', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'papa-carlo-catalog-102-28.jpg', 28),
('catalog-102', '{"color":"ясен білий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'papa-carlo-catalog-102-29.jpg', 29),
('catalog-102', '{"color":"ясен білий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'papa-carlo-catalog-102-30.jpg', 30),
('catalog-102', '{"color":"дуб ciрий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'papa-carlo-catalog-102-31.jpg', 31),
('catalog-102', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'papa-carlo-catalog-102-32.jpg', 32),
('catalog-102', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'papa-carlo-catalog-102-33.jpg', 33),
('catalog-102', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'papa-carlo-catalog-102-34.jpg', 34),
('catalog-102', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'papa-carlo-catalog-102-35.jpg', 35),
('catalog-102', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'papa-carlo-catalog-102-36.jpg', 36),
('catalog-102', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'papa-carlo-catalog-102-37.jpg', 37),
('catalog-102', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'papa-carlo-catalog-102-38.jpg', 38),
('catalog-102', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'papa-carlo-catalog-102-39.jpg', 39),
('catalog-102', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'papa-carlo-catalog-102-40.jpg', 40),
('catalog-102', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'papa-carlo-catalog-102-41.jpg', 41),
('catalog-102', '{"color":"бетон сiрий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'papa-carlo-catalog-102-42.jpg', 42),
('catalog-102', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'papa-carlo-catalog-102-43.jpg', 43),
('catalog-102', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'papa-carlo-catalog-102-44.jpg', 44),
('catalog-102', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'papa-carlo-catalog-102-2284.jpg', 2284),
('catalog-102', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'papa-carlo-catalog-102-2285.jpg', 2285),
('catalog-102', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC чорна"}'::jsonb, 'papa-carlo-catalog-102-3097.jpg', 3097),
('catalog-102', '{"color":"ясен білий","edge":"торець кромка ABC чорна"}'::jsonb, 'papa-carlo-catalog-102-3098.jpg', 3098),
('catalog-102', '{"color":"дуб ciрий","edge":"торець кромка ABC чорна"}'::jsonb, 'papa-carlo-catalog-102-3099.jpg', 3099),
('catalog-102', '{"color":"дуб кремовий","edge":"торець кромка ABC чорна"}'::jsonb, 'papa-carlo-catalog-102-3100.jpg', 3100),
('catalog-102', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC чорна"}'::jsonb, 'papa-carlo-catalog-102-3101.jpg', 3101),
('catalog-102', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC чорна"}'::jsonb, 'papa-carlo-catalog-102-3102.jpg', 3102),
('catalog-102', '{"color":"бетон сiрий","edge":"торець кромка ABC чорна"}'::jsonb, 'papa-carlo-catalog-102-3103.jpg', 3103),
('catalog-102', '{"color":"сірий матовий","edge":"торець кромка ABC чорна"}'::jsonb, 'papa-carlo-catalog-102-3104.jpg', 3104),
('catalog-102', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC золота"}'::jsonb, 'papa-carlo-catalog-102-4338.jpg', 4338),
('catalog-102', '{"color":"ясен білий","edge":"торець кромка ABC золота"}'::jsonb, 'papa-carlo-catalog-102-4339.jpg', 4339),
('catalog-102', '{"color":"дуб ciрий","edge":"торець кромка ABC золота"}'::jsonb, 'papa-carlo-catalog-102-4340.jpg', 4340),
('catalog-102', '{"color":"дуб кремовий","edge":"торець кромка ABC золота"}'::jsonb, 'papa-carlo-catalog-102-4341.jpg', 4341),
('catalog-102', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC золота"}'::jsonb, 'papa-carlo-catalog-102-4342.jpg', 4342),
('catalog-102', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC золота"}'::jsonb, 'papa-carlo-catalog-102-4343.jpg', 4343),
('catalog-102', '{"color":"бетон сiрий","edge":"торець кромка ABC золота"}'::jsonb, 'papa-carlo-catalog-102-4344.jpg', 4344),
('catalog-102', '{"color":"сірий матовий","edge":"торець кромка ABC золота"}'::jsonb, 'papa-carlo-catalog-102-4345.jpg', 4345),
('catalog-102', '{"color":"сірий матовий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'papa-carlo-catalog-102-4707.jpg', 4707),
('catalog-102', '{"color":"кремовий матовий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'papa-carlo-catalog-102-5012.jpg', 5012),
('catalog-102', '{"color":"кремовий матовий","edge":"торець кромка ABC золота"}'::jsonb, 'papa-carlo-catalog-102-5013.jpg', 5013),
('catalog-102', '{"color":"кремовий матовий","edge":"торець кромка ABC чорна"}'::jsonb, 'papa-carlo-catalog-102-5014.jpg', 5014),
('catalog-102', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'papa-carlo-catalog-102-5015.jpg', 5015),
('catalog-102', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'papa-carlo-catalog-102-5016.jpg', 5016)
on conflict (product_slug, selections) do update
set image_path = excluded.image_path, sort_order = excluded.sort_order, is_active = true;
