-- Фото з офіційної сторінки Papa Carlo: https://papa-carlo.com.ua/ua/dverne-polotno-pl-06/
-- Завантажте вміст папки tmp\papa-carlo-variants\catalog-105 у корінь bucket catalog-images.

insert into public.product_variants (product_slug, selections, image_path, sort_order)
values
('catalog-105', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-179.jpg', 179),
('catalog-105', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-180.jpg', 180),
('catalog-105', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-181.jpg', 181),
('catalog-105', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-182.jpg', 182),
('catalog-105', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-183.jpg', 183),
('catalog-105', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-184.jpg', 184),
('catalog-105', '{"color":"ясен білий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-185.jpg', 185),
('catalog-105', '{"color":"ясен білий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-186.jpg', 186),
('catalog-105', '{"color":"ясен білий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-187.jpg', 187),
('catalog-105', '{"color":"ясен білий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-188.jpg', 188),
('catalog-105', '{"color":"дуб ciрий","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-189.jpg', 189),
('catalog-105', '{"color":"дуб ciрий","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-190.jpg', 190),
('catalog-105', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-191.jpg', 191),
('catalog-105', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-192.jpg', 192),
('catalog-105', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-193.jpg', 193),
('catalog-105', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-194.jpg', 194),
('catalog-105', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-195.jpg', 195),
('catalog-105', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-196.jpg', 196),
('catalog-105', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-197.jpg', 197),
('catalog-105', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-198.jpg', 198),
('catalog-105', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-199.jpg', 199),
('catalog-105', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-200.jpg', 200),
('catalog-105', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-201.jpg', 201),
('catalog-105', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-202.jpg', 202),
('catalog-105', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-203.jpg', 203),
('catalog-105', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-204.jpg', 204),
('catalog-105', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-205.jpg', 205),
('catalog-105', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-206.jpg', 206),
('catalog-105', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-207.jpg', 207),
('catalog-105', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-208.jpg', 208),
('catalog-105', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-209.jpg', 209),
('catalog-105', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-210.jpg', 210),
('catalog-105', '{"color":"бетон сiрий","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-211.jpg', 211),
('catalog-105', '{"color":"бетон сiрий","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-212.jpg', 212),
('catalog-105', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-213.jpg', 213),
('catalog-105', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-214.jpg', 214),
('catalog-105', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-215.jpg', 215),
('catalog-105', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-216.jpg', 216),
('catalog-105', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-681.jpg', 681),
('catalog-105', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-682.jpg', 682),
('catalog-105', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-683.jpg', 683),
('catalog-105', '{"color":"ясен білий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-684.jpg', 684),
('catalog-105', '{"color":"ясен білий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-685.jpg', 685),
('catalog-105', '{"color":"дуб ciрий","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-686.jpg', 686),
('catalog-105', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-687.jpg', 687),
('catalog-105', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-688.jpg', 688),
('catalog-105', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-689.jpg', 689),
('catalog-105', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-690.jpg', 690),
('catalog-105', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-691.jpg', 691),
('catalog-105', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-692.jpg', 692),
('catalog-105', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-693.jpg', 693),
('catalog-105', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-694.jpg', 694),
('catalog-105', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-695.jpg', 695),
('catalog-105', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-696.jpg', 696),
('catalog-105', '{"color":"бетон сiрий","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-697.jpg', 697),
('catalog-105', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-698.jpg', 698),
('catalog-105', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-699.jpg', 699),
('catalog-105', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-2306.jpg', 2306),
('catalog-105', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-2307.jpg', 2307),
('catalog-105', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-2308.jpg', 2308),
('catalog-105', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-2309.jpg', 2309),
('catalog-105', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-2310.jpg', 2310),
('catalog-105', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-2311.jpg', 2311),
('catalog-105', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-3177.jpg', 3177),
('catalog-105', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-3178.jpg', 3178),
('catalog-105', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-3179.jpg', 3179),
('catalog-105', '{"color":"ясен білий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-3180.jpg', 3180),
('catalog-105', '{"color":"ясен білий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-3181.jpg', 3181),
('catalog-105', '{"color":"ясен білий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-3182.jpg', 3182),
('catalog-105', '{"color":"дуб ciрий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-3183.jpg', 3183),
('catalog-105', '{"color":"дуб ciрий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-3184.jpg', 3184),
('catalog-105', '{"color":"дуб ciрий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-3185.jpg', 3185),
('catalog-105', '{"color":"дуб кремовий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-3186.jpg', 3186),
('catalog-105', '{"color":"дуб кремовий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-3187.jpg', 3187),
('catalog-105', '{"color":"дуб кремовий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-3188.jpg', 3188),
('catalog-105', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-3189.jpg', 3189),
('catalog-105', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-3190.jpg', 3190),
('catalog-105', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-3191.jpg', 3191),
('catalog-105', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-3192.jpg', 3192),
('catalog-105', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-3193.jpg', 3193),
('catalog-105', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-3194.jpg', 3194),
('catalog-105', '{"color":"бетон сiрий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-3195.jpg', 3195),
('catalog-105', '{"color":"бетон сiрий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-3196.jpg', 3196),
('catalog-105', '{"color":"бетон сiрий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-3197.jpg', 3197),
('catalog-105', '{"color":"сірий матовий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-3198.jpg', 3198),
('catalog-105', '{"color":"сірий матовий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-3199.jpg', 3199),
('catalog-105', '{"color":"сірий матовий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-3200.jpg', 3200),
('catalog-105', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-4402.jpg', 4402),
('catalog-105', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-4403.jpg', 4403),
('catalog-105', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-4404.jpg', 4404),
('catalog-105', '{"color":"ясен білий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-4405.jpg', 4405),
('catalog-105', '{"color":"ясен білий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-4406.jpg', 4406),
('catalog-105', '{"color":"ясен білий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-4407.jpg', 4407),
('catalog-105', '{"color":"дуб ciрий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-4408.jpg', 4408),
('catalog-105', '{"color":"дуб ciрий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-4409.jpg', 4409),
('catalog-105', '{"color":"дуб ciрий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-4410.jpg', 4410),
('catalog-105', '{"color":"дуб кремовий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-4411.jpg', 4411),
('catalog-105', '{"color":"дуб кремовий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-4412.jpg', 4412),
('catalog-105', '{"color":"дуб кремовий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-4413.jpg', 4413),
('catalog-105', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-4414.jpg', 4414),
('catalog-105', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-4415.jpg', 4415),
('catalog-105', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-4416.jpg', 4416),
('catalog-105', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-4417.jpg', 4417),
('catalog-105', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-4418.jpg', 4418),
('catalog-105', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-4419.jpg', 4419),
('catalog-105', '{"color":"бетон сiрий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-4420.jpg', 4420),
('catalog-105', '{"color":"бетон сiрий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-4421.jpg', 4421),
('catalog-105', '{"color":"бетон сiрий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-4422.jpg', 4422),
('catalog-105', '{"color":"сірий матовий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-4423.jpg', 4423),
('catalog-105', '{"color":"сірий матовий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-4424.jpg', 4424),
('catalog-105', '{"color":"сірий матовий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-4425.jpg', 4425),
('catalog-105', '{"color":"сірий матовий","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-4717.jpg', 4717),
('catalog-105', '{"color":"сірий матовий","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-4718.jpg', 4718),
('catalog-105', '{"color":"сірий матовий","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-4719.jpg', 4719),
('catalog-105', '{"color":"кремовий матовий","edge":"торець кромка ABC у колір полотна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-5062.jpg', 5062),
('catalog-105', '{"color":"кремовий матовий","edge":"торець кромка ABC у колір полотна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-5063.jpg', 5063),
('catalog-105', '{"color":"кремовий матовий","edge":"торець кромка ABC у колір полотна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-5064.jpg', 5064),
('catalog-105', '{"color":"кремовий матовий","edge":"торець кромка ABC золота","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-5065.jpg', 5065),
('catalog-105', '{"color":"кремовий матовий","edge":"торець кромка ABC золота","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-5066.jpg', 5066),
('catalog-105', '{"color":"кремовий матовий","edge":"торець кромка ABC золота","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-5067.jpg', 5067),
('catalog-105', '{"color":"кремовий матовий","edge":"торець кромка ABC чорна","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-5068.jpg', 5068),
('catalog-105', '{"color":"кремовий матовий","edge":"торець кромка ABC чорна","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-5069.jpg', 5069),
('catalog-105', '{"color":"кремовий матовий","edge":"торець кромка ABC чорна","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-5070.jpg', 5070),
('catalog-105', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-5071.jpg', 5071),
('catalog-105', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-5072.jpg', 5072),
('catalog-105', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй сiрий","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-5073.jpg', 5073),
('catalog-105', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй чорний","glass":"скло бiле"}'::jsonb, 'papa-carlo-catalog-105-5074.jpg', 5074),
('catalog-105', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй чорний","glass":"скло чорне"}'::jsonb, 'papa-carlo-catalog-105-5075.jpg', 5075),
('catalog-105', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй чорний","glass":"дзеркало"}'::jsonb, 'papa-carlo-catalog-105-5076.jpg', 5076)
on conflict (product_slug, selections) do update
set image_path = excluded.image_path, sort_order = excluded.sort_order, is_active = true;
