-- Фото з офіційної сторінки Papa Carlo: https://papa-carlo.com.ua/ua/dverne-polotno-pl-02/
-- Завантажте вміст папки tmp\papa-carlo-variants\catalog-103 у корінь bucket catalog-images.

insert into public.product_variants (product_slug, selections, image_path, sort_order)
values
('catalog-103', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'papa-carlo-catalog-103-2967.jpg', 2967),
('catalog-103', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'papa-carlo-catalog-103-53.jpg', 53),
('catalog-103', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'papa-carlo-catalog-103-54.jpg', 54),
('catalog-103', '{"color":"ясен білий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'papa-carlo-catalog-103-55.jpg', 55),
('catalog-103', '{"color":"ясен білий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'papa-carlo-catalog-103-56.jpg', 56),
('catalog-103', '{"color":"дуб ciрий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'papa-carlo-catalog-103-2968.jpg', 2968),
('catalog-103', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'papa-carlo-catalog-103-59.jpg', 59),
('catalog-103', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'papa-carlo-catalog-103-60.jpg', 60),
('catalog-103', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'papa-carlo-catalog-103-61.jpg', 61),
('catalog-103', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'papa-carlo-catalog-103-62.jpg', 62),
('catalog-103', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'papa-carlo-catalog-103-2969.jpg', 2969),
('catalog-103', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'papa-carlo-catalog-103-65.jpg', 65),
('catalog-103', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'papa-carlo-catalog-103-66.jpg', 66),
('catalog-103', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'papa-carlo-catalog-103-2970.jpg', 2970),
('catalog-103', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'papa-carlo-catalog-103-69.jpg', 69),
('catalog-103', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'papa-carlo-catalog-103-70.jpg', 70),
('catalog-103', '{"color":"бетон сiрий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'papa-carlo-catalog-103-2971.jpg', 2971),
('catalog-103', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'papa-carlo-catalog-103-73.jpg', 73),
('catalog-103', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'papa-carlo-catalog-103-74.jpg', 74),
('catalog-103', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'papa-carlo-catalog-103-2286.jpg', 2286),
('catalog-103', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'papa-carlo-catalog-103-2287.jpg', 2287),
('catalog-103', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC чорна"}'::jsonb, 'papa-carlo-catalog-103-3107.jpg', 3107),
('catalog-103', '{"color":"ясен білий","edge":"торець кромка ABC чорна"}'::jsonb, 'papa-carlo-catalog-103-3110.jpg', 3110),
('catalog-103', '{"color":"дуб ciрий","edge":"торець кромка ABC чорна"}'::jsonb, 'papa-carlo-catalog-103-3113.jpg', 3113),
('catalog-103', '{"color":"дуб кремовий","edge":"торець кромка ABC чорна"}'::jsonb, 'papa-carlo-catalog-103-3116.jpg', 3116),
('catalog-103', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC чорна"}'::jsonb, 'papa-carlo-catalog-103-3119.jpg', 3119),
('catalog-103', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC чорна"}'::jsonb, 'papa-carlo-catalog-103-3122.jpg', 3122),
('catalog-103', '{"color":"бетон сiрий","edge":"торець кромка ABC чорна"}'::jsonb, 'papa-carlo-catalog-103-3125.jpg', 3125),
('catalog-103', '{"color":"сірий матовий","edge":"торець кромка ABC чорна"}'::jsonb, 'papa-carlo-catalog-103-3128.jpg', 3128),
('catalog-103', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC золота"}'::jsonb, 'papa-carlo-catalog-103-4346.jpg', 4346),
('catalog-103', '{"color":"ясен білий","edge":"торець кромка ABC золота"}'::jsonb, 'papa-carlo-catalog-103-4347.jpg', 4347),
('catalog-103', '{"color":"дуб ciрий","edge":"торець кромка ABC золота"}'::jsonb, 'papa-carlo-catalog-103-4348.jpg', 4348),
('catalog-103', '{"color":"дуб кремовий","edge":"торець кромка ABC золота"}'::jsonb, 'papa-carlo-catalog-103-4349.jpg', 4349),
('catalog-103', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC золота"}'::jsonb, 'papa-carlo-catalog-103-4350.jpg', 4350),
('catalog-103', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC золота"}'::jsonb, 'papa-carlo-catalog-103-4351.jpg', 4351),
('catalog-103', '{"color":"бетон сiрий","edge":"торець кромка ABC золота"}'::jsonb, 'papa-carlo-catalog-103-4352.jpg', 4352),
('catalog-103', '{"color":"сірий матовий","edge":"торець кромка ABC золота"}'::jsonb, 'papa-carlo-catalog-103-4353.jpg', 4353),
('catalog-103', '{"color":"сірий матовий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'papa-carlo-catalog-103-4710.jpg', 4710),
('catalog-103', '{"color":"кремовий матовий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'papa-carlo-catalog-103-5019.jpg', 5019),
('catalog-103', '{"color":"кремовий матовий","edge":"торець кромка ABC золота"}'::jsonb, 'papa-carlo-catalog-103-5020.jpg', 5020),
('catalog-103', '{"color":"кремовий матовий","edge":"торець кромка ABC чорна"}'::jsonb, 'papa-carlo-catalog-103-5023.jpg', 5023),
('catalog-103', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'papa-carlo-catalog-103-5024.jpg', 5024),
('catalog-103', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'papa-carlo-catalog-103-5025.jpg', 5025)
on conflict (product_slug, selections) do update
set image_path = excluded.image_path, sort_order = excluded.sort_order, is_active = true;
