-- Фото з офіційної сторінки Papa Carlo: https://papa-carlo.com.ua/ua/dverne-polotno-st-01/
-- Завантажте вміст папки tmp\papa-carlo-variants\catalog-111 у bucket catalog-images, зберігши шлях variants/papa-carlo/catalog-111.

insert into public.product_variants (product_slug, selections, image_path, sort_order)
values
('catalog-111', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-111/1170.jpg', 1170),
('catalog-111', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-111/1171.jpg', 1171),
('catalog-111', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-111/1172.jpg', 1172),
('catalog-111', '{"color":"ясен білий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-111/1173.jpg', 1173),
('catalog-111', '{"color":"ясен білий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-111/1174.jpg', 1174),
('catalog-111', '{"color":"дуб ciрий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-111/1175.jpg', 1175),
('catalog-111', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-111/1176.jpg', 1176),
('catalog-111', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-111/1177.jpg', 1177),
('catalog-111', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-111/1178.jpg', 1178),
('catalog-111', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-111/1179.jpg', 1179),
('catalog-111', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-111/1180.jpg', 1180),
('catalog-111', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-111/1181.jpg', 1181),
('catalog-111', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-111/1182.jpg', 1182),
('catalog-111', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-111/1183.jpg', 1183),
('catalog-111', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-111/1184.jpg', 1184),
('catalog-111', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-111/1185.jpg', 1185),
('catalog-111', '{"color":"бетон сiрий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-111/1186.jpg', 1186),
('catalog-111', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-111/1187.jpg', 1187),
('catalog-111', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-111/1188.jpg', 1188),
('catalog-111', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-111/2220.jpg', 2220),
('catalog-111', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-111/2221.jpg', 2221),
('catalog-111', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-111/3850.jpg', 3850),
('catalog-111', '{"color":"ясен білий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-111/3851.jpg', 3851),
('catalog-111', '{"color":"дуб ciрий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-111/3852.jpg', 3852),
('catalog-111', '{"color":"дуб кремовий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-111/3853.jpg', 3853),
('catalog-111', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-111/3854.jpg', 3854),
('catalog-111', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-111/3855.jpg', 3855),
('catalog-111', '{"color":"бетон сiрий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-111/3856.jpg', 3856),
('catalog-111', '{"color":"сірий матовий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-111/3857.jpg', 3857),
('catalog-111', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-111/4098.jpg', 4098),
('catalog-111', '{"color":"ясен білий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-111/4099.jpg', 4099),
('catalog-111', '{"color":"дуб ciрий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-111/4100.jpg', 4100),
('catalog-111', '{"color":"дуб кремовий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-111/4101.jpg', 4101),
('catalog-111', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-111/4102.jpg', 4102),
('catalog-111', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-111/4103.jpg', 4103),
('catalog-111', '{"color":"бетон сiрий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-111/4104.jpg', 4104),
('catalog-111', '{"color":"сірий матовий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-111/4105.jpg', 4105),
('catalog-111', '{"color":"сірий матовий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-111/4677.jpg', 4677),
('catalog-111', '{"color":"кремовий матовий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-111/4849.jpg', 4849),
('catalog-111', '{"color":"кремовий матовий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-111/4850.jpg', 4850),
('catalog-111', '{"color":"кремовий матовий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-111/4851.jpg', 4851),
('catalog-111', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-111/4852.jpg', 4852),
('catalog-111', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-111/4853.jpg', 4853)
on conflict (product_slug, selections) do update
set image_path = excluded.image_path, sort_order = excluded.sort_order, is_active = true;
