-- Фото з офіційної сторінки Papa Carlo: https://papa-carlo.com.ua/ua/dverne-polotno-st-26/
-- Завантажте вміст папки tmp\papa-carlo-variants\catalog-115 у bucket catalog-images, зберігши шлях variants/papa-carlo/catalog-115.

insert into public.product_variants (product_slug, selections, image_path, sort_order)
values
('catalog-115', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-115/2073.jpg', 2073),
('catalog-115', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-115/2074.jpg', 2074),
('catalog-115', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-115/2075.jpg', 2075),
('catalog-115', '{"color":"ясен білий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-115/2076.jpg', 2076),
('catalog-115', '{"color":"ясен білий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-115/2077.jpg', 2077),
('catalog-115', '{"color":"дуб ciрий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-115/2078.jpg', 2078),
('catalog-115', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-115/2079.jpg', 2079),
('catalog-115', '{"color":"дуб ciрий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-115/2080.jpg', 2080),
('catalog-115', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-115/2081.jpg', 2081),
('catalog-115', '{"color":"дуб кремовий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-115/2082.jpg', 2082),
('catalog-115', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-115/2083.jpg', 2083),
('catalog-115', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-115/2084.jpg', 2084),
('catalog-115', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-115/2085.jpg', 2085),
('catalog-115', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-115/2086.jpg', 2086),
('catalog-115', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-115/2087.jpg', 2087),
('catalog-115', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-115/2088.jpg', 2088),
('catalog-115', '{"color":"бетон сiрий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-115/2089.jpg', 2089),
('catalog-115', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-115/2090.jpg', 2090),
('catalog-115', '{"color":"бетон сiрий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-115/2091.jpg', 2091),
('catalog-115', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-115/2270.jpg', 2270),
('catalog-115', '{"color":"сірий матовий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-115/2271.jpg', 2271),
('catalog-115', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-115/4034.jpg', 4034),
('catalog-115', '{"color":"ясен білий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-115/4035.jpg', 4035),
('catalog-115', '{"color":"дуб ciрий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-115/4036.jpg', 4036),
('catalog-115', '{"color":"дуб кремовий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-115/4037.jpg', 4037),
('catalog-115', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-115/4038.jpg', 4038),
('catalog-115', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-115/4039.jpg', 4039),
('catalog-115', '{"color":"бетон сiрий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-115/4040.jpg', 4040),
('catalog-115', '{"color":"сірий матовий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-115/4041.jpg', 4041),
('catalog-115', '{"color":"емаліт білий матовий (ral 9003)","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-115/4282.jpg', 4282),
('catalog-115', '{"color":"ясен білий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-115/4283.jpg', 4283),
('catalog-115', '{"color":"дуб ciрий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-115/4284.jpg', 4284),
('catalog-115', '{"color":"дуб кремовий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-115/4285.jpg', 4285),
('catalog-115', '{"color":"емаліт світло сірий супермат (ral 7044)","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-115/4286.jpg', 4286),
('catalog-115', '{"color":"емаліт темно сірий супермат (ral 7016)","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-115/4287.jpg', 4287),
('catalog-115', '{"color":"бетон сiрий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-115/4288.jpg', 4288),
('catalog-115', '{"color":"сірий матовий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-115/4289.jpg', 4289),
('catalog-115', '{"color":"сірий матовий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-115/4700.jpg', 4700),
('catalog-115', '{"color":"кремовий матовий","edge":"торець кромка ABC у колір полотна"}'::jsonb, 'variants/papa-carlo/catalog-115/4971.jpg', 4971),
('catalog-115', '{"color":"кремовий матовий","edge":"торець кромка ABC золота"}'::jsonb, 'variants/papa-carlo/catalog-115/4972.jpg', 4972),
('catalog-115', '{"color":"кремовий матовий","edge":"торець кромка ABC чорна"}'::jsonb, 'variants/papa-carlo/catalog-115/4973.jpg', 4973),
('catalog-115', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй сiрий"}'::jsonb, 'variants/papa-carlo/catalog-115/4974.jpg', 4974),
('catalog-115', '{"color":"кремовий матовий","edge":"торець кромка алюмiнiй чорний"}'::jsonb, 'variants/papa-carlo/catalog-115/4975.jpg', 4975)
on conflict (product_slug, selections) do update
set image_path = excluded.image_path, sort_order = excluded.sort_order, is_active = true;
