-- Market Dveri — Rodos Style R: 10 точних карток моделей.
-- Перевірено 03.09.2026. Скрипт можна запускати повторно; ціни не імпортуються.

with source(slug,label,image_path,source_url,source_product_name,leaf_type) as (
 values
 ('catalog-246','Style 1 · чорне скло','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/215819/dveri-rodos-style-r-style-1-chorne-sklo-main.jpg','https://market-dveri.ua/uk/dveri-style-1-blk-rodos/','Rodos Style R Style 1 чорне скло','Чорне скло'),
 ('catalog-247','Style 1 · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/215817/dveri-rodos-style-r-style-1-pg-main.jpg','https://market-dveri.ua/uk/dveri-style-1-pg-rodos/','Rodos Style R Style 1 ПГ','Глухе'),
 ('catalog-248','Style 2 · чорне скло','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/215822/dveri-rodos-style-r-style-2-chorne-sklo-main.jpg','https://market-dveri.ua/uk/dveri-style-2-blk-rodos/','Rodos Style R Style 2 чорне скло','Чорне скло'),
 ('catalog-249','Style 2 · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/215820/dveri-rodos-style-r-style-2-pg-main.jpg','https://market-dveri.ua/uk/dveri-style-2-pg-rodos/','Rodos Style R Style 2 ПГ','Глухе'),
 ('catalog-250','Style 3 · чорне скло','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/215825/dveri-rodos-style-r-style-3-chorne-sklo-main.jpg','https://market-dveri.ua/uk/dveri-style-3-blk-rodos/','Rodos Style R Style 3 чорне скло','Чорне скло'),
 ('catalog-251','Style 3 · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/215823/dveri-rodos-style-r-style-3-pg-main.jpg','https://market-dveri.ua/uk/dveri-style-3-pg-rodos/','Rodos Style R Style 3 ПГ','Глухе'),
 ('catalog-252','Style 4 · чорне скло','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/215828/dveri-rodos-style-r-style-4-chorne-sklo-main.jpg','https://market-dveri.ua/uk/dveri-style-4-blk-rodos/','Rodos Style R Style 4 чорне скло','Чорне скло'),
 ('catalog-253','Style 4 · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/215826/dveri-rodos-style-r-style-4-pg-main.jpg','https://market-dveri.ua/uk/dveri-style-4-pg-rodos/','Rodos Style R Style 4 ПГ','Глухе'),
 ('catalog-254','Style 5 · чорне скло','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/215831/dveri-rodos-style-r-style-5-chorne-sklo-main.jpg','https://market-dveri.ua/uk/dveri-style-5-blk-rodos/','Rodos Style R Style 5 чорне скло','Чорне скло'),
 ('catalog-255','Style 5 · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/215829/dveri-rodos-style-r-style-5-pg-main.jpg','https://market-dveri.ua/uk/dveri-style-5-pg-rodos/','Rodos Style R Style 5 ПГ','Глухе')
)
update public.products as product set description='Rodos ' || source.label || ' — сучасні міжкімнатні двері колекції Style R. Підтверджене фото відповідає саме цьому виконанню; актуальні декори уточнюйте у менеджера.',image_path=source.image_path from source where product.slug=source.slug;

with source(slug,label,image_path) as (
 values
 ('catalog-246','Style 1 · чорне скло','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/215819/dveri-rodos-style-r-style-1-chorne-sklo-main.jpg'),('catalog-247','Style 1 · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/215817/dveri-rodos-style-r-style-1-pg-main.jpg'),('catalog-248','Style 2 · чорне скло','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/215822/dveri-rodos-style-r-style-2-chorne-sklo-main.jpg'),('catalog-249','Style 2 · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/215820/dveri-rodos-style-r-style-2-pg-main.jpg'),('catalog-250','Style 3 · чорне скло','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/215825/dveri-rodos-style-r-style-3-chorne-sklo-main.jpg'),('catalog-251','Style 3 · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/215823/dveri-rodos-style-r-style-3-pg-main.jpg'),('catalog-252','Style 4 · чорне скло','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/215828/dveri-rodos-style-r-style-4-chorne-sklo-main.jpg'),('catalog-253','Style 4 · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/215826/dveri-rodos-style-r-style-4-pg-main.jpg'),('catalog-254','Style 5 · чорне скло','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/215831/dveri-rodos-style-r-style-5-chorne-sklo-main.jpg'),('catalog-255','Style 5 · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/215829/dveri-rodos-style-r-style-5-pg-main.jpg')
)
update public.product_media as media set image_path=source.image_path,label=source.label,sort_order=0,is_active=true from source where media.product_slug=source.slug and media.kind='main';

with models(product_slug,leaf_type) as (values ('catalog-246','Чорне скло'),('catalog-247','Глухе'),('catalog-248','Чорне скло'),('catalog-249','Глухе'),('catalog-250','Чорне скло'),('catalog-251','Глухе'),('catalog-252','Чорне скло'),('catalog-253','Глухе'),('catalog-254','Чорне скло'),('catalog-255','Глухе')), specs(product_slug,label,value,sort_order) as (
 select product_slug,'Тип виробу','Міжкімнатні двері',100 from models union all select product_slug,'Тип полотна',leaf_type,110 from models union all select product_slug,'Покриття','ПВХ плівка',120 from models union all select product_slug,'Товщина полотна','44 мм',130 from models union all select product_slug,'Доступні ширини','600 / 700 / 800 / 900 мм',140 from models union all select product_slug,'Висота полотна','2000 мм',150 from models union all select product_slug,'Відкривання','Розпашні, одностулкові',160 from models union all select product_slug,'Погонаж','Телескопічний або компланарний',170 from models union all select product_slug,'Країна виробництва','Україна',180 from models
)
insert into public.product_specs(product_slug,label,value,sort_order) select product_slug,label,value,sort_order from specs on conflict(product_slug,label) do update set value=excluded.value,sort_order=excluded.sort_order,is_active=true;

insert into public.product_sources(product_slug,source_name,source_url,source_product_name,verification_status,verified_at,notes) select slug,'Market Dveri',source_url,source_product_name,'verified',now(),'Модель, виконання та головне фото збігаються.' from (values
 ('catalog-246','https://market-dveri.ua/uk/dveri-style-1-blk-rodos/','Rodos Style R Style 1 чорне скло'),('catalog-247','https://market-dveri.ua/uk/dveri-style-1-pg-rodos/','Rodos Style R Style 1 ПГ'),('catalog-248','https://market-dveri.ua/uk/dveri-style-2-blk-rodos/','Rodos Style R Style 2 чорне скло'),('catalog-249','https://market-dveri.ua/uk/dveri-style-2-pg-rodos/','Rodos Style R Style 2 ПГ'),('catalog-250','https://market-dveri.ua/uk/dveri-style-3-blk-rodos/','Rodos Style R Style 3 чорне скло'),('catalog-251','https://market-dveri.ua/uk/dveri-style-3-pg-rodos/','Rodos Style R Style 3 ПГ'),('catalog-252','https://market-dveri.ua/uk/dveri-style-4-blk-rodos/','Rodos Style R Style 4 чорне скло'),('catalog-253','https://market-dveri.ua/uk/dveri-style-4-pg-rodos/','Rodos Style R Style 4 ПГ'),('catalog-254','https://market-dveri.ua/uk/dveri-style-5-blk-rodos/','Rodos Style R Style 5 чорне скло'),('catalog-255','https://market-dveri.ua/uk/dveri-style-5-pg-rodos/','Rodos Style R Style 5 ПГ')
) as source(slug,source_url,source_product_name) on conflict(product_slug,source_url) do update set source_name=excluded.source_name,source_product_name=excluded.source_product_name,verification_status=excluded.verification_status,verified_at=excluded.verified_at,notes=excluded.notes;
