-- Market Dveri — Rodos Cortes: 16 точних карток моделей.
-- Перевірено 03.09.2026: модель, тип полотна й головне фото збігаються.
-- Ціни навмисно не імпортуються. Скрипт можна запускати повторно.

with source(slug, description, label, image_path, source_url, source_product_name, leaf_type) as (
  values
    ('catalog-194','Rodos Cortes Dolce 3 — пофарбовані міжкімнатні двері з глухим полотном. Модель доступна у білому матовому виконанні та вибраних кольорах палітри RAL.','Cortes Dolce 3 · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213912/dveri-rodos-cortes-dolce-3-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-dolce-3-pg-ral-rodos/','Rodos Cortes Dolce 3 ПГ RAL','Глухе'),
    ('catalog-195','Rodos Cortes Dolce 4 — пофарбовані міжкімнатні двері з глухим полотном. Модель доступна у білому матовому виконанні та вибраних кольорах палітри RAL.','Cortes Dolce 4 · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213914/dveri-rodos-cortes-dolce-4-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-dolce-4-pg-ral-rodos/','Rodos Cortes Dolce 4 ПГ RAL','Глухе'),
    ('catalog-196','Rodos Cortes Dolce — пофарбовані міжкімнатні двері з глухим полотном. Модель доступна у білому матовому виконанні та вибраних кольорах палітри RAL.','Cortes Dolce · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213910/dveri-rodos-cortes-dolce-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-dolce-pg-ral-rodos/','Rodos Cortes Dolce ПГ RAL','Глухе'),
    ('catalog-197','Rodos Cortes Galant — пофарбовані міжкімнатні двері з глухим полотном. Доступні у білому матовому виконанні та вибраних кольорах палітри RAL.','Cortes Galant · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213917/dveri-rodos-cortes-galant-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-galant-pg-ral-rodos/','Rodos Cortes Galant ПГ RAL','Глухе'),
    ('catalog-199','Rodos Cortes Galant ПО — пофарбовані міжкімнатні двері зі скляною вставкою. Фото підтверджене для білого матового виконання.','Cortes Galant ПО · білий мат','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/22381/dveri-rodos-cortes-galant-po-bilij-mat-main.jpg','https://market-dveri.ua/uk/galant-po-belyy-mat-22381/','Rodos Cortes Galant ПО білий мат','Зі склом'),
    ('catalog-200','Rodos Cortes Galliano — пофарбовані міжкімнатні двері з глухим полотном. Фото підтверджене для білого матового виконання.','Cortes Galliano · білий мат','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/27075/dveri-rodos-cortes-galliano-pg-bilij-mat-main.jpg','https://market-dveri.ua/uk/dveri-galliano-pg-bilyj-mat-rodos/','Rodos Cortes Galliano ПГ білий мат','Глухе'),
    ('catalog-201','Rodos Cortes Gaudi — пофарбовані міжкімнатні двері з глухим полотном. Фото підтверджене для білого матового виконання.','Cortes Gaudi · білий мат','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/27077/dveri-rodos-cortes-gaudi-pg-bilij-mat-main.jpg','https://market-dveri.ua/uk/dveri-gaudi-pg-bilyj-mat-rodos/','Rodos Cortes Gaudi ПГ білий мат','Глухе'),
    ('catalog-202','Rodos Cortes Jazz — пофарбовані міжкімнатні двері з глухим полотном. Модель доступна у білому матовому виконанні та вибраних кольорах палітри RAL.','Cortes Jazz · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213915/dveri-rodos-cortes-jazz-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-jazz-pg-ral-rodos/','Rodos Cortes Jazz ПГ RAL','Глухе'),
    ('catalog-203','Rodos Cortes Prima 1G — пофарбовані міжкімнатні двері з глухим полотном. Модель доступна у білому матовому виконанні та вибраних кольорах палітри RAL.','Cortes Prima 1G · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213906/dveri-rodos-cortes-prima-1g-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-prima-1g-pg-ral-rodos/','Rodos Cortes Prima 1G ПГ RAL','Глухе'),
    ('catalog-204','Rodos Cortes Prima 3G — пофарбовані міжкімнатні двері з глухим полотном. Модель доступна у білому матовому виконанні та вибраних кольорах палітри RAL.','Cortes Prima 3G · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213907/dveri-rodos-cortes-prima-3g-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-prima-3g-pg-ral-rodos/','Rodos Cortes Prima 3G ПГ RAL','Глухе'),
    ('catalog-205','Rodos Cortes Prima 3V — пофарбовані міжкімнатні двері з глухим полотном. Модель доступна у білому матовому виконанні та вибраних кольорах палітри RAL.','Cortes Prima 3V · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213908/dveri-rodos-cortes-prima-3v-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-prima-3v-pg-ral-rodos/','Rodos Cortes Prima 3V ПГ RAL','Глухе'),
    ('catalog-206','Rodos Cortes Prima 3V1 — пофарбовані міжкімнатні двері з глухим полотном. Модель доступна у білому матовому виконанні та вибраних кольорах палітри RAL.','Cortes Prima 3V1 · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213909/dveri-rodos-cortes-prima-3v1-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-prima-3v1-pg-ral-rodos/','Rodos Cortes Prima 3V1 ПГ RAL','Глухе'),
    ('catalog-210','Rodos Cortes Roma — пофарбовані міжкімнатні двері з глухим полотном. Модель доступна у білому матовому виконанні та вибраних кольорах палітри RAL.','Cortes Roma · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213919/dveri-rodos-cortes-roma-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-roma-pg-ral-rodos/','Rodos Cortes Roma ПГ RAL','Глухе'),
    ('catalog-211','Rodos Cortes Salsa — пофарбовані міжкімнатні двері з глухим полотном. Модель доступна у білому матовому виконанні та вибраних кольорах палітри RAL.','Cortes Salsa · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213920/dveri-rodos-cortes-salsa-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-salsa-pg-ral-rodos/','Rodos Cortes Salsa ПГ RAL','Глухе'),
    ('catalog-212','Rodos Cortes Selena — пофарбовані міжкімнатні двері з глухим полотном. Модель доступна у білому матовому виконанні та вибраних кольорах палітри RAL.','Cortes Selena · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213916/dveri-rodos-cortes-selena-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-selena-pg-ral-rodos/','Rodos Cortes Selena ПГ RAL','Глухе'),
    ('catalog-213','Rodos Cortes Tango — пофарбовані міжкімнатні двері з глухим полотном. Модель доступна у білому матовому виконанні та вибраних кольорах палітри RAL.','Cortes Tango · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213921/dveri-rodos-cortes-tango-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-tango-pg-ral-rodos/','Rodos Cortes Tango ПГ RAL','Глухе')
)
update public.products as product set description=source.description,image_path=source.image_path from source where product.slug=source.slug;

with source(slug,label,image_path) as (
  values
    ('catalog-194','Cortes Dolce 3 · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213912/dveri-rodos-cortes-dolce-3-pg-ral-main.jpg'),('catalog-195','Cortes Dolce 4 · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213914/dveri-rodos-cortes-dolce-4-pg-ral-main.jpg'),('catalog-196','Cortes Dolce · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213910/dveri-rodos-cortes-dolce-pg-ral-main.jpg'),('catalog-197','Cortes Galant · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213917/dveri-rodos-cortes-galant-pg-ral-main.jpg'),('catalog-199','Cortes Galant ПО · білий мат','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/22381/dveri-rodos-cortes-galant-po-bilij-mat-main.jpg'),('catalog-200','Cortes Galliano · білий мат','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/27075/dveri-rodos-cortes-galliano-pg-bilij-mat-main.jpg'),('catalog-201','Cortes Gaudi · білий мат','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/27077/dveri-rodos-cortes-gaudi-pg-bilij-mat-main.jpg'),('catalog-202','Cortes Jazz · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213915/dveri-rodos-cortes-jazz-pg-ral-main.jpg'),('catalog-203','Cortes Prima 1G · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213906/dveri-rodos-cortes-prima-1g-pg-ral-main.jpg'),('catalog-204','Cortes Prima 3G · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213907/dveri-rodos-cortes-prima-3g-pg-ral-main.jpg'),('catalog-205','Cortes Prima 3V · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213908/dveri-rodos-cortes-prima-3v-pg-ral-main.jpg'),('catalog-206','Cortes Prima 3V1 · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213909/dveri-rodos-cortes-prima-3v1-pg-ral-main.jpg'),('catalog-210','Cortes Roma · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213919/dveri-rodos-cortes-roma-pg-ral-main.jpg'),('catalog-211','Cortes Salsa · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213920/dveri-rodos-cortes-salsa-pg-ral-main.jpg'),('catalog-212','Cortes Selena · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213916/dveri-rodos-cortes-selena-pg-ral-main.jpg'),('catalog-213','Cortes Tango · глухе','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213921/dveri-rodos-cortes-tango-pg-ral-main.jpg')
)
update public.product_media as media set image_path=source.image_path,label=source.label,sort_order=0,is_active=true from source where media.product_slug=source.slug and media.kind='main';

with models(product_slug,leaf_type) as (
  values ('catalog-194','Глухе'),('catalog-195','Глухе'),('catalog-196','Глухе'),('catalog-197','Глухе'),('catalog-199','Зі склом'),('catalog-200','Глухе'),('catalog-201','Глухе'),('catalog-202','Глухе'),('catalog-203','Глухе'),('catalog-204','Глухе'),('catalog-205','Глухе'),('catalog-206','Глухе'),('catalog-210','Глухе'),('catalog-211','Глухе'),('catalog-212','Глухе'),('catalog-213','Глухе')
), specs(product_slug,label,value,sort_order) as (
  select product_slug,'Тип виробу','Міжкімнатні двері',100 from models
  union all select product_slug,'Тип полотна',leaf_type,110 from models
  union all select product_slug,'Покриття','Фарба',120 from models
  union all select product_slug,'Базовий декор','Білий мат; можливе фарбування у вибрані кольори RAL',130 from models
  union all select product_slug,'Товщина полотна','44 мм',140 from models
  union all select product_slug,'Доступні ширини','600 / 700 / 800 / 900 мм',150 from models
  union all select product_slug,'Висота полотна','2000 мм',160 from models
  union all select product_slug,'Відкривання','Розпашні, одностулкові',170 from models
  union all select product_slug,'Погонаж','Телескопічний або компланарний',180 from models
  union all select product_slug,'Підрізка полотна','До 20 мм',190 from models
  union all select product_slug,'Країна виробництва','Україна',200 from models
)
insert into public.product_specs(product_slug,label,value,sort_order) select product_slug,label,value,sort_order from specs
on conflict(product_slug,label) do update set value=excluded.value,sort_order=excluded.sort_order,is_active=true;

insert into public.product_sources(product_slug,source_name,source_url,source_product_name,verification_status,verified_at,notes) values
  ('catalog-194','Market Dveri','https://market-dveri.ua/uk/dveri-dolce-3-pg-ral-rodos/','Rodos Cortes Dolce 3 ПГ RAL','verified',now(),'Модель, тип полотна та головне фото збігаються.'),('catalog-195','Market Dveri','https://market-dveri.ua/uk/dveri-dolce-4-pg-ral-rodos/','Rodos Cortes Dolce 4 ПГ RAL','verified',now(),'Модель, тип полотна та головне фото збігаються.'),('catalog-196','Market Dveri','https://market-dveri.ua/uk/dveri-dolce-pg-ral-rodos/','Rodos Cortes Dolce ПГ RAL','verified',now(),'Модель, тип полотна та головне фото збігаються.'),('catalog-197','Market Dveri','https://market-dveri.ua/uk/dveri-galant-pg-ral-rodos/','Rodos Cortes Galant ПГ RAL','verified',now(),'Модель, тип полотна та головне фото збігаються.'),('catalog-199','Market Dveri','https://market-dveri.ua/uk/galant-po-belyy-mat-22381/','Rodos Cortes Galant ПО білий мат','verified',now(),'Модель, тип полотна та головне фото збігаються.'),('catalog-200','Market Dveri','https://market-dveri.ua/uk/dveri-galliano-pg-bilyj-mat-rodos/','Rodos Cortes Galliano ПГ білий мат','verified',now(),'Модель, тип полотна та головне фото збігаються.'),('catalog-201','Market Dveri','https://market-dveri.ua/uk/dveri-gaudi-pg-bilyj-mat-rodos/','Rodos Cortes Gaudi ПГ білий мат','verified',now(),'Модель, тип полотна та головне фото збігаються.'),('catalog-202','Market Dveri','https://market-dveri.ua/uk/dveri-jazz-pg-ral-rodos/','Rodos Cortes Jazz ПГ RAL','verified',now(),'Модель, тип полотна та головне фото збігаються.'),('catalog-203','Market Dveri','https://market-dveri.ua/uk/dveri-prima-1g-pg-ral-rodos/','Rodos Cortes Prima 1G ПГ RAL','verified',now(),'Модель, тип полотна та головне фото збігаються.'),('catalog-204','Market Dveri','https://market-dveri.ua/uk/dveri-prima-3g-pg-ral-rodos/','Rodos Cortes Prima 3G ПГ RAL','verified',now(),'Модель, тип полотна та головне фото збігаються.'),('catalog-205','Market Dveri','https://market-dveri.ua/uk/dveri-prima-3v-pg-ral-rodos/','Rodos Cortes Prima 3V ПГ RAL','verified',now(),'Модель, тип полотна та головне фото збігаються.'),('catalog-206','Market Dveri','https://market-dveri.ua/uk/dveri-prima-3v1-pg-ral-rodos/','Rodos Cortes Prima 3V1 ПГ RAL','verified',now(),'Модель, тип полотна та головне фото збігаються.'),('catalog-210','Market Dveri','https://market-dveri.ua/uk/dveri-roma-pg-ral-rodos/','Rodos Cortes Roma ПГ RAL','verified',now(),'Модель, тип полотна та головне фото збігаються.'),('catalog-211','Market Dveri','https://market-dveri.ua/uk/dveri-salsa-pg-ral-rodos/','Rodos Cortes Salsa ПГ RAL','verified',now(),'Модель, тип полотна та головне фото збігаються.'),('catalog-212','Market Dveri','https://market-dveri.ua/uk/dveri-selena-pg-ral-rodos/','Rodos Cortes Selena ПГ RAL','verified',now(),'Модель, тип полотна та головне фото збігаються.'),('catalog-213','Market Dveri','https://market-dveri.ua/uk/dveri-tango-pg-ral-rodos/','Rodos Cortes Tango ПГ RAL','verified',now(),'Модель, тип полотна та головне фото збігаються.')
on conflict(product_slug,source_url) do update set source_name=excluded.source_name,source_product_name=excluded.source_product_name,verification_status=excluded.verification_status,verified_at=excluded.verified_at,notes=excluded.notes;
