-- Market Dveri — Grand LUX: 10 точних карток моделей.
-- Перевірено 03.09.2026. Скрипт можна запускати повторно; ціни не імпортуються.

with source(slug,label,image_path,source_url,source_product_name,leaf_type) as (values
 ('catalog-30','Grand Lux 1','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/grand/24086/dveri-grand-grand-lux-1-main.jpg','https://market-dveri.ua/uk/grand-lux-1-24086/','ГРАНД Grand Lux-1','Глухе'),
 ('catalog-31','Grand Lux 11','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/grand/212843/dveri-grand-grand-lux-11-main.jpg','https://market-dveri.ua/uk/dveri-grand-lux-11-grand/','ГРАНД Grand Lux-11','Глухе'),
 ('catalog-32','Grand Lux 13','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/grand/212845/dveri-grand-grand-lux-13-main.jpg','https://market-dveri.ua/uk/dveri-grand-lux-13-grand/','ГРАНД Grand Lux-13','Глухе'),
 ('catalog-33','Grand Lux 14','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/grand/223070/dveri-grand-grand-lux-14-main.jpg','https://market-dveri.ua/uk/dveri-grand-lux-14-grand/','ГРАНД Grand Lux-14','Глухе'),
 ('catalog-34','Grand Lux 2','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/grand/24087/dveri-grand-grand-lux-2-main.jpg','https://market-dveri.ua/uk/grand-lux-2-24087/','ГРАНД Grand Lux-2','Глухе'),
 ('catalog-35','Grand Lux 3','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/grand/27771/dveri-grand-grand-lux-3-main.jpg','https://market-dveri.ua/uk/dveri-grand-lux-3-grand/','ГРАНД Grand Lux-3','Глухе'),
 ('catalog-36','Grand Lux 4 · чорне скло','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/grand/212837/dveri-grand-grand-lux-4-chorne-sklo-main.jpg','https://market-dveri.ua/uk/dveri-grand-lux-4-blk-grand/','ГРАНД Grand Lux-4 чорне скло','Чорне скло'),
 ('catalog-37','Grand Lux 5','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/grand/28781/dveri-grand-grand-lux-5-main.jpg','https://market-dveri.ua/uk/dveri-grand-lux-5-grand/','ГРАНД Grand Lux-5','Глухе'),
 ('catalog-38','Grand Lux 6','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/grand/28918/dveri-grand-grand-lux-6-main.jpg','https://market-dveri.ua/uk/dveri-grand-lux-6-grand/','ГРАНД Grand Lux-6','Глухе'),
 ('catalog-39','Grand Lux 8','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/grand/10080/dveri-grand-grand-lux-8-main.jpg','https://market-dveri.ua/uk/dveri-grand-lux-8-grand/','ГРАНД Grand Lux-8','Глухе')
)
update public.products as product set description='Grand ' || source.label || ' — міжкімнатні двері колекції LUX із ПВХ-покриттям. Підтверджене фото відповідає зазначеній моделі; доступні декори уточнюйте у менеджера.',image_path=source.image_path from source where product.slug=source.slug;

with source(slug,label,image_path) as (values
 ('catalog-30','Grand Lux 1','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/grand/24086/dveri-grand-grand-lux-1-main.jpg'),('catalog-31','Grand Lux 11','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/grand/212843/dveri-grand-grand-lux-11-main.jpg'),('catalog-32','Grand Lux 13','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/grand/212845/dveri-grand-grand-lux-13-main.jpg'),('catalog-33','Grand Lux 14','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/grand/223070/dveri-grand-grand-lux-14-main.jpg'),('catalog-34','Grand Lux 2','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/grand/24087/dveri-grand-grand-lux-2-main.jpg'),('catalog-35','Grand Lux 3','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/grand/27771/dveri-grand-grand-lux-3-main.jpg'),('catalog-36','Grand Lux 4 · чорне скло','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/grand/212837/dveri-grand-grand-lux-4-chorne-sklo-main.jpg'),('catalog-37','Grand Lux 5','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/grand/28781/dveri-grand-grand-lux-5-main.jpg'),('catalog-38','Grand Lux 6','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/grand/28918/dveri-grand-grand-lux-6-main.jpg'),('catalog-39','Grand Lux 8','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/grand/10080/dveri-grand-grand-lux-8-main.jpg')
)
update public.product_media as media set image_path=source.image_path,label=source.label,sort_order=0,is_active=true from source where media.product_slug=source.slug and media.kind='main';

with models(product_slug,leaf_type) as (values ('catalog-30','Глухе'),('catalog-31','Глухе'),('catalog-32','Глухе'),('catalog-33','Глухе'),('catalog-34','Глухе'),('catalog-35','Глухе'),('catalog-36','Чорне скло'),('catalog-37','Глухе'),('catalog-38','Глухе'),('catalog-39','Глухе')), specs(product_slug,label,value,sort_order) as (
 select product_slug,'Тип виробу','Міжкімнатні двері',100 from models union all select product_slug,'Тип полотна',leaf_type,110 from models union all select product_slug,'Покриття','ПВХ плівка',120 from models union all select product_slug,'Товщина полотна','44 мм',130 from models union all select product_slug,'Доступні ширини','600 / 700 / 800 / 900 мм',140 from models union all select product_slug,'Висота полотна','2000 мм',150 from models union all select product_slug,'Відкривання','Розпашні, одностулкові',160 from models union all select product_slug,'Країна виробництва','Україна',170 from models
)
insert into public.product_specs(product_slug,label,value,sort_order) select product_slug,label,value,sort_order from specs on conflict(product_slug,label) do update set value=excluded.value,sort_order=excluded.sort_order,is_active=true;

insert into public.product_sources(product_slug,source_name,source_url,source_product_name,verification_status,verified_at,notes) select slug,'Market Dveri',source_url,source_product_name,'verified',now(),'Модель, виконання та головне фото збігаються.' from (values
 ('catalog-30','https://market-dveri.ua/uk/grand-lux-1-24086/','ГРАНД Grand Lux-1'),('catalog-31','https://market-dveri.ua/uk/dveri-grand-lux-11-grand/','ГРАНД Grand Lux-11'),('catalog-32','https://market-dveri.ua/uk/dveri-grand-lux-13-grand/','ГРАНД Grand Lux-13'),('catalog-33','https://market-dveri.ua/uk/dveri-grand-lux-14-grand/','ГРАНД Grand Lux-14'),('catalog-34','https://market-dveri.ua/uk/grand-lux-2-24087/','ГРАНД Grand Lux-2'),('catalog-35','https://market-dveri.ua/uk/dveri-grand-lux-3-grand/','ГРАНД Grand Lux-3'),('catalog-36','https://market-dveri.ua/uk/dveri-grand-lux-4-blk-grand/','ГРАНД Grand Lux-4 чорне скло'),('catalog-37','https://market-dveri.ua/uk/dveri-grand-lux-5-grand/','ГРАНД Grand Lux-5'),('catalog-38','https://market-dveri.ua/uk/dveri-grand-lux-6-grand/','ГРАНД Grand Lux-6'),('catalog-39','https://market-dveri.ua/uk/dveri-grand-lux-8-grand/','ГРАНД Grand Lux-8')
) as source(slug,source_url,source_product_name) on conflict(product_slug,source_url) do update set source_name=excluded.source_name,source_product_name=excluded.source_product_name,verification_status=excluded.verification_status,verified_at=excluded.verified_at,notes=excluded.notes;
