-- Market Dveri — Rodos Loft: 18 точних карток моделей.
-- Перевірено 03.09.2026: назва моделі й головне фото збігаються.
-- Ціни навмисно не імпортуються. Скрипт можна запускати повторно.

with source(slug,label,image_path,source_url,source_product_name,leaf_type) as (
  values
  ('catalog-216','Loft Arrigo · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/27067/dveri-rodos-loft-arrigo-ral-main.jpg','https://market-dveri.ua/uk/dveri-arrigo-ral-rodos/','Rodos Loft Arrigo RAL','Зі склом'),
  ('catalog-217','Loft Arte · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213881/dveri-rodos-loft-arte-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-arte-pg-ral-rodos/','Rodos Loft Arte ПГ RAL','Глухе'),
  ('catalog-218','Loft Aura · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213883/dveri-rodos-loft-aura-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-aura-pg-ral-rodos/','Rodos Loft Aura ПГ RAL','Глухе'),
  ('catalog-219','Loft Berta G · білий мат','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/22126/dveri-rodos-loft-berta-g-bilij-mat-main.jpg','https://market-dveri.ua/uk/berta-g-belyy-mat-22126/','Rodos Loft Berta G білий мат','Глухе'),
  ('catalog-220','Loft Berta GL · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213897/dveri-rodos-loft-berta-gl-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-berta-gl-pg-ral-rodos/','Rodos Loft Berta GL ПГ RAL','Глухе'),
  ('catalog-221','Loft Berta GW · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213899/dveri-rodos-loft-berta-gw-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-berta-gw-pg-ral-rodos/','Rodos Loft Berta GW ПГ RAL','Глухе'),
  ('catalog-222','Loft Berta V · білий мат','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/22125/dveri-rodos-loft-berta-v-bilij-mat-main.jpg','https://market-dveri.ua/uk/berta-v-belyy-mat-22125/','Rodos Loft Berta V білий мат','Глухе'),
  ('catalog-224','Loft Cosmo · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/27070/dveri-rodos-loft-cosmo-ral-main.jpg','https://market-dveri.ua/uk/dveri-cosmo-ral-rodos/','Rodos Loft Cosmo RAL','Глухе'),
  ('catalog-226','Loft Lago 2 · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213887/dveri-rodos-loft-lago-2-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-lago-2-pg-ral-rodos/','Rodos Loft Lago 2 ПГ RAL','Глухе'),
  ('catalog-227','Loft Lago 3 · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213889/dveri-rodos-loft-lago-3-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-lago-3-pg-ral-rodos/','Rodos Loft Lago 3 ПГ RAL','Глухе'),
  ('catalog-228','Loft Nikoletta · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/27072/dveri-rodos-loft-nikoletta-ral-main.jpg','https://market-dveri.ua/uk/dveri-nikoletta-ral-rodos/','Rodos Loft Nikoletta RAL','Глухе'),
  ('catalog-229','Loft Olimpia 2 · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213893/dveri-rodos-loft-olimpia-2-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-olimpia-2-pg-ral-rodos/','Rodos Loft Olimpia 2 ПГ RAL','Глухе'),
  ('catalog-230','Loft Olimpia 3 · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213895/dveri-rodos-loft-olimpia-3-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-olimpia-3-pg-ral-rodos/','Rodos Loft Olimpia 3 ПГ RAL','Глухе'),
  ('catalog-231','Loft Olimpia · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213891/dveri-rodos-loft-olimpia-pg-ral-main.jpg','https://market-dveri.ua/uk/dveri-olimpia-pg-ral-rodos/','Rodos Loft Olimpia ПГ RAL','Глухе'),
  ('catalog-232','Loft Porto 2 · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/22391/dveri-rodos-loft-porto-2-pg-ral-main.jpg','https://market-dveri.ua/uk/porto-2-pg-ral-22391/','Rodos Loft Porto 2 ПГ RAL','Глухе'),
  ('catalog-233','Loft Porto 3 · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213902/dveri-rodos-loft-porto-3-po-ral-main.jpg','https://market-dveri.ua/uk/dveri-porto-3-po-ral-rodos/','Rodos Loft Porto 3 ПО RAL','Зі склом'),
  ('catalog-234','Loft Porto · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213900/dveri-rodos-loft-porto-po-ral-main.jpg','https://market-dveri.ua/uk/dveri-porto-po-ral-rodos/','Rodos Loft Porto ПО RAL','Зі склом'),
  ('catalog-235','Loft Wave G · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213903/dveri-rodos-loft-wave-g-ral-main.jpg','https://market-dveri.ua/uk/dveri-wave-g-ral-rodos/','Rodos Loft Wave G RAL','Глухе')
)
update public.products as product
set description = 'Rodos ' || source.label || ' — пофарбовані міжкімнатні двері колекції Loft. Підтверджене фото відповідає зазначеному виконанню; доступні кольори уточнюйте у менеджера.', image_path = source.image_path
from source where product.slug = source.slug;

with source(slug,label,image_path) as (
  values
  ('catalog-216','Loft Arrigo · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/27067/dveri-rodos-loft-arrigo-ral-main.jpg'),('catalog-217','Loft Arte · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213881/dveri-rodos-loft-arte-pg-ral-main.jpg'),('catalog-218','Loft Aura · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213883/dveri-rodos-loft-aura-pg-ral-main.jpg'),('catalog-219','Loft Berta G · білий мат','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/22126/dveri-rodos-loft-berta-g-bilij-mat-main.jpg'),('catalog-220','Loft Berta GL · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213897/dveri-rodos-loft-berta-gl-pg-ral-main.jpg'),('catalog-221','Loft Berta GW · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213899/dveri-rodos-loft-berta-gw-pg-ral-main.jpg'),('catalog-222','Loft Berta V · білий мат','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/22125/dveri-rodos-loft-berta-v-bilij-mat-main.jpg'),('catalog-224','Loft Cosmo · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/27070/dveri-rodos-loft-cosmo-ral-main.jpg'),('catalog-226','Loft Lago 2 · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213887/dveri-rodos-loft-lago-2-pg-ral-main.jpg'),('catalog-227','Loft Lago 3 · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213889/dveri-rodos-loft-lago-3-pg-ral-main.jpg'),('catalog-228','Loft Nikoletta · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/27072/dveri-rodos-loft-nikoletta-ral-main.jpg'),('catalog-229','Loft Olimpia 2 · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213893/dveri-rodos-loft-olimpia-2-pg-ral-main.jpg'),('catalog-230','Loft Olimpia 3 · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213895/dveri-rodos-loft-olimpia-3-pg-ral-main.jpg'),('catalog-231','Loft Olimpia · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213891/dveri-rodos-loft-olimpia-pg-ral-main.jpg'),('catalog-232','Loft Porto 2 · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/22391/dveri-rodos-loft-porto-2-pg-ral-main.jpg'),('catalog-233','Loft Porto 3 · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213902/dveri-rodos-loft-porto-3-po-ral-main.jpg'),('catalog-234','Loft Porto · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213900/dveri-rodos-loft-porto-po-ral-main.jpg'),('catalog-235','Loft Wave G · RAL','https://market-dveri.ua/image/catalog/product/mizhkimnatni-dveri/rodos/213903/dveri-rodos-loft-wave-g-ral-main.jpg')
)
update public.product_media as media set image_path=source.image_path,label=source.label,sort_order=0,is_active=true from source where media.product_slug=source.slug and media.kind='main';

with models(product_slug,leaf_type) as (
 values ('catalog-216','Зі склом'),('catalog-217','Глухе'),('catalog-218','Глухе'),('catalog-219','Глухе'),('catalog-220','Глухе'),('catalog-221','Глухе'),('catalog-222','Глухе'),('catalog-224','Глухе'),('catalog-226','Глухе'),('catalog-227','Глухе'),('catalog-228','Глухе'),('catalog-229','Глухе'),('catalog-230','Глухе'),('catalog-231','Глухе'),('catalog-232','Глухе'),('catalog-233','Зі склом'),('catalog-234','Зі склом'),('catalog-235','Глухе')
), specs(product_slug,label,value,sort_order) as (
 select product_slug,'Тип виробу','Міжкімнатні двері',100 from models union all select product_slug,'Тип полотна',leaf_type,110 from models union all select product_slug,'Покриття','Фарба',120 from models union all select product_slug,'Базовий декор','Білий мат; можливе фарбування у вибрані кольори RAL',130 from models union all select product_slug,'Товщина полотна','44 мм',140 from models union all select product_slug,'Доступні ширини','600 / 700 / 800 / 900 мм',150 from models union all select product_slug,'Висота полотна','2000 мм',160 from models union all select product_slug,'Відкривання','Розпашні, одностулкові',170 from models union all select product_slug,'Погонаж','Телескопічний або компланарний',180 from models union all select product_slug,'Підрізка полотна','До 20 мм',190 from models union all select product_slug,'Країна виробництва','Україна',200 from models
)
insert into public.product_specs(product_slug,label,value,sort_order) select product_slug,label,value,sort_order from specs on conflict(product_slug,label) do update set value=excluded.value,sort_order=excluded.sort_order,is_active=true;

insert into public.product_sources(product_slug,source_name,source_url,source_product_name,verification_status,verified_at,notes)
select slug,'Market Dveri',source_url,source_product_name,'verified',now(),'Модель і головне фото збігаються.' from (values
 ('catalog-216','https://market-dveri.ua/uk/dveri-arrigo-ral-rodos/','Rodos Loft Arrigo RAL'),('catalog-217','https://market-dveri.ua/uk/dveri-arte-pg-ral-rodos/','Rodos Loft Arte ПГ RAL'),('catalog-218','https://market-dveri.ua/uk/dveri-aura-pg-ral-rodos/','Rodos Loft Aura ПГ RAL'),('catalog-219','https://market-dveri.ua/uk/berta-g-belyy-mat-22126/','Rodos Loft Berta G білий мат'),('catalog-220','https://market-dveri.ua/uk/dveri-berta-gl-pg-ral-rodos/','Rodos Loft Berta GL ПГ RAL'),('catalog-221','https://market-dveri.ua/uk/dveri-berta-gw-pg-ral-rodos/','Rodos Loft Berta GW ПГ RAL'),('catalog-222','https://market-dveri.ua/uk/berta-v-belyy-mat-22125/','Rodos Loft Berta V білий мат'),('catalog-224','https://market-dveri.ua/uk/dveri-cosmo-ral-rodos/','Rodos Loft Cosmo RAL'),('catalog-226','https://market-dveri.ua/uk/dveri-lago-2-pg-ral-rodos/','Rodos Loft Lago 2 ПГ RAL'),('catalog-227','https://market-dveri.ua/uk/dveri-lago-3-pg-ral-rodos/','Rodos Loft Lago 3 ПГ RAL'),('catalog-228','https://market-dveri.ua/uk/dveri-nikoletta-ral-rodos/','Rodos Loft Nikoletta RAL'),('catalog-229','https://market-dveri.ua/uk/dveri-olimpia-2-pg-ral-rodos/','Rodos Loft Olimpia 2 ПГ RAL'),('catalog-230','https://market-dveri.ua/uk/dveri-olimpia-3-pg-ral-rodos/','Rodos Loft Olimpia 3 ПГ RAL'),('catalog-231','https://market-dveri.ua/uk/dveri-olimpia-pg-ral-rodos/','Rodos Loft Olimpia ПГ RAL'),('catalog-232','https://market-dveri.ua/uk/porto-2-pg-ral-22391/','Rodos Loft Porto 2 ПГ RAL'),('catalog-233','https://market-dveri.ua/uk/dveri-porto-3-po-ral-rodos/','Rodos Loft Porto 3 ПО RAL'),('catalog-234','https://market-dveri.ua/uk/dveri-porto-po-ral-rodos/','Rodos Loft Porto ПО RAL'),('catalog-235','https://market-dveri.ua/uk/dveri-wave-g-ral-rodos/','Rodos Loft Wave G RAL')
) as source(slug,source_url,source_product_name)
on conflict(product_slug,source_url) do update set source_name=excluded.source_name,source_product_name=excluded.source_product_name,verification_status=excluded.verification_status,verified_at=excluded.verified_at,notes=excluded.notes;
