-- Market Dveri — Q Doors Стріт: чотири точні виконання моделей.
-- Перевірено 03.09.2026. Скрипт можна запускати повторно; ціни не імпортуються.

with source(slug,label,image_path,description,source_url,source_product_name,contours) as (values
 ('catalog-55','Стріт Горизонталь · антрацит / біле дерево','https://market-dveri.ua/image/catalog/product/vhidni-dveri/qdoors/219206/dveri-strit-gorizontal-metal-antratsit-7021-farba-mdf-bile-derevo-vinorit-3k-qdoors-main.jpg','Q Doors Стріт Горизонталь — вуличні вхідні двері з антрацитовим металом RAL 7021 зовні та МДФ-панеллю «біле дерево» Vinorit усередині.','https://market-dveri.ua/uk/dveri-strit-goryzontal-metal-antracyt-7021-farba-mdf-bile-derevo-vinorit-3k-qdoors/','Стріт Горизонталь · антрацит / біле дерево Vinorit','3 контури'),
 ('catalog-56','Стріт Елегант · антрацит / біле дерево','https://market-dveri.ua/image/catalog/product/vhidni-dveri/qdoors/211067/dveri-strit-elegant-metal-antratsit-7021-farba-mdf-bile-derevo-vinorit-3k-qdoors-main.jpg','Q Doors Стріт Елегант — вуличні вхідні двері з антрацитовим металом RAL 7021 зовні та МДФ-панеллю «біле дерево» Vinorit усередині.','https://market-dveri.ua/uk/dveri-strit-elegant-metal-antracyt-7021-farba-mdf-bile-derevo-vinorit-3k-qdoors/','Стріт Елегант · антрацит / біле дерево Vinorit','3 контури'),
 ('catalog-57','Стріт Лайт · антрацит / біла шагрень','https://market-dveri.ua/image/catalog/product/vhidni-dveri/qdoors/225073/dveri-strit-lajt-metal-antratsit-7021-farba-mdf-bila-shagren-vinorit-2k-qdoors-main.jpg','Q Doors Стріт Лайт — вуличні вхідні двері з антрацитовим металом RAL 7021 зовні та МДФ-панеллю «біла шагрень» Vinorit усередині.','https://market-dveri.ua/uk/dveri-strit-lajt-metal-antracyt-7021-farba-mdf-bila-shagren-vinorit-2k-qdoors/','Стріт Лайт · антрацит / біла шагрень Vinorit','2 контури'),
 ('catalog-58','Стріт Спейс · антрацит / біла шагрень','https://market-dveri.ua/image/catalog/product/vhidni-dveri/qdoors/225072/dveri-strit-spejs-metal-antratsit-7021-farba-mdf-bila-shagren-vinorit-3k-qdoors-main.jpg','Q Doors Стріт Спейс — вуличні вхідні двері з антрацитовим металом RAL 7021 зовні та МДФ-панеллю «біла шагрень» Vinorit усередині.','https://market-dveri.ua/uk/dveri-strit-spejs-metal-antracyt-7021-farba-mdf-bila-shagren-vinorit-3k-qdoors/','Стріт Спейс · антрацит / біла шагрень Vinorit','3 контури')
)
update public.products as product set description=source.description,image_path=source.image_path from source where product.slug=source.slug;

with source(slug,label,image_path) as (values
 ('catalog-55','Стріт Горизонталь · антрацит / біле дерево','https://market-dveri.ua/image/catalog/product/vhidni-dveri/qdoors/219206/dveri-strit-gorizontal-metal-antratsit-7021-farba-mdf-bile-derevo-vinorit-3k-qdoors-main.jpg'),('catalog-56','Стріт Елегант · антрацит / біле дерево','https://market-dveri.ua/image/catalog/product/vhidni-dveri/qdoors/211067/dveri-strit-elegant-metal-antratsit-7021-farba-mdf-bile-derevo-vinorit-3k-qdoors-main.jpg'),('catalog-57','Стріт Лайт · антрацит / біла шагрень','https://market-dveri.ua/image/catalog/product/vhidni-dveri/qdoors/225073/dveri-strit-lajt-metal-antratsit-7021-farba-mdf-bila-shagren-vinorit-2k-qdoors-main.jpg'),('catalog-58','Стріт Спейс · антрацит / біла шагрень','https://market-dveri.ua/image/catalog/product/vhidni-dveri/qdoors/225072/dveri-strit-spejs-metal-antratsit-7021-farba-mdf-bila-shagren-vinorit-3k-qdoors-main.jpg')
)
update public.product_media as media set image_path=source.image_path,label=source.label,sort_order=0,is_active=true from source where media.product_slug=source.slug and media.kind='main';

insert into public.product_specs(product_slug,label,value,sort_order) values
 ('catalog-55','Призначення','Для будинку',100),('catalog-55','Оздоблення','Метал-МДФ Vinorit',110),('catalog-55','Контури примикання','3 контури',120),
 ('catalog-56','Призначення','Для будинку',100),('catalog-56','Оздоблення','Метал-МДФ Vinorit',110),('catalog-56','Контури примикання','3 контури',120),
 ('catalog-57','Призначення','Для будинку',100),('catalog-57','Оздоблення','Метал-МДФ Vinorit',110),('catalog-57','Контури примикання','2 контури',120),
 ('catalog-58','Призначення','Для будинку',100),('catalog-58','Оздоблення','Метал-МДФ Vinorit',110),('catalog-58','Контури примикання','3 контури',120)
on conflict(product_slug,label) do update set value=excluded.value,sort_order=excluded.sort_order,is_active=true;

insert into public.product_sources(product_slug,source_name,source_url,source_product_name,verification_status,verified_at,notes) values
 ('catalog-55','Market Dveri','https://market-dveri.ua/uk/dveri-strit-goryzontal-metal-antracyt-7021-farba-mdf-bile-derevo-vinorit-3k-qdoors/','Стріт Горизонталь · антрацит / біле дерево Vinorit','verified',now(),'Модель, виконання та головне фото збігаються.'),('catalog-56','Market Dveri','https://market-dveri.ua/uk/dveri-strit-elegant-metal-antracyt-7021-farba-mdf-bile-derevo-vinorit-3k-qdoors/','Стріт Елегант · антрацит / біле дерево Vinorit','verified',now(),'Модель, виконання та головне фото збігаються.'),('catalog-57','Market Dveri','https://market-dveri.ua/uk/dveri-strit-lajt-metal-antracyt-7021-farba-mdf-bila-shagren-vinorit-2k-qdoors/','Стріт Лайт · антрацит / біла шагрень Vinorit','verified',now(),'Модель, виконання та головне фото збігаються.'),('catalog-58','Market Dveri','https://market-dveri.ua/uk/dveri-strit-spejs-metal-antracyt-7021-farba-mdf-bila-shagren-vinorit-3k-qdoors/','Стріт Спейс · антрацит / біла шагрень Vinorit','verified',now(),'Модель, виконання та головне фото збігаються.')
on conflict(product_slug,source_url) do update set source_name=excluded.source_name,source_product_name=excluded.source_product_name,verification_status=excluded.verification_status,verified_at=excluded.verified_at,notes=excluded.notes;
