-- Market Dveri — Q Doors «Квартира»: 5 точних карток моделей.
-- Перевірено 03.09.2026. Скрипт можна запускати повторно; ціни не імпортуються.

with source(slug,label,image_path,description,source_url,source_product_name,series,finish) as (values
 ('catalog-61','Бостон M · бетон темний / світлий','https://market-dveri.ua/image/catalog/product/vhidni-dveri/qdoors/22161/dveri-premium-boston-m-beton-temnij-svitlij-qdoors-main.jpg','Q Doors Бостон M — квартирні вхідні двері серії Premium у виконанні «бетон темний / бетон світлий».','https://market-dveri.ua/uk/premium-boston-m-beton-temnyy-svetlyy-22161/','Преміум Бостон M · бетон темний / світлий','Premium','Бетон темний / бетон світлий'),
 ('catalog-62','Босфор AK · 2 кольори','https://market-dveri.ua/image/catalog/product/vhidni-dveri/qdoors/28224/dveri-avangard-bosfor-ak-2-kolori-qdoors-main.jpg','Q Doors Босфор AK — квартирні вхідні двері серії Авангард у підтвердженому двоколірному виконанні.','https://market-dveri.ua/uk/dveri-avangard-bosfor-ak-2-kolory-qdoors/','Авангард Босфор AK · 2 кольори','Авангард','2 кольори'),
 ('catalog-64','Люксор · спил дерева коньячний','https://market-dveri.ua/image/catalog/product/vhidni-dveri/qdoors/23922/dveri-premium-ljuksor-spil-dereva-kon-jachnij-qdoors-main.jpg','Q Doors Люксор — квартирні вхідні двері серії Premium у декорі «спил дерева коньячний».','https://market-dveri.ua/uk/lyuksor-spil-dereva-kon-yachnyy-23922/','Преміум Люксор · спил дерева коньячний','Premium','Спил дерева коньячний'),
 ('catalog-65','Міроу · мармур темний / біла емаль / дзеркало','https://market-dveri.ua/image/catalog/product/vhidni-dveri/qdoors/28976/dveri-ultra-mirou-mramor-temnij-bila-emal-plus-dzerkalo-qdoors-main.jpg','Q Doors Міроу — квартирні вхідні двері серії Ultra у виконанні «мармур темний / біла емаль» з внутрішнім дзеркалом.','https://market-dveri.ua/uk/dveri-mirou-mramor-temnyj-bila-emal-dzerkalo-qdoors/','Ultra Міроу · мармур темний / біла емаль / дзеркало','Ultra','Мармур темний / біла емаль'),
 ('catalog-66','Стиль M · венге сірий горизонт / біле дерево','https://market-dveri.ua/image/catalog/product/vhidni-dveri/qdoors/21950/dveri-premium-stil-m-venge-sirij-gorizont-art-bile-derevo-qdoors-main.jpg','Q Doors Стиль M — квартирні вхідні двері серії Premium у виконанні «венге сірий горизонт / біле дерево».','https://market-dveri.ua/uk/stil-m-venge-seryy-gorizont-art-beloe-derevo-21950/','Premium Стиль M · венге сірий горизонт / біле дерево','Premium','Венге сірий горизонт / біле дерево')
)
update public.products as product set description=source.description,image_path=source.image_path from source where product.slug=source.slug;

with source(slug,label,image_path) as (values
 ('catalog-61','Бостон M · бетон темний / світлий','https://market-dveri.ua/image/catalog/product/vhidni-dveri/qdoors/22161/dveri-premium-boston-m-beton-temnij-svitlij-qdoors-main.jpg'),('catalog-62','Босфор AK · 2 кольори','https://market-dveri.ua/image/catalog/product/vhidni-dveri/qdoors/28224/dveri-avangard-bosfor-ak-2-kolori-qdoors-main.jpg'),('catalog-64','Люксор · спил дерева коньячний','https://market-dveri.ua/image/catalog/product/vhidni-dveri/qdoors/23922/dveri-premium-ljuksor-spil-dereva-kon-jachnij-qdoors-main.jpg'),('catalog-65','Міроу · мармур темний / біла емаль / дзеркало','https://market-dveri.ua/image/catalog/product/vhidni-dveri/qdoors/28976/dveri-ultra-mirou-mramor-temnij-bila-emal-plus-dzerkalo-qdoors-main.jpg'),('catalog-66','Стиль M · венге сірий горизонт / біле дерево','https://market-dveri.ua/image/catalog/product/vhidni-dveri/qdoors/21950/dveri-premium-stil-m-venge-sirij-gorizont-art-bile-derevo-qdoors-main.jpg')
)
update public.product_media as media set image_path=source.image_path,label=source.label,sort_order=0,is_active=true from source where media.product_slug=source.slug and media.kind='main';

insert into public.product_specs(product_slug,label,value,sort_order) values
 ('catalog-61','Призначення','Для квартири',100),('catalog-61','Серія','Premium',110),('catalog-61','Підтверджене виконання','Бетон темний / бетон світлий',120),
 ('catalog-62','Призначення','Для квартири',100),('catalog-62','Серія','Авангард',110),('catalog-62','Підтверджене виконання','2 кольори',120),
 ('catalog-64','Призначення','Для квартири',100),('catalog-64','Серія','Premium',110),('catalog-64','Підтверджене виконання','Спил дерева коньячний',120),
 ('catalog-65','Призначення','Для квартири',100),('catalog-65','Серія','Ultra',110),('catalog-65','Підтверджене виконання','Мармур темний / біла емаль / дзеркало',120),
 ('catalog-66','Призначення','Для квартири',100),('catalog-66','Серія','Premium',110),('catalog-66','Підтверджене виконання','Венге сірий горизонт / біле дерево',120)
on conflict(product_slug,label) do update set value=excluded.value,sort_order=excluded.sort_order,is_active=true;

insert into public.product_sources(product_slug,source_name,source_url,source_product_name,verification_status,verified_at,notes) values
 ('catalog-61','Market Dveri','https://market-dveri.ua/uk/premium-boston-m-beton-temnyy-svetlyy-22161/','Преміум Бостон M · бетон темний / світлий','verified',now(),'Модель, виконання та головне фото збігаються.'),('catalog-62','Market Dveri','https://market-dveri.ua/uk/dveri-avangard-bosfor-ak-2-kolory-qdoors/','Авангард Босфор AK · 2 кольори','verified',now(),'Модель, виконання та головне фото збігаються.'),('catalog-64','Market Dveri','https://market-dveri.ua/uk/lyuksor-spil-dereva-kon-yachnyy-23922/','Преміум Люксор · спил дерева коньячний','verified',now(),'Модель, виконання та головне фото збігаються.'),('catalog-65','Market Dveri','https://market-dveri.ua/uk/dveri-mirou-mramor-temnyj-bila-emal-dzerkalo-qdoors/','Ultra Міроу · мармур темний / біла емаль / дзеркало','verified',now(),'Модель, виконання та головне фото збігаються.'),('catalog-66','Market Dveri','https://market-dveri.ua/uk/stil-m-venge-seryy-gorizont-art-beloe-derevo-21950/','Premium Стиль M · венге сірий горизонт / біле дерево','verified',now(),'Модель, виконання та головне фото збігаються.')
on conflict(product_slug,source_url) do update set source_name=excluded.source_name,source_product_name=excluded.source_product_name,verification_status=excluded.verification_status,verified_at=excluded.verified_at,notes=excluded.notes;
