-- Papa Carlo Style: пакет 11–20 з 30.
begin;
insert into public.products (slug, category, brand, collection, name, material, style, color, price, description, features, image_path, sort_order, is_available) values
('papa-carlo-st-13-official', 'interior', 'Papa Carlo', 'Style', 'Papa Carlo ST-13', 'Міжкімнатні', 'Колекція Style', 'Варіанти декорів і скла', 'Ціна за запитом', 'ST-13 — міжкімнатні двері колекції Style з поліпропіленовим покриттям Renolit (Німеччина). Покриття стійке до повсякденних пошкоджень і допомагає зберігати охайний вигляд дверей. Для моделі доступні різні кольори та варіанти оздоблення. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція Style"]', 'https://papa-karlo.com.ua/content/images/2/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-13-38000453559927.jpg', '860', 'true'),
('papa-carlo-st-14-official', 'interior', 'Papa Carlo', 'Style', 'Papa Carlo ST-14', 'Міжкімнатні', 'Колекція Style', 'Варіанти декорів і скла', 'Ціна за запитом', 'ST-14 — міжкімнатні двері колекції Style з поліпропіленовим покриттям Renolit (Німеччина). Покриття стійке до повсякденних пошкоджень і допомагає зберігати охайний вигляд дверей. Для моделі доступні різні кольори та варіанти оздоблення. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція Style"]', 'https://papa-karlo.com.ua/content/images/3/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-14-52730485433033.jpg', '861', 'true'),
('papa-carlo-st-15-official', 'interior', 'Papa Carlo', 'Style', 'Papa Carlo ST-15', 'Міжкімнатні', 'Колекція Style', 'Варіанти декорів і скла', 'Ціна за запитом', 'ST-15 — міжкімнатні двері колекції Style з поліпропіленовим покриттям Renolit (Німеччина). Покриття стійке до повсякденних пошкоджень і допомагає зберігати охайний вигляд дверей. Для моделі доступні різні кольори та варіанти оздоблення. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція Style"]', 'https://papa-karlo.com.ua/content/images/4/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-15-82304091817971.jpg', '862', 'true'),
('papa-carlo-st-16-official', 'interior', 'Papa Carlo', 'Style', 'Papa Carlo ST-16', 'Міжкімнатні', 'Колекція Style', 'Варіанти декорів і скла', 'Ціна за запитом', 'ST-16 — міжкімнатні двері колекції Style з поліпропіленовим покриттям Renolit (Німеччина). Покриття стійке до повсякденних пошкоджень і допомагає зберігати охайний вигляд дверей. Для моделі доступні різні кольори та варіанти оздоблення. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція Style"]', 'https://papa-karlo.com.ua/content/images/7/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-16-44766163244662.jpg', '863', 'true'),
('papa-carlo-st-17-official', 'interior', 'Papa Carlo', 'Style', 'Papa Carlo ST-17', 'Міжкімнатні', 'Колекція Style', 'Варіанти декорів і скла', 'Ціна за запитом', 'ST-17 — міжкімнатні двері колекції Style з поліпропіленовим покриттям Renolit (Німеччина). Покриття стійке до повсякденних пошкоджень і допомагає зберігати охайний вигляд дверей. Для моделі доступні різні кольори та варіанти оздоблення. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція Style"]', 'https://papa-karlo.com.ua/content/images/8/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-17-49531377236477.jpg', '864', 'true'),
('papa-carlo-st-18-official', 'interior', 'Papa Carlo', 'Style', 'Papa Carlo ST-18', 'Міжкімнатні', 'Колекція Style', 'Варіанти декорів і скла', 'Ціна за запитом', 'ST-18 — міжкімнатні двері колекції Style з поліпропіленовим покриттям Renolit (Німеччина). Покриття стійке до повсякденних пошкоджень і допомагає зберігати охайний вигляд дверей. Для моделі доступні різні кольори та варіанти оздоблення. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція Style"]', 'https://papa-karlo.com.ua/content/images/9/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-18-50162198282709.jpg', '865', 'true'),
('papa-carlo-st-19-official', 'interior', 'Papa Carlo', 'Style', 'Papa Carlo ST-19', 'Міжкімнатні', 'Колекція Style', 'Варіанти декорів і скла', 'Ціна за запитом', 'ST-19 — міжкімнатні двері колекції Style з поліпропіленовим покриттям Renolit (Німеччина). Покриття стійке до повсякденних пошкоджень і допомагає зберігати охайний вигляд дверей. Для моделі доступні різні кольори та варіанти оздоблення. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція Style"]', 'https://papa-karlo.com.ua/content/images/10/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-19-65017975170717.jpg', '866', 'true'),
('papa-carlo-st-20-official', 'interior', 'Papa Carlo', 'Style', 'Papa Carlo ST-20', 'Міжкімнатні', 'Колекція Style', 'Варіанти декорів і скла', 'Ціна за запитом', 'ST-20 — міжкімнатні двері колекції Style з поліпропіленовим покриттям Renolit (Німеччина). Покриття стійке до повсякденних пошкоджень і допомагає зберігати охайний вигляд дверей. Для моделі доступні різні кольори та варіанти оздоблення. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція Style"]', 'https://papa-karlo.com.ua/content/images/11/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-20-94525281431596.jpg', '867', 'true'),
('papa-carlo-st-21-official', 'interior', 'Papa Carlo', 'Style', 'Papa Carlo ST-21', 'Міжкімнатні', 'Колекція Style', 'Варіанти декорів і скла', 'Ціна за запитом', 'ST-21 — міжкімнатні двері колекції Style з поліпропіленовим покриттям Renolit (Німеччина). Покриття стійке до повсякденних пошкоджень і допомагає зберігати охайний вигляд дверей. Для моделі доступні різні кольори та варіанти оздоблення. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція Style"]', 'https://papa-karlo.com.ua/content/images/12/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-21-94848496960328.jpg', '868', 'true'),
('papa-carlo-st-22-official', 'interior', 'Papa Carlo', 'Style', 'Papa Carlo ST-22', 'Міжкімнатні', 'Колекція Style', 'Варіанти декорів і скла', 'Ціна за запитом', 'ST-22 — міжкімнатні двері колекції Style з поліпропіленовим покриттям Renolit (Німеччина). Покриття стійке до повсякденних пошкоджень і допомагає зберігати охайний вигляд дверей. Для моделі доступні різні кольори та варіанти оздоблення. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція Style"]', 'https://papa-karlo.com.ua/content/images/13/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-22-39272090350028.jpg', '869', 'true')
on conflict (slug) do update set name = excluded.name, material = excluded.material, style = excluded.style, color = excluded.color, description = excluded.description, features = excluded.features, image_path = excluded.image_path, sort_order = excluded.sort_order, is_available = true;
insert into public.product_specs (product_slug, label, value, sort_order, is_active) values
('papa-carlo-st-13-official', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-st-13-official', 'Товщина полотна', '40 мм', '110', 'true'),
('papa-carlo-st-13-official', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-st-13-official', 'Стиль', 'Лофт, Модерн, Сучасний, Хай-тек', '140', 'true'),
('papa-carlo-st-13-official', 'Декор', 'Білий матовий, світло-сірий супермат, темно-сірий супермат, дуб сірий, дуб кремовий, ясен білий, бетон сірий, сірий матовий', '900', 'true'),
('papa-carlo-st-14-official', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-st-14-official', 'Товщина полотна', '40 мм', '110', 'true'),
('papa-carlo-st-14-official', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-st-14-official', 'Стиль', 'Лофт, Модерн, Сучасний, Хай-тек', '140', 'true'),
('papa-carlo-st-14-official', 'Декор', 'Білий матовий, світло-сірий супермат, темно-сірий супермат, дуб сірий, дуб кремовий, ясен білий, бетон сірий, сірий матовий', '900', 'true'),
('papa-carlo-st-15-official', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-st-15-official', 'Товщина полотна', '40 мм', '110', 'true'),
('papa-carlo-st-15-official', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-st-15-official', 'Стиль', 'Лофт, Модерн, Сучасний, Хай-тек', '140', 'true'),
('papa-carlo-st-15-official', 'Декор', 'Білий матовий, світло-сірий супермат, темно-сірий супермат, дуб сірий, дуб кремовий, ясен білий, бетон сірий, сірий матовий', '900', 'true'),
('papa-carlo-st-16-official', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-st-16-official', 'Товщина полотна', '40 мм', '110', 'true'),
('papa-carlo-st-16-official', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-st-16-official', 'Стиль', 'Лофт, Модерн, Сучасний, Хай-тек', '140', 'true'),
('papa-carlo-st-16-official', 'Декор', 'Білий матовий, світло-сірий супермат, темно-сірий супермат, дуб сірий, дуб кремовий, ясен білий, бетон сірий, сірий матовий', '900', 'true'),
('papa-carlo-st-17-official', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-st-17-official', 'Товщина полотна', '40 мм', '110', 'true'),
('papa-carlo-st-17-official', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-st-17-official', 'Стиль', 'Лофт, Модерн, Сучасний, Хай-тек', '140', 'true'),
('papa-carlo-st-17-official', 'Декор', 'Білий матовий, світло-сірий супермат, темно-сірий супермат, дуб сірий, дуб кремовий, ясен білий, бетон сірий, сірий матовий', '900', 'true'),
('papa-carlo-st-18-official', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-st-18-official', 'Товщина полотна', '40 мм', '110', 'true'),
('papa-carlo-st-18-official', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-st-18-official', 'Стиль', 'Лофт, Модерн, Сучасний, Хай-тек', '140', 'true'),
('papa-carlo-st-18-official', 'Декор', 'Білий матовий, світло-сірий супермат, темно-сірий супермат, дуб сірий, дуб кремовий, ясен білий, бетон сірий, сірий матовий', '900', 'true'),
('papa-carlo-st-19-official', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-st-19-official', 'Товщина полотна', '40 мм', '110', 'true'),
('papa-carlo-st-19-official', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-st-19-official', 'Стиль', 'Лофт, Модерн, Сучасний, Хай-тек', '140', 'true'),
('papa-carlo-st-19-official', 'Декор', 'Білий матовий, світло-сірий супермат, темно-сірий супермат, дуб сірий, дуб кремовий, ясен білий, бетон сірий, сірий матовий', '900', 'true'),
('papa-carlo-st-20-official', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-st-20-official', 'Товщина полотна', '40 мм', '110', 'true'),
('papa-carlo-st-20-official', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-st-20-official', 'Стиль', 'Лофт, Модерн, Сучасний, Хай-тек', '140', 'true'),
('papa-carlo-st-20-official', 'Декор', 'Білий матовий, світло-сірий супермат, темно-сірий супермат, дуб сірий, дуб кремовий, ясен білий, бетон сірий, сірий матовий', '900', 'true'),
('papa-carlo-st-21-official', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-st-21-official', 'Товщина полотна', '40 мм', '110', 'true'),
('papa-carlo-st-21-official', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-st-21-official', 'Стиль', 'Лофт, Модерн, Сучасний, Класика, Неокласика, Хай-тек', '140', 'true'),
('papa-carlo-st-21-official', 'Декор', 'Білий матовий, світло-сірий супермат, темно-сірий супермат, дуб сірий, дуб кремовий, ясен білий, бетон сірий, сірий матовий', '900', 'true'),
('papa-carlo-st-22-official', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-st-22-official', 'Товщина полотна', '40 мм', '110', 'true'),
('papa-carlo-st-22-official', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-st-22-official', 'Стиль', 'Класика, Прованс, Неокласика', '140', 'true'),
('papa-carlo-st-22-official', 'Декор', 'Білий матовий, світло-сірий супермат, темно-сірий супермат, дуб сірий, дуб кремовий, ясен білий, бетон сірий, сірий матовий', '900', 'true');
insert into public.product_media (product_slug, kind, label, image_path, sort_order, is_active) values
('papa-carlo-st-13-official', 'main', 'ST-13 — головне фото', 'https://papa-karlo.com.ua/content/images/2/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-13-38000453559927.jpg', '0', 'true'),
('papa-carlo-st-13-official', 'gallery', 'ST-13 — фото 2', 'https://papa-karlo.com.ua/content/images/2/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-13-42515050882766.jpg', '1', 'true'),
('papa-carlo-st-13-official', 'gallery', 'ST-13 — фото 3', 'https://papa-karlo.com.ua/content/images/2/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-13-71179893558850.jpg', '2', 'true'),
('papa-carlo-st-13-official', 'gallery', 'ST-13 — фото 4', 'https://papa-karlo.com.ua/content/images/2/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-13-31694730895604.jpg', '3', 'true'),
('papa-carlo-st-13-official', 'gallery', 'ST-13 — фото 5', 'https://papa-karlo.com.ua/content/images/2/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-13-76800152840180.jpg', '4', 'true'),
('papa-carlo-st-13-official', 'gallery', 'ST-13 — фото 6', 'https://papa-karlo.com.ua/content/images/2/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-13-86197539936407.jpg', '5', 'true'),
('papa-carlo-st-13-official', 'gallery', 'ST-13 — фото 7', 'https://papa-karlo.com.ua/content/images/2/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-13-95755526622601.jpg', '6', 'true'),
('papa-carlo-st-14-official', 'main', 'ST-14 — головне фото', 'https://papa-karlo.com.ua/content/images/3/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-14-52730485433033.jpg', '0', 'true'),
('papa-carlo-st-14-official', 'gallery', 'ST-14 — фото 2', 'https://papa-karlo.com.ua/content/images/3/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-14-94084584048811.jpg', '1', 'true'),
('papa-carlo-st-14-official', 'gallery', 'ST-14 — фото 3', 'https://papa-karlo.com.ua/content/images/3/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-14-13490880342751.jpg', '2', 'true'),
('papa-carlo-st-14-official', 'gallery', 'ST-14 — фото 4', 'https://papa-karlo.com.ua/content/images/3/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-14-42210507667140.jpg', '3', 'true'),
('papa-carlo-st-14-official', 'gallery', 'ST-14 — фото 5', 'https://papa-karlo.com.ua/content/images/3/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-14-21932211201373.jpg', '4', 'true'),
('papa-carlo-st-14-official', 'gallery', 'ST-14 — фото 6', 'https://papa-karlo.com.ua/content/images/3/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-14-60112255512680.jpg', '5', 'true'),
('papa-carlo-st-14-official', 'gallery', 'ST-14 — фото 7', 'https://papa-karlo.com.ua/content/images/3/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-14-18680290950849.jpg', '6', 'true'),
('papa-carlo-st-15-official', 'main', 'ST-15 — головне фото', 'https://papa-karlo.com.ua/content/images/4/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-15-82304091817971.jpg', '0', 'true'),
('papa-carlo-st-15-official', 'gallery', 'ST-15 — фото 2', 'https://papa-karlo.com.ua/content/images/4/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-15-23719484751902.jpg', '1', 'true'),
('papa-carlo-st-15-official', 'gallery', 'ST-15 — фото 3', 'https://papa-karlo.com.ua/content/images/4/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-15-92498888117434.jpg', '2', 'true'),
('papa-carlo-st-15-official', 'gallery', 'ST-15 — фото 4', 'https://papa-karlo.com.ua/content/images/4/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-15-69672080693571.jpg', '3', 'true'),
('papa-carlo-st-15-official', 'gallery', 'ST-15 — фото 5', 'https://papa-karlo.com.ua/content/images/4/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-15-51911556635741.jpg', '4', 'true'),
('papa-carlo-st-15-official', 'gallery', 'ST-15 — фото 6', 'https://papa-karlo.com.ua/content/images/4/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-15-61423177956786.jpg', '5', 'true'),
('papa-carlo-st-15-official', 'gallery', 'ST-15 — фото 7', 'https://papa-karlo.com.ua/content/images/4/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-15-81682090031529.jpg', '6', 'true'),
('papa-carlo-st-16-official', 'main', 'ST-16 — головне фото', 'https://papa-karlo.com.ua/content/images/7/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-16-44766163244662.jpg', '0', 'true'),
('papa-carlo-st-16-official', 'gallery', 'ST-16 — фото 2', 'https://papa-karlo.com.ua/content/images/7/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-16-78604774262854.jpg', '1', 'true'),
('papa-carlo-st-16-official', 'gallery', 'ST-16 — фото 3', 'https://papa-karlo.com.ua/content/images/7/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-16-32605843744803.jpg', '2', 'true'),
('papa-carlo-st-16-official', 'gallery', 'ST-16 — фото 4', 'https://papa-karlo.com.ua/content/images/7/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-16-45318216394946.jpg', '3', 'true'),
('papa-carlo-st-16-official', 'gallery', 'ST-16 — фото 5', 'https://papa-karlo.com.ua/content/images/7/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-16-24569335060969.jpg', '4', 'true'),
('papa-carlo-st-17-official', 'main', 'ST-17 — головне фото', 'https://papa-karlo.com.ua/content/images/8/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-17-49531377236477.jpg', '0', 'true'),
('papa-carlo-st-17-official', 'gallery', 'ST-17 — фото 2', 'https://papa-karlo.com.ua/content/images/8/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-17-38634446508240.jpg', '1', 'true'),
('papa-carlo-st-17-official', 'gallery', 'ST-17 — фото 3', 'https://papa-karlo.com.ua/content/images/8/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-17-33819010416351.jpg', '2', 'true'),
('papa-carlo-st-17-official', 'gallery', 'ST-17 — фото 4', 'https://papa-karlo.com.ua/content/images/8/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-17-24281032330356.jpg', '3', 'true'),
('papa-carlo-st-17-official', 'gallery', 'ST-17 — фото 5', 'https://papa-karlo.com.ua/content/images/8/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-17-39907836652122.jpg', '4', 'true'),
('papa-carlo-st-18-official', 'main', 'ST-18 — головне фото', 'https://papa-karlo.com.ua/content/images/9/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-18-50162198282709.jpg', '0', 'true'),
('papa-carlo-st-18-official', 'gallery', 'ST-18 — фото 2', 'https://papa-karlo.com.ua/content/images/9/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-18-62247541968813.jpg', '1', 'true'),
('papa-carlo-st-18-official', 'gallery', 'ST-18 — фото 3', 'https://papa-karlo.com.ua/content/images/9/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-18-38265089389415.jpg', '2', 'true'),
('papa-carlo-st-18-official', 'gallery', 'ST-18 — фото 4', 'https://papa-karlo.com.ua/content/images/9/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-18-40627626473385.jpg', '3', 'true'),
('papa-carlo-st-18-official', 'gallery', 'ST-18 — фото 5', 'https://papa-karlo.com.ua/content/images/9/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-18-26022008175977.jpg', '4', 'true'),
('papa-carlo-st-19-official', 'main', 'ST-19 — головне фото', 'https://papa-karlo.com.ua/content/images/10/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-19-65017975170717.jpg', '0', 'true'),
('papa-carlo-st-19-official', 'gallery', 'ST-19 — фото 2', 'https://papa-karlo.com.ua/content/images/10/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-19-70037994161998.jpg', '1', 'true'),
('papa-carlo-st-19-official', 'gallery', 'ST-19 — фото 3', 'https://papa-karlo.com.ua/content/images/10/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-19-23585020964237.jpg', '2', 'true'),
('papa-carlo-st-19-official', 'gallery', 'ST-19 — фото 4', 'https://papa-karlo.com.ua/content/images/10/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-19-35258525893374.jpg', '3', 'true'),
('papa-carlo-st-19-official', 'gallery', 'ST-19 — фото 5', 'https://papa-karlo.com.ua/content/images/10/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-19-86195582438998.jpg', '4', 'true'),
('papa-carlo-st-20-official', 'main', 'ST-20 — головне фото', 'https://papa-karlo.com.ua/content/images/11/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-20-94525281431596.jpg', '0', 'true'),
('papa-carlo-st-20-official', 'gallery', 'ST-20 — фото 2', 'https://papa-karlo.com.ua/content/images/11/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-20-70232471689204.jpg', '1', 'true'),
('papa-carlo-st-20-official', 'gallery', 'ST-20 — фото 3', 'https://papa-karlo.com.ua/content/images/11/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-20-50261773299547.jpg', '2', 'true'),
('papa-carlo-st-20-official', 'gallery', 'ST-20 — фото 4', 'https://papa-karlo.com.ua/content/images/11/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-20-88976977788461.jpg', '3', 'true'),
('papa-carlo-st-20-official', 'gallery', 'ST-20 — фото 5', 'https://papa-karlo.com.ua/content/images/11/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-20-78913486505584.jpg', '4', 'true'),
('papa-carlo-st-21-official', 'main', 'ST-21 — головне фото', 'https://papa-karlo.com.ua/content/images/12/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-21-94848496960328.jpg', '0', 'true'),
('papa-carlo-st-21-official', 'gallery', 'ST-21 — фото 2', 'https://papa-karlo.com.ua/content/images/12/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-21-52296380121882.jpg', '1', 'true'),
('papa-carlo-st-21-official', 'gallery', 'ST-21 — фото 3', 'https://papa-karlo.com.ua/content/images/12/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-21-98974394666048.jpg', '2', 'true'),
('papa-carlo-st-21-official', 'gallery', 'ST-21 — фото 4', 'https://papa-karlo.com.ua/content/images/12/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-21-53486706663706.jpg', '3', 'true'),
('papa-carlo-st-21-official', 'gallery', 'ST-21 — фото 5', 'https://papa-karlo.com.ua/content/images/12/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-21-90168956121426.jpg', '4', 'true'),
('papa-carlo-st-22-official', 'main', 'ST-22 — головне фото', 'https://papa-karlo.com.ua/content/images/13/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-22-39272090350028.jpg', '0', 'true'),
('papa-carlo-st-22-official', 'gallery', 'ST-22 — фото 2', 'https://papa-karlo.com.ua/content/images/13/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-22-50773936373404.jpg', '1', 'true'),
('papa-carlo-st-22-official', 'gallery', 'ST-22 — фото 3', 'https://papa-karlo.com.ua/content/images/13/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-22-78526112640601.jpg', '2', 'true'),
('papa-carlo-st-22-official', 'gallery', 'ST-22 — фото 4', 'https://papa-karlo.com.ua/content/images/13/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-22-94572911826081.jpg', '3', 'true'),
('papa-carlo-st-22-official', 'gallery', 'ST-22 — фото 5', 'https://papa-karlo.com.ua/content/images/13/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-22-14994282029055.jpg', '4', 'true')
on conflict (product_slug, kind, image_path) do update set label = excluded.label, sort_order = excluded.sort_order, is_active = true;
insert into public.product_sources (product_slug, source_name, source_url, source_product_name, verification_status, verified_at, notes) values
('papa-carlo-st-13-official', 'Papa Carlo', 'https://papa-karlo.com.ua/mizhkimnatni-dveri-papa-karlo-st-13', 'Міжкімнатні двері Папа Карло ST-13 - Ламіновані', 'verified', now(), 'Офіційна картка Papa Carlo: фото, галерея, декори й базові технічні параметри.'),
('papa-carlo-st-14-official', 'Papa Carlo', 'https://papa-karlo.com.ua/mizhkimnatni-dveri-papa-karlo-st-14', 'Міжкімнатні двері Папа Карло ST-14 - Ламіновані', 'verified', now(), 'Офіційна картка Papa Carlo: фото, галерея, декори й базові технічні параметри.'),
('papa-carlo-st-15-official', 'Papa Carlo', 'https://papa-karlo.com.ua/mizhkimnatni-dveri-papa-karlo-st-15', 'Міжкімнатні двері Папа Карло ST-15 - Ламіновані', 'verified', now(), 'Офіційна картка Papa Carlo: фото, галерея, декори й базові технічні параметри.'),
('papa-carlo-st-16-official', 'Papa Carlo', 'https://papa-karlo.com.ua/mizhkimnatni-dveri-papa-karlo-st-16', 'Міжкімнатні двері Папа Карло ST-16 - Ламіновані', 'verified', now(), 'Офіційна картка Papa Carlo: фото, галерея, декори й базові технічні параметри.'),
('papa-carlo-st-17-official', 'Papa Carlo', 'https://papa-karlo.com.ua/mizhkimnatni-dveri-papa-karlo-st-17', 'Міжкімнатні двері Папа Карло ST-17 - Ламіновані', 'verified', now(), 'Офіційна картка Papa Carlo: фото, галерея, декори й базові технічні параметри.'),
('papa-carlo-st-18-official', 'Papa Carlo', 'https://papa-karlo.com.ua/mizhkimnatni-dveri-papa-karlo-st-18', 'Міжкімнатні двері Папа Карло ST-18 - Ламіновані', 'verified', now(), 'Офіційна картка Papa Carlo: фото, галерея, декори й базові технічні параметри.'),
('papa-carlo-st-19-official', 'Papa Carlo', 'https://papa-karlo.com.ua/mizhkimnatni-dveri-papa-karlo-st-19', 'Міжкімнатні двері Папа Карло ST-19 - Ламіновані', 'verified', now(), 'Офіційна картка Papa Carlo: фото, галерея, декори й базові технічні параметри.'),
('papa-carlo-st-20-official', 'Papa Carlo', 'https://papa-karlo.com.ua/mizhkimnatni-dveri-papa-karlo-st-20', 'Міжкімнатні двері Папа Карло ST-20 - Ламіновані', 'verified', now(), 'Офіційна картка Papa Carlo: фото, галерея, декори й базові технічні параметри.'),
('papa-carlo-st-21-official', 'Papa Carlo', 'https://papa-karlo.com.ua/mizhkimnatni-dveri-papa-karlo-st-21', 'Міжкімнатні двері Папа Карло ST-21 - Ламіновані', 'verified', now(), 'Офіційна картка Papa Carlo: фото, галерея, декори й базові технічні параметри.'),
('papa-carlo-st-22-official', 'Papa Carlo', 'https://papa-karlo.com.ua/mizhkimnatni-dveri-papa-karlo-st-22', 'Міжкімнатні двері Папа Карло ST-22 - Ламіновані', 'verified', now(), 'Офіційна картка Papa Carlo: фото, галерея, декори й базові технічні параметри.')
on conflict (product_slug, source_url) do update set source_product_name = excluded.source_product_name, verification_status = 'verified', verified_at = now(), notes = excluded.notes;
commit;
