-- Papa Carlo Style: пакет 21–30 з 30.
begin;
insert into public.products (slug, category, brand, collection, name, material, style, color, price, description, features, image_path, sort_order, is_available) values
('papa-carlo-st-23-official', 'interior', 'Papa Carlo', 'Style', 'Papa Carlo ST-23', 'Міжкімнатні', 'Колекція Style', 'Варіанти декорів і скла', 'Ціна за запитом', 'ST-23 — міжкімнатні двері колекції Style з поліпропіленовим покриттям Renolit (Німеччина). Покриття стійке до повсякденних пошкоджень і допомагає зберігати охайний вигляд дверей. Для моделі доступні різні кольори та варіанти оздоблення. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція Style"]', 'https://papa-karlo.com.ua/content/images/14/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-23-88137771554103.jpg', '870', 'true'),
('papa-carlo-st-24-official', 'interior', 'Papa Carlo', 'Style', 'Papa Carlo ST-24', 'Міжкімнатні', 'Колекція Style', 'Варіанти декорів і скла', 'Ціна за запитом', 'ST-24 — міжкімнатні двері колекції Style з поліпропіленовим покриттям Renolit (Німеччина). Покриття стійке до повсякденних пошкоджень і допомагає зберігати охайний вигляд дверей. Для моделі доступні різні кольори та варіанти оздоблення. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція Style"]', 'https://papa-karlo.com.ua/content/images/15/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-24-29813570602103.jpg', '871', 'true'),
('papa-carlo-st-25-official', 'interior', 'Papa Carlo', 'Style', 'Papa Carlo ST-25', 'Міжкімнатні', 'Колекція Style', 'Варіанти декорів і скла', 'Ціна за запитом', 'ST-25 — міжкімнатні двері колекції Style з поліпропіленовим покриттям Renolit (Німеччина). Покриття стійке до повсякденних пошкоджень і допомагає зберігати охайний вигляд дверей. Для моделі доступні різні кольори та варіанти оздоблення. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція Style"]', 'https://papa-karlo.com.ua/content/images/16/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-25-74342627912442.jpg', '872', 'true'),
('papa-carlo-st-26-official', 'interior', 'Papa Carlo', 'Style', 'Papa Carlo ST-26', 'Міжкімнатні', 'Колекція Style', 'Варіанти декорів і скла', 'Ціна за запитом', 'ST-26 — міжкімнатні двері колекції Style з поліпропіленовим покриттям Renolit (Німеччина). Покриття стійке до повсякденних пошкоджень і допомагає зберігати охайний вигляд дверей. Для моделі доступні різні кольори та варіанти оздоблення. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція Style"]', 'https://papa-karlo.com.ua/content/images/17/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-26-95408199426896.jpg', '873', 'true'),
('papa-carlo-st-27-official', 'interior', 'Papa Carlo', 'Style', 'Papa Carlo ST-27', 'Міжкімнатні', 'Колекція Style', 'Варіанти декорів і скла', 'Ціна за запитом', 'ST-27 — міжкімнатні двері колекції Style з поліпропіленовим покриттям Renolit (Німеччина). Покриття стійке до повсякденних пошкоджень і допомагає зберігати охайний вигляд дверей. Для моделі доступні різні кольори та варіанти оздоблення. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція Style"]', 'https://papa-karlo.com.ua/content/images/18/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-27-56020296862250.jpg', '874', 'true'),
('papa-carlo-st-28-official', 'interior', 'Papa Carlo', 'Style', 'Papa Carlo ST-28', 'Міжкімнатні', 'Колекція Style', 'Варіанти декорів і скла', 'Ціна за запитом', 'ST-28 — міжкімнатні двері колекції Style з поліпропіленовим покриттям Renolit (Німеччина). Покриття стійке до повсякденних пошкоджень і допомагає зберігати охайний вигляд дверей. Для моделі доступні різні кольори та варіанти оздоблення. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція Style"]', 'https://papa-karlo.com.ua/content/images/19/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-28-87069437891516.jpg', '875', 'true'),
('papa-carlo-st-29-official', 'interior', 'Papa Carlo', 'Style', 'Papa Carlo ST-29', 'Міжкімнатні', 'Колекція Style', 'Варіанти декорів і скла', 'Ціна за запитом', 'ST-29 — міжкімнатні двері колекції Style з поліпропіленовим покриттям Renolit (Німеччина). Покриття стійке до повсякденних пошкоджень і допомагає зберігати охайний вигляд дверей. Для моделі доступні різні кольори та варіанти оздоблення. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція Style"]', 'https://papa-karlo.com.ua/content/images/20/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-29-31790368651356.jpg', '876', 'true'),
('papa-carlo-st-30-official', 'interior', 'Papa Carlo', 'Style', 'Papa Carlo ST-30', 'Міжкімнатні', 'Колекція Style', 'Варіанти декорів і скла', 'Ціна за запитом', 'ST-30 — міжкімнатні двері колекції Style з поліпропіленовим покриттям Renolit (Німеччина). Покриття стійке до повсякденних пошкоджень і допомагає зберігати охайний вигляд дверей. Для моделі доступні різні кольори та варіанти оздоблення. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція Style"]', 'https://papa-karlo.com.ua/content/images/21/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-30-69965482109530.jpg', '877', 'true'),
('papa-carlo-st-31-official', 'interior', 'Papa Carlo', 'Style', 'Papa Carlo ST-31', 'Міжкімнатні', 'Колекція Style', 'Варіанти декорів і скла', 'Ціна за запитом', 'ST-31 — міжкімнатні двері колекції Style з поліпропіленовим покриттям Renolit (Німеччина). Покриття стійке до повсякденних пошкоджень і допомагає зберігати охайний вигляд дверей. Для моделі доступні різні кольори та варіанти оздоблення. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція Style"]', 'https://papa-karlo.com.ua/content/images/22/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-31-48061187404287.jpg', '878', 'true'),
('papa-carlo-st-32-official', 'interior', 'Papa Carlo', 'Style', 'Papa Carlo ST-32', 'Міжкімнатні', 'Колекція Style', 'Варіанти декорів і скла', 'Ціна за запитом', 'ST-32 — міжкімнатні двері колекції Style з поліпропіленовим покриттям Renolit (Німеччина). Покриття стійке до повсякденних пошкоджень і допомагає зберігати охайний вигляд дверей. Для моделі доступні різні кольори та варіанти оздоблення. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція Style"]', 'https://papa-karlo.com.ua/content/images/23/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-32-22709631246729.jpg', '879', 'true')
on conflict (slug) do update set name = excluded.name, material = excluded.material, style = excluded.style, color = excluded.color, description = excluded.description, features = excluded.features, image_path = excluded.image_path, sort_order = excluded.sort_order, is_available = true;
insert into public.product_specs (product_slug, label, value, sort_order, is_active) values
('papa-carlo-st-23-official', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-st-23-official', 'Товщина полотна', '40 мм', '110', 'true'),
('papa-carlo-st-23-official', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-st-23-official', 'Стиль', 'Класика, Прованс, Неокласика', '140', 'true'),
('papa-carlo-st-23-official', 'Декор', 'Білий матовий, світло-сірий супермат, темно-сірий супермат, дуб сірий, дуб кремовий, ясен білий, бетон сірий, сірий матовий', '900', 'true'),
('papa-carlo-st-24-official', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-st-24-official', 'Товщина полотна', '40 мм', '110', 'true'),
('papa-carlo-st-24-official', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-st-24-official', 'Стиль', 'Класика, Прованс, Неокласика', '140', 'true'),
('papa-carlo-st-24-official', 'Декор', 'Білий матовий, світло-сірий супермат, темно-сірий супермат, дуб сірий, дуб кремовий, ясен білий, бетон сірий, сірий матовий', '900', 'true'),
('papa-carlo-st-25-official', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-st-25-official', 'Товщина полотна', '40 мм', '110', 'true'),
('papa-carlo-st-25-official', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-st-25-official', 'Стиль', 'Лофт, Модерн, Сучасний, Класика, Неокласика, Хай-тек', '140', 'true'),
('papa-carlo-st-25-official', 'Декор', 'Білий матовий, світло-сірий супермат, темно-сірий супермат, дуб сірий, дуб кремовий, ясен білий, бетон сірий, сірий матовий', '900', 'true'),
('papa-carlo-st-26-official', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-st-26-official', 'Товщина полотна', '40 мм', '110', 'true'),
('papa-carlo-st-26-official', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-st-26-official', 'Стиль', 'Класика, Прованс, Неокласика', '140', 'true'),
('papa-carlo-st-26-official', 'Декор', 'Білий матовий, світло-сірий супермат, темно-сірий супермат, дуб сірий, дуб кремовий, ясен білий, бетон сірий, сірий матовий', '900', 'true'),
('papa-carlo-st-27-official', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-st-27-official', 'Товщина полотна', '40 мм', '110', 'true'),
('papa-carlo-st-27-official', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-st-27-official', 'Стиль', 'Класика, Прованс, Неокласика', '140', 'true'),
('papa-carlo-st-27-official', 'Декор', 'Білий матовий, світло-сірий супермат, темно-сірий супермат, дуб сірий, дуб кремовий, ясен білий, бетон сірий, сірий матовий', '900', 'true'),
('papa-carlo-st-28-official', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-st-28-official', 'Товщина полотна', '40 мм', '110', 'true'),
('papa-carlo-st-28-official', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-st-28-official', 'Стиль', 'Класика, Прованс, Неокласика', '140', 'true'),
('papa-carlo-st-28-official', 'Декор', 'Білий матовий, світло-сірий супермат, темно-сірий супермат, дуб сірий, дуб кремовий, ясен білий, бетон сірий, сірий матовий', '900', 'true'),
('papa-carlo-st-29-official', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-st-29-official', 'Товщина полотна', '40 мм', '110', 'true'),
('papa-carlo-st-29-official', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-st-29-official', 'Стиль', 'Лофт, Модерн, Сучасний, Класика, Неокласика, Хай-тек', '140', 'true'),
('papa-carlo-st-29-official', 'Декор', 'Білий матовий, світло-сірий супермат, темно-сірий супермат, дуб сірий, дуб кремовий, ясен білий, бетон сірий, сірий матовий', '900', 'true'),
('papa-carlo-st-30-official', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-st-30-official', 'Товщина полотна', '40 мм', '110', 'true'),
('papa-carlo-st-30-official', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-st-30-official', 'Стиль', 'Класика, Прованс, Неокласика', '140', 'true'),
('papa-carlo-st-30-official', 'Декор', 'Білий матовий, світло-сірий супермат, темно-сірий супермат, дуб сірий, дуб кремовий, ясен білий, бетон сірий, сірий матовий', '900', 'true'),
('papa-carlo-st-31-official', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-st-31-official', 'Товщина полотна', '40 мм', '110', 'true'),
('papa-carlo-st-31-official', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-st-31-official', 'Стиль', 'Класика, Прованс, Неокласика', '140', 'true'),
('papa-carlo-st-31-official', 'Декор', 'Білий матовий, світло-сірий супермат, темно-сірий супермат, дуб сірий, дуб кремовий, ясен білий, бетон сірий, сірий матовий', '900', 'true'),
('papa-carlo-st-32-official', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-st-32-official', 'Товщина полотна', '40 мм', '110', 'true'),
('papa-carlo-st-32-official', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-st-32-official', 'Стиль', 'Класика, Прованс, Неокласика', '140', 'true'),
('papa-carlo-st-32-official', 'Декор', 'Білий матовий, світло-сірий супермат, темно-сірий супермат, дуб сірий, дуб кремовий, ясен білий, бетон сірий, сірий матовий', '900', 'true');
insert into public.product_media (product_slug, kind, label, image_path, sort_order, is_active) values
('papa-carlo-st-23-official', 'main', 'ST-23 — головне фото', 'https://papa-karlo.com.ua/content/images/14/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-23-88137771554103.jpg', '0', 'true'),
('papa-carlo-st-23-official', 'gallery', 'ST-23 — фото 2', 'https://papa-karlo.com.ua/content/images/14/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-23-97062950082346.jpg', '1', 'true'),
('papa-carlo-st-23-official', 'gallery', 'ST-23 — фото 3', 'https://papa-karlo.com.ua/content/images/14/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-23-54459455824812.jpg', '2', 'true'),
('papa-carlo-st-23-official', 'gallery', 'ST-23 — фото 4', 'https://papa-karlo.com.ua/content/images/14/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-23-65140011126890.jpg', '3', 'true'),
('papa-carlo-st-23-official', 'gallery', 'ST-23 — фото 5', 'https://papa-karlo.com.ua/content/images/14/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-23-99345667191233.jpg', '4', 'true'),
('papa-carlo-st-24-official', 'main', 'ST-24 — головне фото', 'https://papa-karlo.com.ua/content/images/15/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-24-29813570602103.jpg', '0', 'true'),
('papa-carlo-st-24-official', 'gallery', 'ST-24 — фото 2', 'https://papa-karlo.com.ua/content/images/15/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-24-59593179971236.jpg', '1', 'true'),
('papa-carlo-st-24-official', 'gallery', 'ST-24 — фото 3', 'https://papa-karlo.com.ua/content/images/15/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-24-64495197927813.jpg', '2', 'true'),
('papa-carlo-st-24-official', 'gallery', 'ST-24 — фото 4', 'https://papa-karlo.com.ua/content/images/15/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-24-69732132080597.jpg', '3', 'true'),
('papa-carlo-st-24-official', 'gallery', 'ST-24 — фото 5', 'https://papa-karlo.com.ua/content/images/15/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-24-72654427836899.jpg', '4', 'true'),
('papa-carlo-st-25-official', 'main', 'ST-25 — головне фото', 'https://papa-karlo.com.ua/content/images/16/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-25-74342627912442.jpg', '0', 'true'),
('papa-carlo-st-25-official', 'gallery', 'ST-25 — фото 2', 'https://papa-karlo.com.ua/content/images/16/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-25-67688736431241.jpg', '1', 'true'),
('papa-carlo-st-25-official', 'gallery', 'ST-25 — фото 3', 'https://papa-karlo.com.ua/content/images/16/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-25-12998880500978.jpg', '2', 'true'),
('papa-carlo-st-25-official', 'gallery', 'ST-25 — фото 4', 'https://papa-karlo.com.ua/content/images/16/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-25-50827632467982.jpg', '3', 'true'),
('papa-carlo-st-25-official', 'gallery', 'ST-25 — фото 5', 'https://papa-karlo.com.ua/content/images/16/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-25-94357037585022.jpg', '4', 'true'),
('papa-carlo-st-26-official', 'main', 'ST-26 — головне фото', 'https://papa-karlo.com.ua/content/images/17/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-26-95408199426896.jpg', '0', 'true'),
('papa-carlo-st-26-official', 'gallery', 'ST-26 — фото 2', 'https://papa-karlo.com.ua/content/images/17/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-26-32384894984338.jpg', '1', 'true'),
('papa-carlo-st-26-official', 'gallery', 'ST-26 — фото 3', 'https://papa-karlo.com.ua/content/images/17/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-26-60725601193858.jpg', '2', 'true'),
('papa-carlo-st-26-official', 'gallery', 'ST-26 — фото 4', 'https://papa-karlo.com.ua/content/images/17/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-26-87899106232753.jpg', '3', 'true'),
('papa-carlo-st-26-official', 'gallery', 'ST-26 — фото 5', 'https://papa-karlo.com.ua/content/images/17/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-26-66840278656400.jpg', '4', 'true'),
('papa-carlo-st-27-official', 'main', 'ST-27 — головне фото', 'https://papa-karlo.com.ua/content/images/18/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-27-56020296862250.jpg', '0', 'true'),
('papa-carlo-st-27-official', 'gallery', 'ST-27 — фото 2', 'https://papa-karlo.com.ua/content/images/18/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-27-36760086673709.jpg', '1', 'true'),
('papa-carlo-st-27-official', 'gallery', 'ST-27 — фото 3', 'https://papa-karlo.com.ua/content/images/18/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-27-13330474103429.jpg', '2', 'true'),
('papa-carlo-st-27-official', 'gallery', 'ST-27 — фото 4', 'https://papa-karlo.com.ua/content/images/18/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-27-30940067583615.jpg', '3', 'true'),
('papa-carlo-st-27-official', 'gallery', 'ST-27 — фото 5', 'https://papa-karlo.com.ua/content/images/18/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-27-77343490027286.jpg', '4', 'true'),
('papa-carlo-st-28-official', 'main', 'ST-28 — головне фото', 'https://papa-karlo.com.ua/content/images/19/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-28-87069437891516.jpg', '0', 'true'),
('papa-carlo-st-28-official', 'gallery', 'ST-28 — фото 2', 'https://papa-karlo.com.ua/content/images/19/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-28-66770874669488.jpg', '1', 'true'),
('papa-carlo-st-28-official', 'gallery', 'ST-28 — фото 3', 'https://papa-karlo.com.ua/content/images/19/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-28-43979792758177.jpg', '2', 'true'),
('papa-carlo-st-28-official', 'gallery', 'ST-28 — фото 4', 'https://papa-karlo.com.ua/content/images/19/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-28-84519949656838.jpg', '3', 'true'),
('papa-carlo-st-28-official', 'gallery', 'ST-28 — фото 5', 'https://papa-karlo.com.ua/content/images/19/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-28-79124452263597.jpg', '4', 'true'),
('papa-carlo-st-29-official', 'main', 'ST-29 — головне фото', 'https://papa-karlo.com.ua/content/images/20/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-29-31790368651356.jpg', '0', 'true'),
('papa-carlo-st-29-official', 'gallery', 'ST-29 — фото 2', 'https://papa-karlo.com.ua/content/images/20/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-29-62138515868242.jpg', '1', 'true'),
('papa-carlo-st-29-official', 'gallery', 'ST-29 — фото 3', 'https://papa-karlo.com.ua/content/images/20/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-29-94778763182268.jpg', '2', 'true'),
('papa-carlo-st-29-official', 'gallery', 'ST-29 — фото 4', 'https://papa-karlo.com.ua/content/images/20/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-29-78818865124664.jpg', '3', 'true'),
('papa-carlo-st-29-official', 'gallery', 'ST-29 — фото 5', 'https://papa-karlo.com.ua/content/images/20/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-29-88110298786706.jpg', '4', 'true'),
('papa-carlo-st-30-official', 'main', 'ST-30 — головне фото', 'https://papa-karlo.com.ua/content/images/21/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-30-69965482109530.jpg', '0', 'true'),
('papa-carlo-st-30-official', 'gallery', 'ST-30 — фото 2', 'https://papa-karlo.com.ua/content/images/21/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-30-49741859195127.jpg', '1', 'true'),
('papa-carlo-st-30-official', 'gallery', 'ST-30 — фото 3', 'https://papa-karlo.com.ua/content/images/21/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-30-14111955105948.jpg', '2', 'true'),
('papa-carlo-st-30-official', 'gallery', 'ST-30 — фото 4', 'https://papa-karlo.com.ua/content/images/21/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-30-26497866378648.jpg', '3', 'true'),
('papa-carlo-st-30-official', 'gallery', 'ST-30 — фото 5', 'https://papa-karlo.com.ua/content/images/21/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-30-70771563126239.jpg', '4', 'true'),
('papa-carlo-st-31-official', 'main', 'ST-31 — головне фото', 'https://papa-karlo.com.ua/content/images/22/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-31-48061187404287.jpg', '0', 'true'),
('papa-carlo-st-31-official', 'gallery', 'ST-31 — фото 2', 'https://papa-karlo.com.ua/content/images/22/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-31-49653791565851.jpg', '1', 'true'),
('papa-carlo-st-31-official', 'gallery', 'ST-31 — фото 3', 'https://papa-karlo.com.ua/content/images/22/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-31-53097331370561.jpg', '2', 'true'),
('papa-carlo-st-31-official', 'gallery', 'ST-31 — фото 4', 'https://papa-karlo.com.ua/content/images/22/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-31-61415799732921.jpg', '3', 'true'),
('papa-carlo-st-31-official', 'gallery', 'ST-31 — фото 5', 'https://papa-karlo.com.ua/content/images/22/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-31-23799373573570.jpg', '4', 'true'),
('papa-carlo-st-32-official', 'main', 'ST-32 — головне фото', 'https://papa-karlo.com.ua/content/images/23/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-32-22709631246729.jpg', '0', 'true'),
('papa-carlo-st-32-official', 'gallery', 'ST-32 — фото 2', 'https://papa-karlo.com.ua/content/images/23/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-32-14618271570380.jpg', '1', 'true'),
('papa-carlo-st-32-official', 'gallery', 'ST-32 — фото 3', 'https://papa-karlo.com.ua/content/images/23/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-32-44763473044040.jpg', '2', 'true'),
('papa-carlo-st-32-official', 'gallery', 'ST-32 — фото 4', 'https://papa-karlo.com.ua/content/images/23/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-32-88963161614685.jpg', '3', 'true'),
('papa-carlo-st-32-official', 'gallery', 'ST-32 — фото 5', 'https://papa-karlo.com.ua/content/images/23/420x940l80mc0/mizhkimnatni-dveri-papa-karlo-st-32-99977543179218.jpg', '4', 'true')
on conflict (product_slug, kind, image_path) do update set label = excluded.label, sort_order = excluded.sort_order, is_active = true;
insert into public.product_sources (product_slug, source_name, source_url, source_product_name, verification_status, verified_at, notes) values
('papa-carlo-st-23-official', 'Papa Carlo', 'https://papa-karlo.com.ua/mizhkimnatni-dveri-papa-karlo-st-23', 'Міжкімнатні двері Папа Карло ST-23 - Ламіновані', 'verified', now(), 'Офіційна картка Papa Carlo: фото, галерея, декори й базові технічні параметри.'),
('papa-carlo-st-24-official', 'Papa Carlo', 'https://papa-karlo.com.ua/mizhkimnatni-dveri-papa-karlo-st-24', 'Міжкімнатні двері Папа Карло ST-24 - Ламіновані', 'verified', now(), 'Офіційна картка Papa Carlo: фото, галерея, декори й базові технічні параметри.'),
('papa-carlo-st-25-official', 'Papa Carlo', 'https://papa-karlo.com.ua/mizhkimnatni-dveri-papa-karlo-st-25', 'Міжкімнатні двері Папа Карло ST-25 - Ламіновані', 'verified', now(), 'Офіційна картка Papa Carlo: фото, галерея, декори й базові технічні параметри.'),
('papa-carlo-st-26-official', 'Papa Carlo', 'https://papa-karlo.com.ua/mizhkimnatni-dveri-papa-karlo-st-26', 'Міжкімнатні двері Папа Карло ST-26 - Ламіновані', 'verified', now(), 'Офіційна картка Papa Carlo: фото, галерея, декори й базові технічні параметри.'),
('papa-carlo-st-27-official', 'Papa Carlo', 'https://papa-karlo.com.ua/mizhkimnatni-dveri-papa-karlo-st-27', 'Міжкімнатні двері Папа Карло ST-27 - Ламіновані', 'verified', now(), 'Офіційна картка Papa Carlo: фото, галерея, декори й базові технічні параметри.'),
('papa-carlo-st-28-official', 'Papa Carlo', 'https://papa-karlo.com.ua/mizhkimnatni-dveri-papa-karlo-st-28', 'Міжкімнатні двері Папа Карло ST-28 - Ламіновані', 'verified', now(), 'Офіційна картка Papa Carlo: фото, галерея, декори й базові технічні параметри.'),
('papa-carlo-st-29-official', 'Papa Carlo', 'https://papa-karlo.com.ua/mizhkimnatni-dveri-papa-karlo-st-29', 'Міжкімнатні двері Папа Карло ST-29 - Ламіновані', 'verified', now(), 'Офіційна картка Papa Carlo: фото, галерея, декори й базові технічні параметри.'),
('papa-carlo-st-30-official', 'Papa Carlo', 'https://papa-karlo.com.ua/mizhkimnatni-dveri-papa-karlo-st-30', 'Міжкімнатні двері Папа Карло ST-30 - Ламіновані', 'verified', now(), 'Офіційна картка Papa Carlo: фото, галерея, декори й базові технічні параметри.'),
('papa-carlo-st-31-official', 'Papa Carlo', 'https://papa-karlo.com.ua/mizhkimnatni-dveri-papa-karlo-st-31', 'Міжкімнатні двері Папа Карло ST-31 - Ламіновані', 'verified', now(), 'Офіційна картка Papa Carlo: фото, галерея, декори й базові технічні параметри.'),
('papa-carlo-st-32-official', 'Papa Carlo', 'https://papa-karlo.com.ua/mizhkimnatni-dveri-papa-karlo-st-32', 'Міжкімнатні двері Папа Карло ST-32 - Ламіновані', 'verified', now(), 'Офіційна картка Papa Carlo: фото, галерея, декори й базові технічні параметри.')
on conflict (product_slug, source_url) do update set source_product_name = excluded.source_product_name, verification_status = 'verified', verified_at = now(), notes = excluded.notes;
commit;
