-- Офіційний імпорт Papa Carlo / iDoors: 4 моделі.
begin;
insert into public.products (slug, category, brand, collection, name, material, style, color, price, description, features, image_path, sort_order, is_available) values
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-zovnishnie-vidkryttia', 'interior', 'Papa Carlo', 'iDoors', 'Papa Carlo Prime-AL(С) Зовнішнє відкриття', 'Міжкімнатні', 'Прихований монтаж', 'Варіанти виконання', 'Ціна за запитом', 'Papa Carlo Prime-AL(С) Зовнішнє відкриття — приховані міжкімнатні двері: глуха модель, для зовнішнього відкривання. Алюмінієвий прихований короб і поліпропіленове покриття Renolit (Німеччина) допомагають створити лаконічний інтер''єр. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція iDoors"]', 'https://papa-karlo.com.ua/content/images/5/869x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-als-zovnishnie-vidkryttia-99119444288435.jpg', '950', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-zovnishnie-vidkryttia', 'interior', 'Papa Carlo', 'iDoors', 'Papa Carlo Prime-AL(Ч) Зовнішнє відкриття', 'Міжкімнатні', 'Прихований монтаж', 'Варіанти виконання', 'Ціна за запитом', 'Papa Carlo Prime-AL(Ч) Зовнішнє відкриття — приховані міжкімнатні двері: зі склом, для зовнішнього відкривання. Алюмінієвий прихований короб і поліпропіленове покриття Renolit (Німеччина) допомагають створити лаконічний інтер''єр. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція iDoors"]', 'https://papa-karlo.com.ua/content/images/6/905x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-zovnishnie-vidkryttia-50030160003184.jpg', '951', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-inside-vnutrishnie-vidkryttia', 'interior', 'Papa Carlo', 'iDoors', 'Papa Carlo Prime-AL(С) Inside Внутрішнє відкриття', 'Міжкімнатні', 'Прихований монтаж', 'Варіанти виконання', 'Ціна за запитом', 'Papa Carlo Prime-AL(С) Inside Внутрішнє відкриття — приховані міжкімнатні двері: глуха модель, для внутрішнього відкривання. Алюмінієвий прихований короб і поліпропіленове покриття Renolit (Німеччина) допомагають створити лаконічний інтер''єр. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція iDoors"]', 'https://papa-karlo.com.ua/content/images/7/898x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-als-inside-vnutrishnie-vidkryttia-84788290053328.jpg', '952', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-inside-vnutrishnie-vidkryttia', 'interior', 'Papa Carlo', 'iDoors', 'Papa Carlo Prime-AL(Ч) Inside Внутрішнє відкриття', 'Міжкімнатні', 'Прихований монтаж', 'Варіанти виконання', 'Ціна за запитом', 'Papa Carlo Prime-AL(Ч) Inside Внутрішнє відкриття — приховані міжкімнатні двері: зі склом, для внутрішнього відкривання. Алюмінієвий прихований короб і поліпропіленове покриття Renolit (Німеччина) допомагають створити лаконічний інтер''єр. Актуальну комплектацію й ціну уточнюйте у менеджера.', '["Фабрика Papa Carlo","Колекція iDoors"]', 'https://papa-karlo.com.ua/content/images/8/884x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-inside-vnutrishnie-vidkryttia-85857638231771.jpg', '953', 'true')
on conflict (slug) do update set name = excluded.name, material = excluded.material, style = excluded.style, color = excluded.color, description = excluded.description, features = excluded.features, image_path = excluded.image_path, sort_order = excluded.sort_order, is_available = true;
insert into public.product_specs (product_slug, label, value, sort_order, is_active) values
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-zovnishnie-vidkryttia', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-zovnishnie-vidkryttia', 'Товщина полотна', '42 мм', '110', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-zovnishnie-vidkryttia', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-zovnishnie-vidkryttia', 'Каркас', 'Клеєний масив хвойних порід, 10см', '130', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-zovnishnie-vidkryttia', 'Внутрішнє наповнення', 'Сотовий наповнювач + МДФ плита 6мм', '140', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-zovnishnie-vidkryttia', 'Шумоізоляція', 'Висока', '150', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-zovnishnie-vidkryttia', 'Гарантія виробника', '5 років', '900', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-zovnishnie-vidkryttia', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2000 мм', '100', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-zovnishnie-vidkryttia', 'Товщина полотна', '42 мм', '110', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-zovnishnie-vidkryttia', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-zovnishnie-vidkryttia', 'Каркас', 'Клеєний масив хвойних порід, 10см', '130', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-zovnishnie-vidkryttia', 'Внутрішнє наповнення', 'Сотовий наповнювач + МДФ плита 8мм', '140', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-zovnishnie-vidkryttia', 'Шумоізоляція', 'Висока', '150', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-zovnishnie-vidkryttia', 'Гарантія виробника', '5 років', '900', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-inside-vnutrishnie-vidkryttia', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2012 мм', '100', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-inside-vnutrishnie-vidkryttia', 'Товщина полотна', '46 мм', '110', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-inside-vnutrishnie-vidkryttia', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-inside-vnutrishnie-vidkryttia', 'Каркас', 'Клеєний масив хвойних порід, 10см', '130', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-inside-vnutrishnie-vidkryttia', 'Внутрішнє наповнення', 'Сотовий наповнювач + МДФ плита 8мм', '140', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-inside-vnutrishnie-vidkryttia', 'Шумоізоляція', 'Висока', '150', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-inside-vnutrishnie-vidkryttia', 'Гарантія виробника', '5 років', '900', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-inside-vnutrishnie-vidkryttia', 'Розміри полотна', 'ширина: 710 мм, 810 мм, 610 мм, 910 мм; висота: Будь-який (під замовлення), 2012 мм', '100', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-inside-vnutrishnie-vidkryttia', 'Товщина полотна', '46 мм', '110', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-inside-vnutrishnie-vidkryttia', 'Матеріал покриття', 'Поліпропіленова плівка Renolit (Німеччина)', '120', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-inside-vnutrishnie-vidkryttia', 'Каркас', 'Клеєний масив хвойних порід, 10см', '130', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-inside-vnutrishnie-vidkryttia', 'Внутрішнє наповнення', 'Сотовий наповнювач + МДФ плита 8мм', '140', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-inside-vnutrishnie-vidkryttia', 'Шумоізоляція', 'Висока', '150', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-inside-vnutrishnie-vidkryttia', 'Гарантія виробника', '5 років', '900', 'true');
insert into public.product_media (product_slug, kind, label, image_path, sort_order, is_active) values
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-zovnishnie-vidkryttia', 'main', 'Papa Carlo Prime-AL(С) Зовнішнє відкриття — головне фото', 'https://papa-karlo.com.ua/content/images/5/869x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-als-zovnishnie-vidkryttia-99119444288435.jpg', '0', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-zovnishnie-vidkryttia', 'gallery', 'Papa Carlo Prime-AL(С) Зовнішнє відкриття — фото 2', 'https://papa-karlo.com.ua/content/images/5/869x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-als-zovnishnie-vidkryttia-51711965290897.jpg', '1', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-zovnishnie-vidkryttia', 'gallery', 'Papa Carlo Prime-AL(С) Зовнішнє відкриття — фото 3', 'https://papa-karlo.com.ua/content/images/5/869x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-als-zovnishnie-vidkryttia-80484686372200.jpg', '2', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-zovnishnie-vidkryttia', 'gallery', 'Papa Carlo Prime-AL(С) Зовнішнє відкриття — фото 4', 'https://papa-karlo.com.ua/content/images/5/869x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-als-zovnishnie-vidkryttia-67031901044225.jpg', '3', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-zovnishnie-vidkryttia', 'gallery', 'Papa Carlo Prime-AL(С) Зовнішнє відкриття — фото 5', 'https://papa-karlo.com.ua/content/images/5/869x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-als-zovnishnie-vidkryttia-50534466008184.jpg', '4', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-zovnishnie-vidkryttia', 'main', 'Papa Carlo Prime-AL(Ч) Зовнішнє відкриття — головне фото', 'https://papa-karlo.com.ua/content/images/6/905x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-zovnishnie-vidkryttia-50030160003184.jpg', '0', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-zovnishnie-vidkryttia', 'gallery', 'Papa Carlo Prime-AL(Ч) Зовнішнє відкриття — фото 2', 'https://papa-karlo.com.ua/content/images/6/905x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-zovnishnie-vidkryttia-30640215367133.jpg', '1', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-zovnishnie-vidkryttia', 'gallery', 'Papa Carlo Prime-AL(Ч) Зовнішнє відкриття — фото 3', 'https://papa-karlo.com.ua/content/images/6/905x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-zovnishnie-vidkryttia-58881647326369.jpg', '2', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-zovnishnie-vidkryttia', 'gallery', 'Papa Carlo Prime-AL(Ч) Зовнішнє відкриття — фото 4', 'https://papa-karlo.com.ua/content/images/6/905x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-zovnishnie-vidkryttia-44480114134482.jpg', '3', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-zovnishnie-vidkryttia', 'gallery', 'Papa Carlo Prime-AL(Ч) Зовнішнє відкриття — фото 5', 'https://papa-karlo.com.ua/content/images/6/905x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-zovnishnie-vidkryttia-42501973177711.jpg', '4', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-inside-vnutrishnie-vidkryttia', 'main', 'Papa Carlo Prime-AL(С) Inside Внутрішнє відкриття — головне фото', 'https://papa-karlo.com.ua/content/images/7/898x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-als-inside-vnutrishnie-vidkryttia-84788290053328.jpg', '0', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-inside-vnutrishnie-vidkryttia', 'gallery', 'Papa Carlo Prime-AL(С) Inside Внутрішнє відкриття — фото 2', 'https://papa-karlo.com.ua/content/images/7/898x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-als-inside-vnutrishnie-vidkryttia-98209980723569.jpg', '1', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-inside-vnutrishnie-vidkryttia', 'gallery', 'Papa Carlo Prime-AL(С) Inside Внутрішнє відкриття — фото 3', 'https://papa-karlo.com.ua/content/images/7/898x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-als-inside-vnutrishnie-vidkryttia-57269863854425.jpg', '2', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-inside-vnutrishnie-vidkryttia', 'gallery', 'Papa Carlo Prime-AL(С) Inside Внутрішнє відкриття — фото 4', 'https://papa-karlo.com.ua/content/images/7/898x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-als-inside-vnutrishnie-vidkryttia-87580131031771.jpg', '3', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-inside-vnutrishnie-vidkryttia', 'gallery', 'Papa Carlo Prime-AL(С) Inside Внутрішнє відкриття — фото 5', 'https://papa-karlo.com.ua/content/images/7/898x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-als-inside-vnutrishnie-vidkryttia-51728252892321.jpg', '4', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-inside-vnutrishnie-vidkryttia', 'main', 'Papa Carlo Prime-AL(Ч) Inside Внутрішнє відкриття — головне фото', 'https://papa-karlo.com.ua/content/images/8/884x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-inside-vnutrishnie-vidkryttia-85857638231771.jpg', '0', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-inside-vnutrishnie-vidkryttia', 'gallery', 'Papa Carlo Prime-AL(Ч) Inside Внутрішнє відкриття — фото 2', 'https://papa-karlo.com.ua/content/images/8/884x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-inside-vnutrishnie-vidkryttia-82949427392524.jpg', '1', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-inside-vnutrishnie-vidkryttia', 'gallery', 'Papa Carlo Prime-AL(Ч) Inside Внутрішнє відкриття — фото 3', 'https://papa-karlo.com.ua/content/images/8/884x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-inside-vnutrishnie-vidkryttia-49586653780029.jpg', '2', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-inside-vnutrishnie-vidkryttia', 'gallery', 'Papa Carlo Prime-AL(Ч) Inside Внутрішнє відкриття — фото 4', 'https://papa-karlo.com.ua/content/images/8/884x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-inside-vnutrishnie-vidkryttia-61326068170614.jpg', '3', 'true'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-inside-vnutrishnie-vidkryttia', 'gallery', 'Papa Carlo Prime-AL(Ч) Inside Внутрішнє відкриття — фото 5', 'https://papa-karlo.com.ua/content/images/8/884x1800l80mc0/dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-inside-vnutrishnie-vidkryttia-77925763927650.jpg', '4', 'true')
on conflict (product_slug, kind, image_path) do update set label = excluded.label, sort_order = excluded.sort_order, is_active = true;
insert into public.product_sources (product_slug, source_name, source_url, source_product_name, verification_status, verified_at, notes) values
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-zovnishnie-vidkryttia', 'Papa Carlo', 'https://papa-karlo.com.ua/dveri-prykhovanoho-montazhu-papa-karlo-prime-als-zovnishnie-vidkryttia', 'Двері прихованого монтажу Папа Карло Prime-AL(С) Зовнішнє відкриття - Двері прихованого монтажу iDoors', 'verified', now(), 'Офіційна картка Papa Carlo: фото та технічні параметри iDoors.'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-zovnishnie-vidkryttia', 'Papa Carlo', 'https://papa-karlo.com.ua/dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-zovnishnie-vidkryttia', 'Двері прихованого монтажу Папа Карло Prime-AL(Ч) Зовнішнє відкриття - Двері прихованого монтажу iDoors', 'verified', now(), 'Офіційна картка Papa Carlo: фото та технічні параметри iDoors.'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-als-inside-vnutrishnie-vidkryttia', 'Papa Carlo', 'https://papa-karlo.com.ua/dveri-prykhovanoho-montazhu-papa-karlo-prime-als-inside-vnutrishnie-vidkryttia', 'Двері прихованого монтажу Папа Карло Prime-AL(С) Inside Внутрішнє відкриття - Двері прихованого монтажу iDoors', 'verified', now(), 'Офіційна картка Papa Carlo: фото та технічні параметри iDoors.'),
('papa-carlo-idoors-dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-inside-vnutrishnie-vidkryttia', 'Papa Carlo', 'https://papa-karlo.com.ua/dveri-prykhovanoho-montazhu-papa-karlo-prime-alch-inside-vnutrishnie-vidkryttia', 'Двері прихованого монтажу Папа Карло Prime-AL(Ч) Inside Внутрішнє відкриття - Двері прихованого монтажу iDoors', 'verified', now(), 'Офіційна картка Papa Carlo: фото та технічні параметри iDoors.')
on conflict (product_slug, source_url) do update set source_product_name = excluded.source_product_name, verification_status = 'verified', verified_at = now(), notes = excluded.notes;
commit;
