-- Автоматично сформовано з архіву «Сайт НД.zip».
-- Спершу завантажте папку «Сайт НД» (лише папки з фото, без DOCX) у bucket catalog-images, зберігши структуру папок.
-- Один виняток: файл Loft Surf Шпон.jpg є палітрою RAL, тому не призначений головним фото.

insert into public.product_media (product_slug, kind, label, image_path, sort_order)
values
  ('catalog-149', 'main', 'Т-04', 'Сайт НД/Папа Карло/Склад/Т-04.jpg', 0),
  ('catalog-150', 'main', 'Т-12', 'Сайт НД/Папа Карло/Склад/Т-12.jpg', 0),
  ('catalog-151', 'main', 'Т-14', 'Сайт НД/Папа Карло/Склад/Т-14.jpg', 0),
  ('catalog-138', 'main', 'ML-62c', 'Сайт НД/Папа Карло/Склад/ML-62c.jpg', 0),
  ('catalog-139', 'main', 'PLATO-01', 'Сайт НД/Папа Карло/Склад/PLATO-01.jpg', 0),
  ('catalog-140', 'main', 'PLATO-04', 'Сайт НД/Папа Карло/Склад/PLATO-04.jpg', 0),
  ('catalog-141', 'main', 'PLATO-07', 'Сайт НД/Папа Карло/Склад/PLATO-07.jpg', 0),
  ('catalog-142', 'main', 'PLATO-21', 'Сайт НД/Папа Карло/Склад/PLATO-21.jpg', 0),
  ('catalog-143', 'main', 'PLATO-24', 'Сайт НД/Папа Карло/Склад/PLATO-24.jpg', 0),
  ('catalog-144', 'main', 'Prime-AL INSIDE(С)', 'Сайт НД/Папа Карло/Склад/Prime-AL INSIDE(С).jpg', 0),
  ('catalog-145', 'main', 'Prime-AL(С)', 'Сайт НД/Папа Карло/Склад/Prime-AL(С).jpg', 0),
  ('catalog-146', 'main', 'T-01', 'Сайт НД/Папа Карло/Склад/T-01.jpg', 0),
  ('catalog-147', 'main', 'T-02', 'Сайт НД/Папа Карло/Склад/T-02.jpg', 0),
  ('catalog-148', 'main', 'T-03', 'Сайт НД/Папа Карло/Склад/T-03.jpg', 0),
  ('catalog-85', 'main', 'ML-00', 'Сайт НД/Папа Карло/Milenium/ML-00.jpg', 0),
  ('catalog-86', 'main', 'ML-00F', 'Сайт НД/Папа Карло/Milenium/ML-00F.jpg', 0),
  ('catalog-87', 'main', 'ML-01', 'Сайт НД/Папа Карло/Milenium/ML-01.jpg', 0),
  ('catalog-88', 'main', 'ML-02', 'Сайт НД/Папа Карло/Milenium/ML-02.jpg', 0),
  ('catalog-89', 'main', 'ML-06', 'Сайт НД/Папа Карло/Milenium/ML-06.jpg', 0),
  ('catalog-90', 'main', 'ML-08', 'Сайт НД/Папа Карло/Milenium/ML-08.jpg', 0),
  ('catalog-91', 'main', 'ML-10', 'Сайт НД/Папа Карло/Milenium/ML-10.jpg', 0),
  ('catalog-92', 'main', 'ML-11', 'Сайт НД/Папа Карло/Milenium/ML-11.jpg', 0),
  ('catalog-93', 'main', 'ML-12', 'Сайт НД/Папа Карло/Milenium/ML-12.jpg', 0),
  ('catalog-94', 'main', 'ML-14', 'Сайт НД/Папа Карло/Milenium/ML-14.jpg', 0),
  ('catalog-95', 'main', 'ML-16', 'Сайт НД/Папа Карло/Milenium/ML-16.jpg', 0),
  ('catalog-96', 'main', 'ML-20', 'Сайт НД/Папа Карло/Milenium/ML-20.jpg', 0),
  ('catalog-97', 'main', 'ML-36', 'Сайт НД/Папа Карло/Milenium/ML-36.jpg', 0),
  ('catalog-98', 'main', 'ML-62', 'Сайт НД/Папа Карло/Milenium/ML-62.jpg', 0),
  ('catalog-99', 'main', 'ML-64', 'Сайт НД/Папа Карло/Milenium/ML-64.jpg', 0),
  ('catalog-100', 'main', 'ML-714', 'Сайт НД/Папа Карло/Milenium/ML-714.jpg', 0),
  ('catalog-101', 'main', 'ML-718', 'Сайт НД/Папа Карло/Milenium/ML-718.jpg', 0),
  ('catalog-102', 'main', 'PL-01', 'Сайт НД/Папа Карло/Plato/PL-01.jpg', 0),
  ('catalog-103', 'main', 'PL-02', 'Сайт НД/Папа Карло/Plato/PL-02.jpg', 0),
  ('catalog-104', 'main', 'PL-04', 'Сайт НД/Папа Карло/Plato/PL-04.jpg', 0),
  ('catalog-105', 'main', 'PL-06', 'Сайт НД/Папа Карло/Plato/PL-06.jpg', 0),
  ('catalog-106', 'main', 'PL-07', 'Сайт НД/Папа Карло/Plato/PL-07.jpg', 0),
  ('catalog-107', 'main', 'PL-14', 'Сайт НД/Папа Карло/Plato/PL-14.jpg', 0),
  ('catalog-108', 'main', 'PL-22', 'Сайт НД/Папа Карло/Plato/PL-22.jpg', 0),
  ('catalog-109', 'main', 'PL-30', 'Сайт НД/Папа Карло/Plato/PL-30.jpg', 0),
  ('catalog-110', 'main', 'PL-32', 'Сайт НД/Папа Карло/Plato/PL-32.jpg', 0),
  ('catalog-111', 'main', 'ST-01', 'Сайт НД/Папа Карло/Style/ST-01.jpg', 0),
  ('catalog-112', 'main', 'ST-02', 'Сайт НД/Папа Карло/Style/ST-02.jpg', 0),
  ('catalog-113', 'main', 'ST-04', 'Сайт НД/Папа Карло/Style/ST-04.jpg', 0),
  ('catalog-114', 'main', 'ST-25', 'Сайт НД/Папа Карло/Style/ST-25.jpg', 0),
  ('catalog-115', 'main', 'ST-26', 'Сайт НД/Папа Карло/Style/ST-26.jpg', 0),
  ('catalog-116', 'main', 'ST-33', 'Сайт НД/Папа Карло/Style/ST-33.jpg', 0),
  ('catalog-117', 'main', 'ST-34', 'Сайт НД/Папа Карло/Style/ST-34.jpg', 0),
  ('catalog-118', 'main', 'ST-35', 'Сайт НД/Папа Карло/Style/ST-35.jpg', 0),
  ('catalog-132', 'main', 'Т-00F', 'Сайт НД/Папа Карло/Tetra/Т-00F.jpg', 0),
  ('catalog-133', 'main', 'Т-01', 'Сайт НД/Папа Карло/Tetra/Т-01.jpg', 0),
  ('catalog-134', 'main', 'Т-02', 'Сайт НД/Папа Карло/Tetra/Т-02.jpg', 0),
  ('catalog-135', 'main', 'Т-03', 'Сайт НД/Папа Карло/Tetra/Т-03.jpg', 0),
  ('catalog-136', 'main', 'Т-12', 'Сайт НД/Папа Карло/Tetra/Т-12.jpg', 0),
  ('catalog-137', 'main', 'Т-18 (BLK)', 'Сайт НД/Папа Карло/Tetra/Т-18 (BLK).jpg', 0),
  ('catalog-119', 'main', 'T-04', 'Сайт НД/Папа Карло/Tetra/T-04.jpg', 0),
  ('catalog-120', 'main', 'T-05', 'Сайт НД/Папа Карло/Tetra/T-05.jpg', 0),
  ('catalog-121', 'main', 'T-06', 'Сайт НД/Папа Карло/Tetra/T-06.jpg', 0),
  ('catalog-122', 'main', 'T-07', 'Сайт НД/Папа Карло/Tetra/T-07.jpg', 0),
  ('catalog-123', 'main', 'T-08', 'Сайт НД/Папа Карло/Tetra/T-08.jpg', 0),
  ('catalog-124', 'main', 'T-09', 'Сайт НД/Папа Карло/Tetra/T-09.jpg', 0),
  ('catalog-125', 'main', 'T-10', 'Сайт НД/Папа Карло/Tetra/T-10.jpg', 0),
  ('catalog-126', 'main', 'T-11 (BLK)', 'Сайт НД/Папа Карло/Tetra/T-11 (BLK).jpg', 0),
  ('catalog-127', 'main', 'T-13', 'Сайт НД/Папа Карло/Tetra/T-13.jpg', 0),
  ('catalog-128', 'main', 'T-14', 'Сайт НД/Папа Карло/Tetra/T-14.jpg', 0),
  ('catalog-129', 'main', 'T-15', 'Сайт НД/Папа Карло/Tetra/T-15.jpg', 0),
  ('catalog-130', 'main', 'T-16', 'Сайт НД/Папа Карло/Tetra/T-16.jpg', 0),
  ('catalog-131', 'main', 'T-17', 'Сайт НД/Папа Карло/Tetra/T-17.jpg', 0),
  ('catalog-152', 'main', 'F 120', 'Сайт НД/Родос вхідні/Вулиця/F 120.jpg', 0),
  ('catalog-153', 'main', 'F 124', 'Сайт НД/Родос вхідні/Вулиця/F 124.jpg', 0),
  ('catalog-154', 'main', 'F 130', 'Сайт НД/Родос вхідні/Вулиця/F 130.jpg', 0),
  ('catalog-155', 'main', 'F 131', 'Сайт НД/Родос вхідні/Вулиця/F 131.jpg', 0),
  ('catalog-156', 'main', 'F 135', 'Сайт НД/Родос вхідні/Вулиця/F 135.jpg', 0),
  ('catalog-157', 'main', 'F 145', 'Сайт НД/Родос вхідні/Вулиця/F 145.jpg', 0),
  ('catalog-158', 'main', 'F 147', 'Сайт НД/Родос вхідні/Вулиця/F 147.jpg', 0),
  ('catalog-159', 'main', 'F 150', 'Сайт НД/Родос вхідні/Вулиця/F 150.jpg', 0),
  ('catalog-160', 'main', 'F 160', 'Сайт НД/Родос вхідні/Вулиця/F 160.jpg', 0),
  ('catalog-161', 'main', 'F 163', 'Сайт НД/Родос вхідні/Вулиця/F 163.jpg', 0),
  ('catalog-162', 'main', 'F 167', 'Сайт НД/Родос вхідні/Вулиця/F 167.jpg', 0),
  ('catalog-163', 'main', 'F 106', 'Сайт НД/Родос вхідні/Квартира/F 106.jpg', 0),
  ('catalog-164', 'main', 'F 108', 'Сайт НД/Родос вхідні/Квартира/F 108.jpg', 0),
  ('catalog-165', 'main', 'F 110', 'Сайт НД/Родос вхідні/Квартира/F 110.jpg', 0),
  ('catalog-166', 'main', 'F 113', 'Сайт НД/Родос вхідні/Квартира/F 113.jpg', 0),
  ('catalog-167', 'main', 'F 115', 'Сайт НД/Родос вхідні/Квартира/F 115.jpg', 0),
  ('catalog-168', 'main', 'F 116', 'Сайт НД/Родос вхідні/Квартира/F 116.jpg', 0),
  ('catalog-169', 'main', 'F 120', 'Сайт НД/Родос вхідні/Квартира/F 120.jpg', 0),
  ('catalog-170', 'main', 'F 121', 'Сайт НД/Родос вхідні/Квартира/F 121.jpg', 0),
  ('catalog-171', 'main', 'F 122', 'Сайт НД/Родос вхідні/Квартира/F 122.jpg', 0),
  ('catalog-172', 'main', 'F 124', 'Сайт НД/Родос вхідні/Квартира/F 124.jpg', 0),
  ('catalog-173', 'main', 'F 125', 'Сайт НД/Родос вхідні/Квартира/F 125.jpg', 0),
  ('catalog-174', 'main', 'F 132', 'Сайт НД/Родос вхідні/Квартира/F 132.jpg', 0),
  ('catalog-175', 'main', 'F 136', 'Сайт НД/Родос вхідні/Квартира/F 136.jpg', 0),
  ('catalog-176', 'main', 'F 141', 'Сайт НД/Родос вхідні/Квартира/F 141.jpg', 0),
  ('catalog-177', 'main', 'F 154', 'Сайт НД/Родос вхідні/Квартира/F 154.jpg', 0),
  ('catalog-178', 'main', 'F 155', 'Сайт НД/Родос вхідні/Квартира/F 155.jpg', 0),
  ('catalog-179', 'main', 'F 159', 'Сайт НД/Родос вхідні/Квартира/F 159.jpg', 0),
  ('catalog-180', 'main', 'Atlantic 001  скло', 'Сайт НД/Родос між/Atlantic ПВХ/Atlantic 001  скло.jpg', 0),
  ('catalog-181', 'main', 'Atlantic 001 глухе', 'Сайт НД/Родос між/Atlantic ПВХ/Atlantic 001 глухе.jpg', 0),
  ('catalog-182', 'main', 'Atlantic 002 глухе', 'Сайт НД/Родос між/Atlantic ПВХ/Atlantic 002 глухе.jpg', 0),
  ('catalog-183', 'main', 'Atlantic 002 напівскло', 'Сайт НД/Родос між/Atlantic ПВХ/Atlantic 002 напівскло.jpg', 0),
  ('catalog-184', 'main', 'Atlantic 002 скло', 'Сайт НД/Родос між/Atlantic ПВХ/Atlantic 002 скло.jpg', 0),
  ('catalog-185', 'main', 'Atlantic 003 глухе', 'Сайт НД/Родос між/Atlantic ПВХ/Atlantic 003 глухе.jpg', 0),
  ('catalog-186', 'main', 'Atlantic 003 напівскло', 'Сайт НД/Родос між/Atlantic ПВХ/Atlantic 003 напівскло.jpg', 0),
  ('catalog-187', 'main', 'Atlantic 004 глухе', 'Сайт НД/Родос між/Atlantic ПВХ/Atlantic 004 глухе.jpg', 0),
  ('catalog-188', 'main', 'Atlantic 004 напівскло', 'Сайт НД/Родос між/Atlantic ПВХ/Atlantic 004 напівскло.jpg', 0),
  ('catalog-189', 'main', 'Atlantic 004 скло', 'Сайт НД/Родос між/Atlantic ПВХ/Atlantic 004 скло.jpg', 0),
  ('catalog-190', 'main', 'Atlantic 005 глухе', 'Сайт НД/Родос між/Atlantic ПВХ/Atlantic 005 глухе.jpg', 0),
  ('catalog-191', 'main', 'Atlantic 005 скло', 'Сайт НД/Родос між/Atlantic ПВХ/Atlantic 005 скло.jpg', 0),
  ('catalog-192', 'main', 'Atlantic 006 глухе', 'Сайт НД/Родос між/Atlantic ПВХ/Atlantic 006 глухе.jpg', 0),
  ('catalog-193', 'main', 'Atlantic 006 скло', 'Сайт НД/Родос між/Atlantic ПВХ/Atlantic 006 скло.jpg', 0),
  ('catalog-194', 'main', 'Cortes Dolce-3', 'Сайт НД/Родос між/Cortes фарба/Cortes Dolce-3.jpg', 0),
  ('catalog-195', 'main', 'Cortes Dolce-4', 'Сайт НД/Родос між/Cortes фарба/Cortes Dolce-4.jpg', 0),
  ('catalog-196', 'main', 'Cortes Dolce', 'Сайт НД/Родос між/Cortes фарба/Cortes Dolce.jpg', 0),
  ('catalog-197', 'main', 'Cortes Galant глухе', 'Сайт НД/Родос між/Cortes фарба/Cortes Galant глухе.jpg', 0),
  ('catalog-198', 'main', 'Cortes Galant напівскло', 'Сайт НД/Родос між/Cortes фарба/Cortes Galant напівскло.jpg', 0),
  ('catalog-199', 'main', 'Cortes Galant скло', 'Сайт НД/Родос між/Cortes фарба/Cortes Galant скло.jpg', 0),
  ('catalog-200', 'main', 'Cortes Galliano', 'Сайт НД/Родос між/Cortes фарба/Cortes Galliano.jpg', 0),
  ('catalog-201', 'main', 'Cortes Gaudi', 'Сайт НД/Родос між/Cortes фарба/Cortes Gaudi.jpg', 0),
  ('catalog-202', 'main', 'Cortes Jazz', 'Сайт НД/Родос між/Cortes фарба/Cortes Jazz.jpg', 0),
  ('catalog-203', 'main', 'Cortes Prima 1G', 'Сайт НД/Родос між/Cortes фарба/Cortes Prima 1G.jpg', 0),
  ('catalog-204', 'main', 'Cortes Prima 3G', 'Сайт НД/Родос між/Cortes фарба/Cortes Prima 3G.jpg', 0),
  ('catalog-205', 'main', 'Cortes Prima 3V', 'Сайт НД/Родос між/Cortes фарба/Cortes Prima 3V.jpg', 0),
  ('catalog-206', 'main', 'Cortes Prima 3V1', 'Сайт НД/Родос між/Cortes фарба/Cortes Prima 3V1.jpg', 0),
  ('catalog-207', 'main', 'Cortes Prima глухе', 'Сайт НД/Родос між/Cortes фарба/Cortes Prima глухе.jpg', 0),
  ('catalog-208', 'main', 'Cortes Prima напівскло', 'Сайт НД/Родос між/Cortes фарба/Cortes Prima напівскло.jpg', 0),
  ('catalog-209', 'main', 'Cortes Prima скло', 'Сайт НД/Родос між/Cortes фарба/Cortes Prima скло.jpg', 0),
  ('catalog-210', 'main', 'Cortes Roma', 'Сайт НД/Родос між/Cortes фарба/Cortes Roma.jpg', 0),
  ('catalog-211', 'main', 'Cortes Salsa', 'Сайт НД/Родос між/Cortes фарба/Cortes Salsa.jpg', 0),
  ('catalog-212', 'main', 'Cortes Selena', 'Сайт НД/Родос між/Cortes фарба/Cortes Selena.jpg', 0),
  ('catalog-213', 'main', 'Cortes Tango', 'Сайт НД/Родос між/Cortes фарба/Cortes Tango.jpg', 0),
  ('catalog-214', 'main', 'Cortes Venezia глухе', 'Сайт НД/Родос між/Cortes фарба/Cortes Venezia глухе.jpg', 0),
  ('catalog-215', 'main', 'Cortes Venezia напівскло', 'Сайт НД/Родос між/Cortes фарба/Cortes Venezia напівскло.jpg', 0),
  ('catalog-216', 'main', 'Loft Arrigo', 'Сайт НД/Родос між/Loft фарба/Loft Arrigo.jpg', 0),
  ('catalog-217', 'main', 'Loft Arte', 'Сайт НД/Родос між/Loft фарба/Loft Arte.jpg', 0),
  ('catalog-218', 'main', 'Loft Aura', 'Сайт НД/Родос між/Loft фарба/Loft Aura.jpg', 0),
  ('catalog-219', 'main', 'Loft Berta G', 'Сайт НД/Родос між/Loft фарба/Loft Berta G.jpg', 0),
  ('catalog-220', 'main', 'Loft Berta GL', 'Сайт НД/Родос між/Loft фарба/Loft Berta GL.jpg', 0),
  ('catalog-221', 'main', 'Loft Berta GW', 'Сайт НД/Родос між/Loft фарба/Loft Berta GW.jpg', 0),
  ('catalog-222', 'main', 'Loft Berta V', 'Сайт НД/Родос між/Loft фарба/Loft Berta V.jpg', 0),
  ('catalog-223', 'main', 'Loft Berta V1', 'Сайт НД/Родос між/Loft фарба/Loft Berta V1.jpg', 0),
  ('catalog-224', 'main', 'Loft Cosmo', 'Сайт НД/Родос між/Loft фарба/Loft Cosmo.jpg', 0),
  ('catalog-225', 'main', 'Loft Lago 1', 'Сайт НД/Родос між/Loft фарба/Loft Lago 1.jpg', 0),
  ('catalog-226', 'main', 'Loft Lago 2', 'Сайт НД/Родос між/Loft фарба/Loft Lago 2.jpg', 0),
  ('catalog-227', 'main', 'Loft Lago 3', 'Сайт НД/Родос між/Loft фарба/Loft Lago 3.jpg', 0),
  ('catalog-228', 'main', 'Loft Nikoletta', 'Сайт НД/Родос між/Loft фарба/Loft Nikoletta.jpg', 0),
  ('catalog-229', 'main', 'Loft Olimpia 2', 'Сайт НД/Родос між/Loft фарба/Loft Olimpia 2.jpg', 0),
  ('catalog-230', 'main', 'Loft Olimpia 3', 'Сайт НД/Родос між/Loft фарба/Loft Olimpia 3.jpg', 0),
  ('catalog-231', 'main', 'Loft Olimpia', 'Сайт НД/Родос між/Loft фарба/Loft Olimpia.jpg', 0),
  ('catalog-232', 'main', 'Loft Porto 2', 'Сайт НД/Родос між/Loft фарба/Loft Porto 2.jpg', 0),
  ('catalog-233', 'main', 'Loft Porto 3', 'Сайт НД/Родос між/Loft фарба/Loft Porto 3.jpg', 0),
  ('catalog-234', 'main', 'Loft Porto', 'Сайт НД/Родос між/Loft фарба/Loft Porto.png', 0),
  ('catalog-235', 'main', 'Loft Wave G', 'Сайт НД/Родос між/Loft фарба/Loft Wave G.jpg', 0),
  ('catalog-236', 'main', 'Loft Wave V', 'Сайт НД/Родос між/Loft фарба/Loft Wave V.jpg', 0),
  ('catalog-237', 'palette', 'Палітра RAL', 'Сайт НД/Родос між/Loft шпон/Loft Surf Шпон.jpg', 0),
  ('catalog-238', 'main', 'Avalon Шпон скло', 'Сайт НД/Родос між/Royal шпон/Avalon Шпон скло.jpg', 0),
  ('catalog-239', 'main', 'Avalon Шпон', 'Сайт НД/Родос між/Royal шпон/Avalon Шпон.jpg', 0),
  ('catalog-240', 'main', 'Siena Asti скло', 'Сайт НД/Родос між/Siena фарба/Siena Asti скло.jpg', 0),
  ('catalog-241', 'main', 'Siena Asti', 'Сайт НД/Родос між/Siena фарба/Siena Asti.png', 0),
  ('catalog-242', 'main', 'Siena Laura скло', 'Сайт НД/Родос між/Siena фарба/Siena Laura скло.png', 0),
  ('catalog-243', 'main', 'Siena Laura', 'Сайт НД/Родос між/Siena фарба/Siena Laura.jpg', 0),
  ('catalog-244', 'main', 'Siena Rossi скло', 'Сайт НД/Родос між/Siena фарба/Siena Rossi скло.png', 0),
  ('catalog-245', 'main', 'Siena Rossi', 'Сайт НД/Родос між/Siena фарба/Siena Rossi.png', 0),
  ('catalog-246', 'main', 'MODERN STYLE 1   BLK', 'Сайт НД/Родос між/Style ПВХ/MODERN STYLE 1   BLK.jpg', 0),
  ('catalog-247', 'main', 'MODERN STYLE 1', 'Сайт НД/Родос між/Style ПВХ/MODERN STYLE 1.jpg', 0),
  ('catalog-248', 'main', 'MODERN Style 2   BLK', 'Сайт НД/Родос між/Style ПВХ/MODERN Style 2   BLK.jpg', 0),
  ('catalog-249', 'main', 'MODERN Style 2', 'Сайт НД/Родос між/Style ПВХ/MODERN Style 2.jpg', 0),
  ('catalog-250', 'main', 'MODERN STYLE 3     BLK', 'Сайт НД/Родос між/Style ПВХ/MODERN STYLE 3     BLK.jpg', 0),
  ('catalog-251', 'main', 'MODERN STYLE 3', 'Сайт НД/Родос між/Style ПВХ/MODERN STYLE 3.jpg', 0),
  ('catalog-252', 'main', 'MODERN STYLE 4  BLK', 'Сайт НД/Родос між/Style ПВХ/MODERN STYLE 4  BLK.jpg', 0),
  ('catalog-253', 'main', 'MODERN STYLE 4', 'Сайт НД/Родос між/Style ПВХ/MODERN STYLE 4.jpg', 0),
  ('catalog-254', 'main', 'MODERN STYLE 5    BLK4', 'Сайт НД/Родос між/Style ПВХ/MODERN STYLE 5    BLK4.jpg', 0),
  ('catalog-255', 'main', 'MODERN STYLE 5', 'Сайт НД/Родос між/Style ПВХ/MODERN STYLE 5.jpg', 0),
  ('catalog-256', 'main', 'Proof 1.5 Slim P Double', 'Сайт НД/СТРАЖ/Вулиця/Proof 1.5 Slim P Double.webp', 0),
  ('catalog-257', 'main', 'Proof 2.3 Alfa Rio Double', 'Сайт НД/СТРАЖ/Вулиця/Proof 2.3 Alfa Rio Double.webp', 0),
  ('catalog-258', 'main', 'Proof 2.3 Estra Slim Double', 'Сайт НД/СТРАЖ/Вулиця/Proof 2.3 Estra Slim Double.webp', 0),
  ('catalog-259', 'main', 'Proof Forza', 'Сайт НД/СТРАЖ/Вулиця/Proof Forza.webp', 0),
  ('catalog-260', 'main', 'Proof Malta', 'Сайт НД/СТРАЖ/Вулиця/Proof Malta.webp', 0),
  ('catalog-261', 'main', 'PROOF Nominal', 'Сайт НД/СТРАЖ/Вулиця/PROOF Nominal.webp', 0),
  ('catalog-262', 'main', 'Proof Regola', 'Сайт НД/СТРАЖ/Вулиця/Proof Regola.webp', 0),
  ('catalog-263', 'main', 'PROOF Rio-S Loft', 'Сайт НД/СТРАЖ/Вулиця/PROOF Rio-S Loft.webp', 0),
  ('catalog-264', 'main', 'PROOF Slim S', 'Сайт НД/СТРАЖ/Вулиця/PROOF Slim S.webp', 0),
  ('catalog-265', 'main', 'Proof Valetta', 'Сайт НД/СТРАЖ/Вулиця/Proof Valetta.webp', 0),
  ('catalog-266', 'main', 'PROOF Vega Maxi', 'Сайт НД/СТРАЖ/Вулиця/PROOF Vega Maxi.webp', 0),
  ('catalog-267', 'main', 'Straj Proof 2.0 Alfa Doble', 'Сайт НД/СТРАЖ/Вулиця/Straj Proof 2.0 Alfa Doble.webp', 0),
  ('catalog-276', 'main', 'Піраміс', 'Сайт НД/СТРАЖ/Квартира/Піраміс.webp', 0),
  ('catalog-268', 'main', 'Avenue', 'Сайт НД/СТРАЖ/Квартира/Avenue.webp', 0),
  ('catalog-269', 'main', 'Delica AL Mono', 'Сайт НД/СТРАЖ/Квартира/Delica AL Mono.webp', 0),
  ('catalog-270', 'main', 'Fusion Vertical', 'Сайт НД/СТРАЖ/Квартира/Fusion Vertical.webp', 0),
  ('catalog-271', 'main', 'Orlanda', 'Сайт НД/СТРАЖ/Квартира/Orlanda.webp', 0),
  ('catalog-272', 'main', 'Slim S Glass-A', 'Сайт НД/СТРАЖ/Квартира/Slim S Glass-A.webp', 0),
  ('catalog-273', 'main', 'Terra S New', 'Сайт НД/СТРАЖ/Квартира/Terra S New.webp', 0),
  ('catalog-274', 'main', 'Tira', 'Сайт НД/СТРАЖ/Квартира/Tira.webp', 0),
  ('catalog-275', 'main', 'Vodaria', 'Сайт НД/СТРАЖ/Квартира/Vodaria.webp', 0),
  ('catalog-277', 'main', 'Berez Lux Mela B', 'Сайт НД/СТРАЖ/Склад/Berez Lux Mela B.webp', 0),
  ('catalog-278', 'main', 'Berez Lux Porte', 'Сайт НД/СТРАЖ/Склад/Berez Lux Porte.webp', 0),
  ('catalog-279', 'main', 'Florence', 'Сайт НД/СТРАЖ/Склад/Florence.webp', 0),
  ('catalog-280', 'main', 'Fusion Vertical', 'Сайт НД/СТРАЖ/Склад/Fusion Vertical.webp', 0),
  ('catalog-281', 'main', 'Prestige Delica AL Mono', 'Сайт НД/СТРАЖ/Склад/Prestige Delica AL Mono.webp', 0),
  ('catalog-282', 'main', 'Prestige Matrix', 'Сайт НД/СТРАЖ/Склад/Prestige Matrix.webp', 0),
  ('catalog-283', 'main', 'Prestige Terra S New', 'Сайт НД/СТРАЖ/Склад/Prestige Terra S New.webp', 0),
  ('catalog-284', 'main', 'PROOF Nominal', 'Сайт НД/СТРАЖ/Склад/PROOF Nominal.webp', 0),
  ('catalog-285', 'main', 'PROOF Party D 1200', 'Сайт НД/СТРАЖ/Склад/PROOF Party D 1200.webp', 0),
  ('catalog-286', 'main', 'PROOF Party D', 'Сайт НД/СТРАЖ/Склад/PROOF Party D.webp', 0),
  ('catalog-287', 'main', 'PROOF Rio-S Loft 1200', 'Сайт НД/СТРАЖ/Склад/PROOF Rio-S Loft 1200.webp', 0),
  ('catalog-288', 'main', 'PROOF Rio-S Loft', 'Сайт НД/СТРАЖ/Склад/PROOF Rio-S Loft.webp', 0),
  ('catalog-289', 'main', 'PROOF Slim S 1200', 'Сайт НД/СТРАЖ/Склад/PROOF Slim S 1200.webp', 0),
  ('catalog-290', 'main', 'PROOF Slim S', 'Сайт НД/СТРАЖ/Склад/PROOF Slim S.webp', 0),
  ('catalog-291', 'main', 'ROOF Vega Maxi', 'Сайт НД/СТРАЖ/Склад/ROOF Vega Maxi.webp', 0),
  ('catalog-293', 'main', 'Standart Піраміс', 'Сайт НД/СТРАЖ/Склад/Standart Піраміс.webp', 0),
  ('catalog-292', 'main', 'Standart Mirage', 'Сайт НД/СТРАЖ/Склад/Standart Mirage.webp', 0),
  ('catalog-294', 'main', 'Street PF Rio-S', 'Сайт НД/СТРАЖ/Склад/Street PF Rio-S.webp', 0),
  ('catalog-295', 'main', 'модель 41', 'Сайт НД/Термінус/Caro/модель 41.webp', 0),
  ('catalog-296', 'main', 'модель 50', 'Сайт НД/Термінус/Caro/модель 50.webp', 0),
  ('catalog-297', 'main', 'модель 52', 'Сайт НД/Термінус/Caro/модель 52.webp', 0),
  ('catalog-298', 'main', 'модель 53', 'Сайт НД/Термінус/Caro/модель 53.webp', 0),
  ('catalog-299', 'main', 'модель 55', 'Сайт НД/Термінус/Caro/модель 55.webp', 0),
  ('catalog-300', 'main', 'модель 109', 'Сайт НД/Термінус/Elit plus/модель 109.webp', 0),
  ('catalog-301', 'main', 'модель 111', 'Сайт НД/Термінус/Elit plus/модель 111.webp', 0),
  ('catalog-302', 'main', 'модель 112', 'Сайт НД/Термінус/Elit plus/модель 112.webp', 0),
  ('catalog-303', 'main', 'модель 24.1', 'Сайт НД/Термінус/Frezato/модель 24.1.webp', 0),
  ('catalog-304', 'main', 'модель 24.2', 'Сайт НД/Термінус/Frezato/модель 24.2.webp', 0),
  ('catalog-305', 'main', 'модель 24.3', 'Сайт НД/Термінус/Frezato/модель 24.3.webp', 0),
  ('catalog-306', 'main', 'модель 24.4', 'Сайт НД/Термінус/Frezato/модель 24.4.webp', 0),
  ('catalog-307', 'main', 'модель 24.5', 'Сайт НД/Термінус/Frezato/модель 24.5.webp', 0),
  ('catalog-308', 'main', 'модель 29', 'Сайт НД/Термінус/Frezato/модель 29.webp', 0),
  ('catalog-309', 'main', 'модель 704', 'Сайт НД/Термінус/Frezato/модель 704.webp', 0),
  ('catalog-310', 'main', 'модель 705.1', 'Сайт НД/Термінус/Frezato/модель 705.1.webp', 0),
  ('catalog-311', 'main', 'модель 705.2', 'Сайт НД/Термінус/Frezato/модель 705.2.webp', 0),
  ('catalog-312', 'main', 'модель 705.3', 'Сайт НД/Термінус/Frezato/модель 705.3.webp', 0),
  ('catalog-313', 'main', 'модель 705.4', 'Сайт НД/Термінус/Frezato/модель 705.4.webp', 0),
  ('catalog-314', 'main', 'модель 706.1', 'Сайт НД/Термінус/Frezato/модель 706.1.webp', 0),
  ('catalog-315', 'main', 'модель 706.2', 'Сайт НД/Термінус/Frezato/модель 706.2.webp', 0),
  ('catalog-316', 'main', 'модель 706.3', 'Сайт НД/Термінус/Frezato/модель 706.3.webp', 0),
  ('catalog-317', 'main', 'модель 707.1', 'Сайт НД/Термінус/Frezato/модель 707.1.webp', 0),
  ('catalog-318', 'main', 'модель 707.2', 'Сайт НД/Термінус/Frezato/модель 707.2.webp', 0),
  ('catalog-319', 'main', 'модель 707.3', 'Сайт НД/Термінус/Frezato/модель 707.3.webp', 0),
  ('catalog-320', 'main', 'модель 707.4', 'Сайт НД/Термінус/Frezato/модель 707.4.webp', 0),
  ('catalog-321', 'main', 'модель 708', 'Сайт НД/Термінус/Frezato/модель 708.webp', 0),
  ('catalog-322', 'main', 'модель 714', 'Сайт НД/Термінус/Frezato/модель 714.webp', 0),
  ('catalog-323', 'main', 'модель 715', 'Сайт НД/Термінус/Frezato/модель 715.webp', 0),
  ('catalog-324', 'main', 'ПК-01', 'Сайт НД/Термінус/Light/ПК-01.webp', 0),
  ('catalog-325', 'main', 'ПК-02', 'Сайт НД/Термінус/Light/ПК-02.webp', 0),
  ('catalog-326', 'main', 'ПК-03', 'Сайт НД/Термінус/Light/ПК-03.webp', 0),
  ('catalog-327', 'main', 'ПК-04', 'Сайт НД/Термінус/Light/ПК-04.webp', 0),
  ('catalog-328', 'main', 'ПК-05', 'Сайт НД/Термінус/Light/ПК-05.webp', 0),
  ('catalog-329', 'main', 'ПК-06', 'Сайт НД/Термінус/Light/ПК-06.webp', 0),
  ('catalog-330', 'main', 'ПК-07', 'Сайт НД/Термінус/Light/ПК-07.webp', 0),
  ('catalog-331', 'main', 'ПК-08', 'Сайт НД/Термінус/Light/ПК-08.webp', 0),
  ('catalog-332', 'main', 'ПК-09', 'Сайт НД/Термінус/Light/ПК-09.webp', 0),
  ('catalog-333', 'main', 'ПК-10', 'Сайт НД/Термінус/Light/ПК-10.webp', 0),
  ('catalog-334', 'main', 'ПК-11', 'Сайт НД/Термінус/Light/ПК-11.webp', 0),
  ('catalog-335', 'main', 'ПК-12', 'Сайт НД/Термінус/Light/ПК-12.webp', 0),
  ('catalog-336', 'main', 'ПК-13', 'Сайт НД/Термінус/Light/ПК-13.webp', 0),
  ('catalog-337', 'main', 'ПК-14', 'Сайт НД/Термінус/Light/ПК-14.webp', 0),
  ('catalog-338', 'main', 'ПК-15', 'Сайт НД/Термінус/Light/ПК-15.webp', 0),
  ('catalog-339', 'main', 'ПК-16', 'Сайт НД/Термінус/Light/ПК-16.webp', 0),
  ('catalog-340', 'main', 'ПК-17', 'Сайт НД/Термінус/Light/ПК-17.webp', 0),
  ('catalog-341', 'main', 'модель 401', 'Сайт НД/Термінус/Neoclassico/модель 401.webp', 0),
  ('catalog-342', 'main', 'модель 402', 'Сайт НД/Термінус/Neoclassico/модель 402.webp', 0),
  ('catalog-343', 'main', 'модель 404', 'Сайт НД/Термінус/Neoclassico/модель 404.webp', 0),
  ('catalog-344', 'main', 'модель 601', 'Сайт НД/Термінус/Neoclassico/модель 601.webp', 0),
  ('catalog-345', 'main', 'модель 602', 'Сайт НД/Термінус/Neoclassico/модель 602.webp', 0),
  ('catalog-346', 'main', 'модель 603', 'Сайт НД/Термінус/Neoclassico/модель 603.webp', 0),
  ('catalog-347', 'main', 'модель 604', 'Сайт НД/Термінус/Neoclassico/модель 604.webp', 0),
  ('catalog-348', 'main', 'модель 605', 'Сайт НД/Термінус/Neoclassico/модель 605.webp', 0),
  ('catalog-349', 'main', 'модель 606', 'Сайт НД/Термінус/Neoclassico/модель 606.webp', 0),
  ('catalog-350', 'main', 'модель 607', 'Сайт НД/Термінус/Neoclassico/модель 607.webp', 0),
  ('catalog-351', 'main', 'модель 608', 'Сайт НД/Термінус/Neoclassico/модель 608.webp', 0),
  ('catalog-352', 'main', 'модель 609', 'Сайт НД/Термінус/Neoclassico/модель 609.webp', 0),
  ('catalog-353', 'main', 'модель 801', 'Сайт НД/Термінус/Solid/модель 801.webp', 0),
  ('catalog-354', 'main', 'модель 802', 'Сайт НД/Термінус/Solid/модель 802.webp', 0),
  ('catalog-355', 'main', 'модель 803', 'Сайт НД/Термінус/Solid/модель 803.webp', 0),
  ('catalog-356', 'main', 'модель 804', 'Сайт НД/Термінус/Solid/модель 804.webp', 0),
  ('catalog-357', 'main', 'модель 805', 'Сайт НД/Термінус/Solid/модель 805.webp', 0),
  ('catalog-358', 'main', 'модель 806', 'Сайт НД/Термінус/Solid/модель 806.webp', 0),
  ('catalog-359', 'main', 'модель 807', 'Сайт НД/Термінус/Solid/модель 807.webp', 0),
  ('catalog-360', 'main', 'модель 808', 'Сайт НД/Термінус/Solid/модель 808.webp', 0),
  ('catalog-361', 'main', 'модель 809', 'Сайт НД/Термінус/Solid/модель 809.webp', 0),
  ('catalog-362', 'main', 'модель 810', 'Сайт НД/Термінус/Solid/модель 810.webp', 0),
  ('catalog-363', 'main', 'модель 812', 'Сайт НД/Термінус/Solid/модель 812.webp', 0),
  ('catalog-1', 'main', 'Harmonia', 'Сайт НД/Abwehr/Квартира/Harmonia.webp', 0),
  ('catalog-2', 'main', 'Limana', 'Сайт НД/Abwehr/Квартира/Limana.webp', 0),
  ('catalog-3', 'main', 'Melany', 'Сайт НД/Abwehr/Квартира/Melany.webp', 0),
  ('catalog-4', 'main', 'Mira', 'Сайт НД/Abwehr/Квартира/Mira.webp', 0),
  ('catalog-5', 'main', 'Rain', 'Сайт НД/Abwehr/Квартира/Rain.webp', 0),
  ('catalog-6', 'main', 'Riviera', 'Сайт НД/Abwehr/Квартира/Riviera.webp', 0),
  ('catalog-7', 'main', 'Selena', 'Сайт НД/Abwehr/Квартира/Selena.webp', 0),
  ('catalog-8', 'main', 'Stella', 'Сайт НД/Abwehr/Квартира/Stella.webp', 0),
  ('catalog-9', 'main', 'Avenue', 'Сайт НД/Abwehr/Склад/Avenue.jpg', 0),
  ('catalog-10', 'main', 'Carat', 'Сайт НД/Abwehr/Склад/Carat.jpg', 0),
  ('catalog-11', 'main', 'Queen', 'Сайт НД/Abwehr/Склад/Queen.jpg', 0),
  ('catalog-12', 'main', 'Revolution', 'Сайт НД/Abwehr/Склад/Revolution.jpg', 0),
  ('catalog-13', 'main', 'Tower 1200', 'Сайт НД/Abwehr/Склад/Tower 1200.jpg', 0),
  ('catalog-14', 'main', 'Tower', 'Сайт НД/Abwehr/Склад/Tower.jpg', 0),
  ('catalog-19', 'main', 'Delux ​​1', 'Сайт НД/Grand/DELUX/Delux ​​1.jpg', 0),
  ('catalog-20', 'main', 'Delux ​​10', 'Сайт НД/Grand/DELUX/Delux ​​10.jpg', 0),
  ('catalog-15', 'main', 'Delux 11', 'Сайт НД/Grand/DELUX/Delux 11.jpg', 0),
  ('catalog-16', 'main', 'Delux 12', 'Сайт НД/Grand/DELUX/Delux 12.jpg', 0),
  ('catalog-17', 'main', 'Delux 13', 'Сайт НД/Grand/DELUX/Delux 13.jpg', 0),
  ('catalog-18', 'main', 'Delux 14 BLK', 'Сайт НД/Grand/DELUX/Delux 14 BLK.jpg', 0),
  ('catalog-21', 'main', 'Delux ​​2', 'Сайт НД/Grand/DELUX/Delux ​​2.jpg', 0),
  ('catalog-22', 'main', 'Delux ​​3', 'Сайт НД/Grand/DELUX/Delux ​​3.jpg', 0),
  ('catalog-23', 'main', 'Delux ​​4 BLK', 'Сайт НД/Grand/DELUX/Delux ​​4 BLK.jpg', 0),
  ('catalog-24', 'main', 'Delux ​​4', 'Сайт НД/Grand/DELUX/Delux ​​4.jpg', 0),
  ('catalog-25', 'main', 'Delux ​​5', 'Сайт НД/Grand/DELUX/Delux ​​5.jpg', 0),
  ('catalog-26', 'main', 'Delux ​​6', 'Сайт НД/Grand/DELUX/Delux ​​6.jpg', 0),
  ('catalog-27', 'main', 'Delux ​​7', 'Сайт НД/Grand/DELUX/Delux ​​7.jpg', 0),
  ('catalog-28', 'main', 'Delux ​​8', 'Сайт НД/Grand/DELUX/Delux ​​8.jpg', 0),
  ('catalog-29', 'main', 'Delux ​​9', 'Сайт НД/Grand/DELUX/Delux ​​9.jpg', 0),
  ('catalog-30', 'main', 'Lux ​​1', 'Сайт НД/Grand/LUX/Lux ​​1.jpg', 0),
  ('catalog-31', 'main', 'Lux ​​11', 'Сайт НД/Grand/LUX/Lux ​​11.jpg', 0),
  ('catalog-32', 'main', 'Lux ​​13', 'Сайт НД/Grand/LUX/Lux ​​13.jpg', 0),
  ('catalog-33', 'main', 'Lux ​​14', 'Сайт НД/Grand/LUX/Lux ​​14.jpg', 0),
  ('catalog-34', 'main', 'Lux ​​2', 'Сайт НД/Grand/LUX/Lux ​​2.jpg', 0),
  ('catalog-35', 'main', 'Lux ​​3', 'Сайт НД/Grand/LUX/Lux ​​3.jpg', 0),
  ('catalog-36', 'main', 'Lux ​​4 BLK', 'Сайт НД/Grand/LUX/Lux ​​4 BLK.jpg', 0),
  ('catalog-37', 'main', 'Lux ​​5', 'Сайт НД/Grand/LUX/Lux ​​5.jpg', 0),
  ('catalog-38', 'main', 'Lux ​​6', 'Сайт НД/Grand/LUX/Lux ​​6.jpg', 0),
  ('catalog-39', 'main', 'Lux ​​8', 'Сайт НД/Grand/LUX/Lux ​​8.jpg', 0),
  ('catalog-40', 'main', 'Paint 1', 'Сайт НД/Grand/Paint/Paint 1.jpg', 0),
  ('catalog-41', 'main', 'Paint 10', 'Сайт НД/Grand/Paint/Paint 10.jpg', 0),
  ('catalog-42', 'main', 'Paint 11', 'Сайт НД/Grand/Paint/Paint 11.jpg', 0),
  ('catalog-43', 'main', 'Paint 12', 'Сайт НД/Grand/Paint/Paint 12.jpg', 0),
  ('catalog-44', 'main', 'Paint 2', 'Сайт НД/Grand/Paint/Paint 2.jpg', 0),
  ('catalog-45', 'main', 'Paint 3', 'Сайт НД/Grand/Paint/Paint 3.jpg', 0),
  ('catalog-46', 'main', 'Paint 4', 'Сайт НД/Grand/Paint/Paint 4.jpg', 0),
  ('catalog-47', 'main', 'Paint 5', 'Сайт НД/Grand/Paint/Paint 5.jpg', 0),
  ('catalog-48', 'main', 'Paint 6', 'Сайт НД/Grand/Paint/Paint 6.jpg', 0),
  ('catalog-49', 'main', 'Paint 7', 'Сайт НД/Grand/Paint/Paint 7.jpg', 0),
  ('catalog-50', 'main', 'Paint 8', 'Сайт НД/Grand/Paint/Paint 8.jpg', 0),
  ('catalog-51', 'main', 'Paint 9', 'Сайт НД/Grand/Paint/Paint 9.jpg', 0),
  ('catalog-52', 'main', 'Модель №711.1', 'Сайт НД/Magda/Вулиця/Модель №711.1.png', 0),
  ('catalog-53', 'main', 'Модель №945', 'Сайт НД/Magda/Вулиця/Модель №945.webp', 0),
  ('catalog-54', 'main', 'Стріт Арт', 'Сайт НД/Q Doors/Вулиця/Стріт Арт.webp', 0),
  ('catalog-55', 'main', 'Стріт Горизонталь', 'Сайт НД/Q Doors/Вулиця/Стріт Горизонталь.webp', 0),
  ('catalog-56', 'main', 'Стріт Елегант', 'Сайт НД/Q Doors/Вулиця/Стріт Елегант.webp', 0),
  ('catalog-57', 'main', 'Стріт Лайт', 'Сайт НД/Q Doors/Вулиця/Стріт Лайт.webp', 0),
  ('catalog-58', 'main', 'Стріт Спейс', 'Сайт НД/Q Doors/Вулиця/Стріт Спейс.webp', 0),
  ('catalog-59', 'main', 'Стріт Флай', 'Сайт НД/Q Doors/Вулиця/Стріт Флай.webp', 0),
  ('catalog-60', 'main', 'Аккорд AK', 'Сайт НД/Q Doors/Квартира/Аккорд AK.webp', 0),
  ('catalog-61', 'main', 'Бостон M', 'Сайт НД/Q Doors/Квартира/Бостон M.webp', 0),
  ('catalog-62', 'main', 'Босфор AK', 'Сайт НД/Q Doors/Квартира/Босфор AK.webp', 0),
  ('catalog-63', 'main', 'Лаунж', 'Сайт НД/Q Doors/Квартира/Лаунж.webp', 0),
  ('catalog-64', 'main', 'Люксор', 'Сайт НД/Q Doors/Квартира/Люксор.webp', 0),
  ('catalog-65', 'main', 'Міроу', 'Сайт НД/Q Doors/Квартира/Міроу.webp', 0),
  ('catalog-66', 'main', 'Стиль M', 'Сайт НД/Q Doors/Квартира/Стиль M.webp', 0),
  ('catalog-67', 'main', 'Тріоні', 'Сайт НД/Q Doors/Квартира/Тріоні.webp', 0),
  ('catalog-68', 'main', 'Aura', 'Сайт НД/Stildoors/Presto/Aura.jpg', 0),
  ('catalog-69', 'main', 'Avanti', 'Сайт НД/Stildoors/Presto/Avanti.jpg', 0),
  ('catalog-70', 'main', 'Diamond', 'Сайт НД/Stildoors/Presto/Diamond.jpg', 0),
  ('catalog-71', 'main', 'Elegante', 'Сайт НД/Stildoors/Presto/Elegante.jpg', 0),
  ('catalog-72', 'main', 'Fargo', 'Сайт НД/Stildoors/Presto/Fargo.jpg', 0),
  ('catalog-73', 'main', 'Grazia', 'Сайт НД/Stildoors/Presto/Grazia.jpg', 0),
  ('catalog-74', 'main', 'Karyon', 'Сайт НД/Stildoors/Presto/Karyon.jpg', 0),
  ('catalog-75', 'main', 'Palladio', 'Сайт НД/Stildoors/Presto/Palladio.jpg', 0),
  ('catalog-76', 'main', 'Toledo', 'Сайт НД/Stildoors/Presto/Toledo.jpg', 0),
  ('catalog-77', 'main', 'Wilton', 'Сайт НД/Stildoors/Presto/Wilton.jpg', 0),
  ('catalog-78', 'main', 'Arizona', 'Сайт НД/Stildoors/Stil/Arizona.jpg', 0),
  ('catalog-79', 'main', 'Barcelona', 'Сайт НД/Stildoors/Stil/Barcelona.jpg', 0),
  ('catalog-80', 'main', 'Cuba', 'Сайт НД/Stildoors/Stil/Cuba.jpg', 0),
  ('catalog-81', 'main', 'Florida', 'Сайт НД/Stildoors/Stil/Florida.jpg', 0),
  ('catalog-82', 'main', 'London', 'Сайт НД/Stildoors/Stil/London.jpg', 0),
  ('catalog-83', 'main', 'Mexico', 'Сайт НД/Stildoors/Stil/Mexico.jpg', 0),
  ('catalog-84', 'main', 'Slovenia', 'Сайт НД/Stildoors/Stil/Slovenia.jpg', 0)
on conflict (product_slug, kind, image_path) do update set
  label = excluded.label,
  sort_order = excluded.sort_order,
  is_active = true;
