"use client";
import { Facebook, Instagram, Mail, MapPin, Phone } from "lucide-react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
const schema = z.object({ name: z.string().min(2, "Вкажіть ваше ім’я"), phone: z.string().regex(/^\+380\d{9}$/, "Формат: +380XXXXXXXXX"), message: z.string().min(5, "Напишіть трохи більше деталей") });
type Contact = z.infer<typeof schema>;
export function Contacts() { const { register, handleSubmit, reset, formState: { errors, isSubmitSuccessful } } = useForm<Contact>({ resolver: zodResolver(schema), defaultValues: { phone: "+380" } }); return <section id="contacts" className="bg-sand py-16 sm:py-24"><div className="container-page grid gap-10 lg:grid-cols-2"><div><p className="eyebrow">Контакти</p><h2 className="heading mt-3">Завітайте до нас<br />у салон</h2><div className="mt-8 space-y-5">{[[MapPin, "Україна, м. Ужгород, вул. Льва Толстого, 88014"], [Phone, "+38 (095) 072-93-41 · +38 (068) 815-54-08"], [Mail, "nashidveri.uzh@gmail.com"]].map(([Icon, text]) => { const IconComp = Icon as typeof MapPin; return <div key={text as string} className="flex gap-4"><span className="rounded-full bg-white p-3 text-clay"><IconComp size={20} /></span><span className="pt-2 text-sm font-medium leading-6">{text as string}</span></div> })}</div><div className="mt-8 overflow-hidden rounded-2xl bg-[#d8d0c0] p-6 sm:p-8"><MapPin className="text-clay" /><p className="mt-16 font-display text-3xl">Наш салон<br />на карті Ужгорода</p><a target="_blank" rel="noreferrer" className="mt-3 inline-block text-sm font-bold underline" href="https://www.google.com/maps/search/?api=1&query=вул.+Льва+Толстого,+Ужгород">Відкрити маршрут →</a></div></div><form onSubmit={handleSubmit(() => reset({ name: "", phone: "+380", message: "" }))} className="rounded-2xl bg-white p-6 shadow-soft sm:p-8"><h3 className="font-display text-3xl">Напишіть нам</h3><p className="mt-2 text-sm text-stone-500">Допоможемо вибрати та відповімо на запитання.</p><label className="mt-7 block text-sm font-semibold">Ваше ім’я<input className="mt-2 w-full rounded-xl border px-4 py-3 outline-none focus:border-clay" {...register("name")} /></label>{errors.name && <p className="mt-1 text-xs text-red-600">{errors.name.message}</p>}<label className="mt-4 block text-sm font-semibold">Телефон<input className="mt-2 w-full rounded-xl border px-4 py-3 outline-none focus:border-clay" {...register("phone")} /></label>{errors.phone && <p className="mt-1 text-xs text-red-600">{errors.phone.message}</p>}<label className="mt-4 block text-sm font-semibold">Повідомлення<textarea rows={3} className="mt-2 w-full resize-none rounded-xl border px-4 py-3 outline-none focus:border-clay" placeholder="Наприклад, хочу підібрати двері…" {...register("message")} /></label>{errors.message && <p className="mt-1 text-xs text-red-600">{errors.message.message}</p>}{isSubmitSuccessful && <p className="mt-4 rounded-lg bg-green-50 p-3 text-sm text-pine">Дякуємо! Повідомлення надіслано.</p>}<button className="button-primary mt-6 w-full" type="submit">Надіслати повідомлення</button></form></div></section> }
export function Footer() { return <footer className="bg-ink pb-24 pt-10 text-stone-300 sm:pb-10"><div className="container-page flex flex-col justify-between gap-7 sm:flex-row"><div><p className="font-display text-2xl text-white">НАШІ ДВЕРІ</p><p className="mt-2 text-sm">Гарантія вашого затишку</p></div><div className="flex gap-5 text-sm"><a href="#home">Головна</a><a href="#catalog">Каталог</a><a href="#contacts">Контакти</a></div><div className="flex gap-3"><a aria-label="Facebook" href="#" className="rounded-full border border-white/20 p-2 hover:text-white"><Facebook size={18} /></a><a aria-label="Instagram" href="#" className="rounded-full border border-white/20 p-2 hover:text-white"><Instagram size={18} /></a></div></div><div className="container-page mt-10 border-t border-white/10 pt-5 text-xs text-stone-500">© НАШІ ДВЕРІ. Всі права застережено</div></footer> }
