import { ArrowUpRight, BadgeCheck, ClipboardCheck, Hammer, Ruler, ShieldCheck, PhoneCall, Truck } from "lucide-react";
import Link from "next/link";

export function TrustBar() { const items = [["15 хв", "на попередній розрахунок"], ["3", "ключові категорії для вашого дому"], ["Ужгород", "салон, замір і монтаж на місці"], ["1 заявка", "щоб отримати консультацію менеджера"]]; return <section className="container-page"><div className="grid border-x border-b border-stone-200 sm:grid-cols-2 lg:grid-cols-4">{items.map(([number, text]) => <div className="border-t border-stone-200 px-5 py-6 lg:border-l lg:first:border-l-0" key={number}><p className="font-display text-3xl text-clay">{number}</p><p className="mt-1 max-w-40 text-xs leading-5 text-stone-500">{text}</p></div>)}</div></section> }

const steps = [[PhoneCall, "01", "Заявка або дзвінок", "Розкажіть, що потрібно — менеджер уточнить деталі."], [Ruler, "02", "Безкоштовний замір", "Виміряємо отвори та допоможемо підібрати комплектацію."], [Truck, "03", "Доставка й монтаж", "Привеземо та професійно встановимо обране рішення."], [ShieldCheck, "04", "Гарантія", "Залишаємо контакти для гарантійного обслуговування."]];
export function Process() { return <section className="bg-ink py-16 text-white sm:py-24"><div className="container-page"><div className="max-w-2xl"><p className="eyebrow text-[#E8AE83]">Простий процес</p><h2 className="mt-3 font-display text-4xl leading-tight sm:text-5xl">Від заявки до гарантії — у чотири кроки</h2></div><div className="mt-11 grid gap-px overflow-hidden rounded-[1.5rem] border border-white/15 bg-white/15 md:grid-cols-2 xl:grid-cols-4">{steps.map(([Icon, number, title, text]) => { const IconComp = Icon as typeof Ruler; return <div className="bg-ink p-7 sm:p-8" key={title as string}><div className="flex items-start justify-between"><IconComp size={25} className="text-[#E8AE83]" /><span className="font-display text-2xl text-white/30">{number as string}</span></div><h3 className="mt-10 text-xl font-bold">{title as string}</h3><p className="mt-3 text-sm leading-6 text-stone-400">{text as string}</p></div>})}</div></div></section> }

export function FinalCta() { return <section className="container-page py-16 sm:py-24"><div className="grain relative overflow-hidden rounded-[2rem] bg-clay px-7 py-12 text-white sm:px-12 sm:py-16"><div className="absolute -right-12 -top-16 h-64 w-64 rounded-full border-[28px] border-white/15" /><div className="relative max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-100">Потрібна порада?</p><h2 className="mt-3 font-display text-4xl leading-tight sm:text-5xl">Підберемо рішення під ваш дім і бюджет</h2><p className="mt-5 max-w-lg leading-7 text-orange-50">Залиште заявку — менеджер зателефонує, уточнить задачу та підготує розрахунок.</p><Link href="/contacts" className="mt-8 inline-flex items-center gap-2 rounded-full bg-white px-6 py-3.5 text-sm font-bold text-ink transition hover:bg-sand">Отримати консультацію <ArrowUpRight size={17} /></Link></div></div></section> }
