import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { entranceBrands, type EntranceBrand } from "@/lib/entrance-brands";
import { catalogImageUrl } from "@/lib/catalog";
import { BrandLogo } from "./brand-logo";

export function EntranceBrands() { return <section className="container-page section-pad"><div className="grid overflow-hidden rounded-[2rem] bg-sand lg:grid-cols-[1fr_.8fr]"><div className="p-7 sm:p-10 lg:p-12"><p className="eyebrow">Вхідні двері</p><h1 className="heading mt-3">Оберіть фабрику</h1><p className="mt-5 max-w-xl text-lg leading-8 text-stone-600">Надійні дверні рішення для квартири, будинку чи комерційного простору.</p></div><img src="/design-assets/entrance-anthracite.png" alt="Сучасні антрацитові вхідні двері" className="h-64 w-full object-cover sm:h-80 lg:h-full" /></div><div className="mt-10 grid gap-5 md:grid-cols-3">{entranceBrands.map((brand) => <EntranceBrandCard key={brand.slug} brand={brand} />)}</div></section>; }

export function EntranceBrandCard({ brand }: { brand: EntranceBrand }) { return <Link href={`/vhidni-dveri/${brand.slug}`} aria-label={`Переглянути колекції фабрики ${brand.name}`} className="group block overflow-hidden rounded-[1.5rem] bg-sand transition hover:-translate-y-1 hover:shadow-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-clay"><article><div className="aspect-[1.3] bg-[#f7f5f1] p-4"><img src={catalogImageUrl(brand.image)} alt={brand.name} className="h-full w-full object-contain transition duration-500 group-hover:scale-[1.03]" /></div><div className="p-6"><p className="eyebrow">Фабрика</p><BrandLogo brand={brand.name} className="mt-3 h-10 max-w-[180px]" /><h2 className="mt-3 font-display text-2xl font-semibold tracking-[-.04em]">{brand.name}</h2><p className="mt-3 min-h-12 text-sm leading-6 text-stone-600">{brand.description}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-clay transition group-hover:text-ink">Переглянути колекції <ArrowUpRight size={16} /></span></div></article></Link>; }
