import Link from "next/link";
import Image from "next/image";
import { ArrowUpRight } from "lucide-react";
import { interiorBrands, type InteriorBrand } from "@/lib/interior-brands";
import { catalogImageUrl } from "@/lib/catalog";
import { BrandLogo } from "./brand-logo";

export function InteriorBrands() { return <section id="factories" className="container-page section-pad"><div className="grid overflow-hidden rounded-[2rem] bg-sand lg:grid-cols-[1fr_.8fr]"><div className="p-7 sm:p-10 lg:p-12"><p className="eyebrow">Міжкімнатні двері</p><h1 className="heading mt-3">Оберіть фабрику</h1><p className="mt-5 max-w-xl text-lg leading-8 text-stone-600">Переходьте до колекцій, порівнюйте моделі та залишайте заявку на прорахунок.</p></div><div className="relative h-64 w-full sm:h-80 lg:h-full"><Image src="/design-assets/interior-white.png" alt="Світлі міжкімнатні двері в інтер’єрі" fill sizes="(max-width: 1023px) 100vw, 42vw" className="object-cover" /></div></div><div className="mt-10 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{interiorBrands.map((brand) => <BrandCard key={brand.slug} brand={brand} />)}</div></section>; }

export function BrandCard({ brand }: { brand: InteriorBrand }) { return <Link href={`/mizhkimnatni-dveri/${brand.slug}`} aria-label={`Переглянути колекції фабрики ${brand.name}`} className="group block overflow-hidden rounded-[1.5rem] bg-sand transition hover:-translate-y-1 hover:shadow-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-clay"><article><div className="aspect-[1.3] bg-[#f7f5f1] p-4"><img src={catalogImageUrl(brand.image)} alt={brand.name} className="h-full w-full object-contain transition duration-500 group-hover:scale-[1.03]" /></div><div className="p-6"><p className="eyebrow">Фабрика</p><BrandLogo brand={brand.name} className="mt-3 h-10 max-w-[180px]" /><h2 className="mt-3 font-display text-2xl font-semibold tracking-[-.04em]">{brand.name}</h2><p className="mt-3 min-h-12 text-sm leading-6 text-stone-600">{brand.description}</p><p className="mt-4 text-xs font-semibold text-stone-500">Колекцій: {brand.collections.length || "незабаром"}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-clay transition group-hover:text-ink">Переглянути колекції <ArrowUpRight size={16} /></span></div></article></Link>; }
