"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ExternalLink, LoaderCircle, PackagePlus, RefreshCw } from "lucide-react";
import { AdminRouteGuard } from "@/components/admin-route-guard";
import { getSupabaseBrowserClient } from "@/lib/supabase-browser";

type Item = { url: string; title: string; image: string | null; brand: string; category: "interior" | "entrance"; collection: string };
type Preview = Item & { sourceUrl: string; productCode: string | null; description: string; images: string[]; facts: Array<{ label: string; value: string }> };
type Product = { slug: string; name: string; brand: string };
const button = "inline-flex items-center justify-center gap-2 rounded-xl border border-stone-300 bg-white px-3 py-2.5 text-sm font-bold transition hover:border-clay disabled:cursor-not-allowed disabled:opacity-50";
function normalize(value: string) { return value.toLocaleLowerCase("uk-UA").replace(/(?:rodos|міжкімнатн[а-яіїє]*|межкомнатн[а-яіїє]*|двер[іь]|door)/giu, " ").replace(/[^\p{L}\p{N}]+/gu, " ").trim(); }
function looksSame(left: string, right: string) { const a = normalize(left); const b = normalize(right); return a.length > 4 && b.length > 4 && (a === b || a.includes(b) || b.includes(a)); }
function hash(value: string) { let result = 5381; for (const char of value) result = (result * 33) ^ char.charCodeAt(0); return (result >>> 0).toString(36); }

function RodosImporterContent() {
  const supabase = useMemo(() => getSupabaseBrowserClient(), []);
  const [token, setToken] = useState(""); const [products, setProducts] = useState<Product[]>([]); const [items, setItems] = useState<Item[]>([]); const [active, setActive] = useState<Item | null>(null); const [preview, setPreview] = useState<Preview | null>(null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  useEffect(() => { supabase.auth.getSession().then(({ data }) => setToken(data.session?.access_token || "")); supabase.from("products").select("slug,name,brand").in("brand", ["Rodos", "Rodos Steel"]).then(({ data }) => setProducts((data || []) as Product[])); }, [supabase]);
  async function scan() { if (!token) return; setBusy(true); setNotice(""); try { const response = await fetch("/api/admin/import/rodos/catalog", { headers: { Authorization: "Bearer " + token } }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setItems(data.products || []); } catch (error) { setNotice(error instanceof Error ? error.message : "Не вдалося зчитати sitemap."); } finally { setBusy(false); } }
  async function inspect(item: Item) { if (!token) return; setBusy(true); setActive(item); setPreview(null); setNotice(""); try { const response = await fetch("/api/admin/import/rodos?url=" + encodeURIComponent(item.url), { headers: { Authorization: "Bearer " + token } }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setPreview(data); } catch (error) { setNotice(error instanceof Error ? error.message : "Не вдалося відкрити картку."); } finally { setBusy(false); } }
  async function addDraft() {
    if (!preview) return; const slug = "rodos-" + (preview.productCode || hash(preview.sourceUrl));
    if (products.some((product) => product.slug === slug)) { setNotice("Ця модель уже є в каталозі."); return; }
    setBusy(true); setNotice("");
    try {
      const image = preview.images[0] || preview.image;
      const inserted = await supabase.from("products").insert({ slug, category: preview.category, brand: preview.brand, collection: preview.collection, name: preview.title, material: preview.category === "entrance" ? "Вхідні" : "Міжкімнатні", style: "Колекція " + preview.collection, color: "Уточнюється", price: "Ціна за запитом", description: preview.description, features: [`Фабрика ${preview.brand}`, `Колекція ${preview.collection}`], image_path: image || null, sort_order: 99999, is_available: false });
      if (inserted.error) throw new Error(inserted.error.message);
      const requests: PromiseLike<{ error: { message: string } | null }>[] = [supabase.from("product_sources").insert({ product_slug: slug, source_name: "Rodos", source_url: preview.sourceUrl, source_product_name: preview.title, verification_status: "verified", verified_at: new Date().toISOString(), notes: "Імпорт з офіційної картки rodos.ua. Чернетка потребує перевірки перед публікацією." })];
      if (preview.facts.length) requests.push(supabase.from("product_specs").insert(preview.facts.map((fact, index) => ({ product_slug: slug, label: fact.label, value: fact.value, sort_order: 100 + index * 10, is_active: true }))));
      if (preview.images.length) requests.push(supabase.from("product_media").insert(preview.images.map((image, index) => ({ product_slug: slug, kind: index ? "gallery" : "main", label: index ? "Фото " + (index + 1) : "Головне фото", image_path: image, sort_order: index }))));
      const results = await Promise.all(requests); const failed = results.find((result) => result.error)?.error;
      setProducts((current) => [...current, { slug, name: preview.title, brand: preview.brand }]); setNotice(failed ? "Чернетку створено, але частина даних не збереглась: " + failed.message : "Чернетку створено. Вона прихована від покупців — перевірте й увімкніть її в «Товарах»." );
    } catch (error) { setNotice(error instanceof Error ? error.message : "Не вдалося додати чернетку."); } finally { setBusy(false); }
  }
  const rows = items.map((item) => ({ item, match: products.find((product) => product.brand === item.brand && looksSame(product.name, item.title)) })); const newCount = rows.filter((row) => !row.match).length;
  return <section className="space-y-5"><div className="rounded-3xl bg-ink px-5 py-8 text-white sm:px-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-sand">Офіційний імпорт</p><h1 className="mt-2 font-display text-4xl">Каталог Rodos</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/70">Сканер читає sitemap rodos.ua. Модель потрапляє у каталог лише як прихована чернетка, тому покупці не побачать її до вашої перевірки.</p><div className="mt-5 flex flex-wrap gap-2"><button className={button + " border-white/20 bg-white text-ink"} onClick={scan} disabled={busy || !token}>{busy ? <><LoaderCircle className="animate-spin" size={16} /> Скануємо…</> : <><RefreshCw size={16} /> Сканувати sitemap</>}</button><a className={button + " border-white/30 bg-transparent text-white hover:bg-white/10"} href="https://rodos.ua/sitemap.xml" target="_blank" rel="noreferrer">Відкрити sitemap <ExternalLink size={15} /></a></div></div>
    {notice && <p role="status" className="rounded-xl border bg-white p-4 text-sm text-stone-700">{notice}</p>}
    {items.length > 0 && <section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-display text-3xl">Знайдено {items.length} карток</h2><p className="mt-2 text-sm text-stone-600">Нові: <b>{newCount}</b>. Позначені «Схожа» варто звірити, щоб уникнути дублів.</p></div><Link href="/admin/catalog?brand=Rodos&quality=hidden" className="button-light">Чернетки Rodos</Link></div><div className="mt-5 grid gap-2 lg:grid-cols-2">{rows.map(({ item, match }) => <button key={item.url} onClick={() => inspect(item)} className="rounded-xl border border-stone-200 p-3 text-left transition hover:border-clay hover:bg-sand"><span className="flex items-start justify-between gap-3"><span><b className="block text-sm">{item.title}</b><span className="mt-1 block text-xs text-stone-500">{item.brand} · {item.collection}</span></span><span className={"shrink-0 rounded-full px-2 py-1 text-xs font-bold " + (match ? "bg-amber-100 text-amber-800" : "bg-green-100 text-green-800")}>{match ? "Схожа" : "Нова"}</span></span>{match && <span className="mt-2 block text-xs text-amber-800">Звірити з: {match.name}</span>}</button>)}</div></section>}
    {active && <section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-clay">Перевірка моделі</p><h2 className="mt-1 font-display text-3xl">{active.title}</h2></div><a className="button-light" href={active.url} target="_blank" rel="noreferrer">У виробника <ExternalLink size={15} /></a></div>{busy && !preview ? <p className="mt-5 text-sm text-stone-600">Завантажуємо фото, опис і характеристики…</p> : preview ? <><div className="mt-5 grid gap-5 lg:grid-cols-[260px_1fr]"><div>{preview.images[0] && <img src={preview.images[0]} alt={preview.title} className="h-72 w-full rounded-xl border object-contain p-2" />}</div><div><div className="flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-sand px-2.5 py-1">{preview.brand}</span><span className="rounded-full bg-sand px-2.5 py-1">{preview.collection}</span><span className="rounded-full bg-stone-100 px-2.5 py-1">буде прихована</span></div><p className="mt-4 text-sm leading-6 text-stone-700">{preview.description}</p><dl className="mt-4 grid gap-x-6 text-sm sm:grid-cols-2">{preview.facts.slice(0, 12).map((fact) => <div key={fact.label} className="flex justify-between gap-3 border-b py-2"><dt className="text-stone-500">{fact.label}</dt><dd className="text-right font-semibold">{fact.value}</dd></div>)}</dl></div></div><div className="mt-5 flex flex-wrap gap-2 border-t pt-4"><button className="button-primary" onClick={addDraft} disabled={busy || products.some((product) => product.slug === "rodos-" + (preview.productCode || hash(preview.sourceUrl)))}><PackagePlus size={16} /> Додати як чернетку</button><Link className="button-light" href="/admin/catalog?brand=Rodos&quality=hidden">Перевірити чернетки</Link></div></> : null}</section>}
  </section>;
}
export function RodosImporter() { return <AdminRouteGuard><RodosImporterContent /></AdminRouteGuard>; }
